### ISSUE TITLE
AL source positioning broken by a recent commit?

### ISSUE THREAD

**Issue by teistiz** [yquake2/yquake2#100]
Hey,

was just trying yquake2 built from git sources on my Debian laptop and noticed the OpenAL sound was pretty glitchy. By the end of base1 almost all enemy sound effects had weird volume and/or panning.

Since a stable build didn't seem to have this problem on Windows, I had a look at some recent commits. Now, I'm not very familiar with the Q2 codebase, but I'd guess 432fdc271b41551ea60c957aab67da3f4afd019b made all AL sources eventually get stuck with AL_SOURCE_RELATIVE set to AL_TRUE. I don't see anything that could reset the mode, at least.

**Comment by DanielGibson** [comment]
have you tried the very latest master including da2ac36cc6fa50c6723d7b74df98560803ee87a4 ?
Because I noticed today that one of the problems this Vector math stuff caused was sound coming from the wrong direction and the reverting fixed that for me.

**Comment by teistiz** [comment]
Yes, I only git clone'd this a couple of hours ago and can see da2ac36cc6fa50c6723d7b74df98560803ee87a4 in my local repo.

I think my quick hack to call `qalSourcei(ch->srcnum, AL_SOURCE_RELATIVE, AL_FALSE)` in AL_Spatialize when the sound is not coming from the view entity fixed this, but testing this is taking a while since the sound doesn't break immediately.

**Comment by DanielGibson** [comment]
Ok, I can reproduce the problem. But when near the end of base1, I cannot hear sounds with positions (gunfire from enemies, buttons, blaster projectile hitting the wall, ..) *at all*. So they're not all relative and thus have no direction, but they're absent (or so silent I can't hear them).

Further problem I noticed: If you still can hear the sounds around you, they're not coming from the right direction. A sound always comes out of the same speaker, regardless of player orientation.

I haven't looked at the source yet, but maybe the listener position and orientation isn't updated like it should, so you can only hear sounds that are relative when not near position (0,0,0).
This would at least explain the issue we noticed.

Not sure if the fix is gonna be easy, will have to dig into the source. Not sure when I have time for that, probably Yamagi and I will look at it next weekend.

**Comment by teistiz** [comment]
I can hear some of the positioned sounds on pretty good headphones, but most of them are very quiet. If the sources are getting stuck in relative mode, I'd guess whether one can hear them or not depends on how close they are to world (0, 0, 0) --- the effective listener position for relative AL sources.

Rushed through two units and I'm now pretty sure the bug is fixed by teistiz/yquake2@3b6aa98f170d1933028adf21948a3702ee47c138 .

**Comment by DanielGibson** [comment]
that can't be a proper fix, it basically reverts the commit that made it relative in the first place.

```
	if ((ch->entnum == -1) || (ch->entnum == cl.playernum + 1) || !ch->dist_mult)
	{
		qalSource3f(ch->srcnum, AL_POSITION, 0,0,0);
		qalSourcei(ch->srcnum, AL_SOURCE_RELATIVE, AL_TRUE);
		return;
	}
```
is  undone by the else-case below (because you made the `else if` below an `if`.
so it just reverts to all sounds being relative with a given position and this would cause the troubles 432fdc271b41551ea60c957aab67da3f4afd019b was supposed to fix.

**Comment by teistiz** [comment]
I'm pretty sure the return statement stops that from happening.

**Comment by DanielGibson** [comment]
oh, right, yeah.
so why did you remove the `else` from the `else if`?

**Comment by DanielGibson** [comment]
your patch works for me :-)

however, I'm still unsure why this is necessary - `qalSourcei(ch->srcnum, AL_SOURCE_RELATIVE, AL_TRUE);` explicitly only sets it for one source, not globally, so why should it be set for other sounds as well?

**Comment by teistiz** [comment]
I guess the "else" just felt redundant since the first if-block (that looks like a special case) returns.

The 432fdc271b41551ea60c957aab67da3f4afd019b commit that started this looks like it fixed a real problem by setting the AL_SOURCE_RELATIVE flag and (0,0,0) pos _when_ playing sounds that should be centered on the viewer at all times.

When those sounds finished playing, however, the sound source could get reused for an effect that actually wanted positioning. In this case, the AL_SOURCE_RELATIVE setting was never cleared and the sound was played with wrong listener transforms.

**Comment by DanielGibson** [comment]
True.

However I think that AL_SOURCE_RELATIVE should be set in `AL_PlayChannel()` instead of each update. Testing :)

**Comment by DanielGibson** [comment]
I think I fixed it, thanks a lot for the suggestions!

Does it work for you?

**Comment by teistiz** [comment]
Yeah, cleared a few more maps and got no sound glitches.

The commit looks nicer than the quick hack fix, too :)

**Comment by DanielGibson** [comment]
Awesome, thanks for reporting and testing!

**Comment by deuxsonic** [comment]
I noticed the sound for cinematics is kind of quiet compared to the volume of the menu sounds.

**Comment by mckaygerhard** [comment]
yeah, the sond of cinematics and music are pretty lower rather than effects ...

**Comment by deuxsonic** [comment]
Are cinematics treated as dynamic?
 


     On Sunday, October 25, 2015 12:04 PM, PICCORO Lenz McKAY <notifications@github.com> wrote:
   

 yeah, the sond of cinematics and music are pretty lower rather than effects ...—
