### ISSUE TITLE
Missing Gibs After Some Gameplay

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#104]
Simply put, as I play through the game, the game spawns gibs properly at first when an enemy/corpse is gibbed, but after a little while (it seems to start for me when gibbing enemies midway through the second map) when enemies are gibbed, only the head gib appears.

EDIT

It seems like there's a limit to the number of gibs that can be out at one time. I take out the machine gun and basically gib every enemy as I go.

**Comment by deuxsonic** [comment]
It seems to start right at the first enforcer in the installation.

**Comment by maraakate** [comment]
Daikatana had a similar issue where the gibs would disappear after some 
time and in that code there was an internal counter for the number of 
total gibs spawned that wasn't being cleared upon map transitions.

**Comment by deuxsonic** [comment]
Interesting. Yeah, I think it's happening where it is because there are so many guards right there at the start. I gibbed all of them and let the gibs disappear and then it was fine continuing. Somewhere there is a maximum number of gibs that can be created in the code. Perhaps it could be removed as it would not be a performance issue anymore?

**Comment by maraakate** [comment]
Besides performance, part of it's reason to exist is because of network 
traffic.  So keeping the limit for multiplayer has a purpose.

You should be able to test the issue quickly by setting cheats 1, 
timescale <high value like 9 or so> and watching the gibs fade then set 
timescale back to 1 and try it again.

Frank

**Comment by maraakate** [comment]
In g_func.c --> ThrowDebris and ThrowGib

     if (level.framenum > lastgibframe)
     {
         gibsthisframe = 0;
         lastgibframe = level.framenum;
     }

I don't know if framenum keeps incrementing between map transitions.  If 
not, then it would be the cause of gibs taking longer to reset.  In that 
case, on new map transitions resetting the gibsthisframe and 
lastgibframe to 0 would fix that issue.

Below that is a limit of 20.  In Daikatana, I have the limit controlled 
by a server-side CVAR (with CVAR_LATCH flag).  You could change the 
limit to be read by a CVAR like sv_gibs_max with the default limit of 
20.  However, that's up to Yamagi if that is an acceptable solution.  My 
design goals for my projects are different from Yamagi's.

It should be noted that ThowHead has no limit.

Frank

**Comment by deuxsonic** [comment]
I searched in g_func.c and couldn't find that.

**Comment by maraakate** [comment]
Should be there, I am using Q2DOS codebase which is basically using 
Yamagi's gamex86.  I don't have his source on hand.  I stay subscribed 
to YQ2 in-case game logic bugs such as these are found so I keep it 
maintained.

In any case, a good place to reset the counter would be ExitLevel in 
g_main.c

do a grep for lastgibframe and gibsthisframe.

Frank

**Comment by maraakate** [comment]
A way I would think is more correct would be to move lastgibframe and 
gibsthisframe to level_locals_t struct but it would break save games.  
Though, those two values could be reset to 0 in the same place as the 
memset for level struct.

Frank

**Comment by Yamagi** [comment]
The 20 gibs per frame limitation needs to stay there. Otherwise the network packages send from client to server may overflow and the whole game will crash. But 20 gibs per frame is more than enough, in 99.99% there are mush less gibs. Only in extreme situations like killing a lot enemies with the BFG will exceed that limit.

maraakate is right. lastgibframe should be reset on level / map change. Otherwise the condiditional resetting the gibsthisframe variable may never be executed resulting in no gibs being drawn.

**Comment by maraakate** [comment]
It looks like a good place to put it is in SpawnEntities after the 
memset for &level and g_edicts.

My plan is to reset lastgibframe = gibsthisframe = 0 at that point.

What do you think?  I won't push any changes to Q2DOS so I can mirror 
your results.

Frank

**Comment by maraakate** [comment]
I mean, personally I would prefer it be moved to the level struct itself 
so the memset &level will take care of it without having to do an extern 
of the two counters(since it would be per-level specific anyways).  But 
again, would break saves... which is OK for me to do so in Q2DOS since 
my user base is very limited.

Frank

**Comment by Yamagi** [comment]
I'll do something like that. :)

**Comment by maraakate** [comment]
Yeah, I'm just thinking of it while I look at it in front of me now quickly... but I'm sure you know of another struct that is memset on transitions that wouldn't break save compatibility.

Putting an extern to call those two seems sort of hacky, which is OK in Daikatana, but there's a higher standard here in regards to correct code with YQ2 :P.

**Comment by Yamagi** [comment]
The commited fix is more less solution suggested by maraakate
