### ISSUE TITLE
The weapon is rotated to the right relative to the vertical axis

### ISSUE THREAD

**Issue by maximus105** [yquake2/yquake2#1050]
When using software rendering, the weapon is rotated to the right relative to the vertical axis. This makes the weapon look very compressed. Other renders don't have this bug. Also, this bug is not present in the original Quake2 with software rendering. Is it possible to transfer the fix from the original ref_soft.dll for yquake 2, since the original Quake2 does not have this bug on the software renderer.

**Comment by Yamagi** [comment]
This is caused by the softrenderer being unable to calculate arbitrary projection matrices making it impossible to implement a correct gun fov. On whitescreen resolutions it's much worse than on classic 4:3 resolutions... The code is here: https://github.com/yquake2/yquake2/blob/master/src/client/refresh/soft/sw_alias.c#L735 Fixing this would need deeper changes to the software renderer which are unlikely to happen. Better use the GL3 renderer, it can emulate the software renderers look: https://github.com/yquake2/yquake2/blob/master/doc/030_configuration.md#renderer
