### ISSUE TITLE
Artifacts on the screen when choosing a grenade

### ISSUE THREAD

**Issue by maximus105** [yquake2/yquake2#1051]
When cycling a chaingun to a grenade and back, when cycling from a grenade launcher to a grenade, an artifact in the form of a part of a hand holding a grenade appears in the lower right corner of the screen. Tested in version 8.20. To reproduce this bug: run the give all command. rotate the mouse scroll forward/backward when selecting a grenade after the chaingun and before the granade launcher. This artifact always looks different (more/less). Also, during idle animation, the machinegun has a stump of the left hand, when the left hand does not hold the machinegun. This is noticeable at 2560x1440 resolution. The original Quake2 does not have this bug.

Issue is partially solved. You need to set a more precise value for r_gunfov. The r_gunfov value of -1 most closely matches the original Quake 2. But there is still a piece of the left hand holding the machinegun when removing the left hand down.

**Comment by Yamagi** [comment]
This is caused by the weapon models not build for the rather large gun fov needed for whitescreen resolutions. The wider the resolution, the worse it gets. It can't really be fixed, it's a trade-off between the model getting cut off and slightly missrendered or having an somewhat wrong gun fov.

If `r_gunfov -1` the gun is rendered at the global fov, which in relation to each other looks correct but might be too wide for the models to handle.

**Comment by protocultor** [comment]
@maximus105, you may try using this mod, which fixes the problem mentioned above by Yamagi:
https://www.nexusmods.com/quake2/mods/45
