### ISSUE TITLE
`gl1_overbrightbits` allows for invaild value

### ISSUE THREAD

**Issue by BraXi** [yquake2/yquake2#1080]
Setting `gl1_overbrightbits` to `3` causes opengl errors in calls to

`glTexEnvi(GL_TEXTURE_ENV, GL_RGB_SCALE_EXT, gl1_overbrightbits->value);`

> According to docs:
> If the pName parameter is GL_RGB_SCALE_EXT, or GL_ALPHA_SCALE,
> the Parameter(s) parameter is (or points to) a floating-point scale factor.
> Only three such scale factors are valid: 1.0, 2.0, and 4.0. The default value is 1.0.

Possible fix is to replace this line https://github.com/yquake2/yquake2/blob/e40f5d14804b40ae38a2972a5638954103735483/src/client/refresh/gl1/gl1_main.c#L1623 with `else if (gl1_overbrightbits->value > 2)`

Edit: Tested on NVIDIA GTX1650, Windows 10

**Comment by protocultor** [comment]
Look at this old issue (and its associated PR), which should explain the current state of `gl1_overbrightbits`: https://github.com/yquake2/yquake2/issues/1065
I never imagined it generated OGL errors using `3`. In my defense, the "limiter" didn't work anyway, since the name of the cvar was incorrect.

**Comment by apartfromtime** [comment]
> Look at this old issue (and its associated PR), which should explain the current state of `gl1_overbrightbits`: #1065 I never imagined it generated OGL errors using `3`. In my defense, the "limiter" didn't work anyway, since the name of the cvar was incorrect.

If "3" isn't a valid value, what value is opengl defaulting to? If you were trying to merge the two variables between gl1 and gl3 the code for overbrightbits in gl1->RI_BeginFrame was correct.

This also appears to be an IBM specific extension to the gl1 specification that was promoted in opengl 2.0, support for this should be tested at start-up in the gl1 code to avoid generating errors.

**Comment by protocultor** [comment]
> If "3" isn't a valid value, what value is opengl defaulting to? If you were trying to merge the two variables between gl1 and gl3 the code for overbrightbits in gl1->RI_BeginFrame was correct.

As I mentioned in the linked issue, I was trying to make sense of what the documentation said about `gl1_overbrightbits`, and why there was an inexistent cvar on its validator. Nothing more.
As I also mentioned, "3" was always a "valid" value, but that's because the validator was worrying about the inexistent cvar.

> This also appears to be an IBM specific extension to the gl1 specification that was promoted in opengl 2.0, support for this should be tested at start-up in the gl1 code to avoid generating errors.

Current Yamagi GL1 renderer needs OpenGL 1.4, and the needed extension for this (`*_texture_env_combine`) was already a core feature since 1.3:
https://registry.khronos.org/OpenGL/specs/gl/glspec14.pdf (page 285)

I'm currently working on a PR which not only solves this issue, but also shows OpenGL errors.

**Comment by apartfromtime** [comment]
> > If "3" isn't a valid value, what value is opengl defaulting to? If you were trying to merge the two variables between gl1 and gl3 the code for overbrightbits in gl1->RI_BeginFrame was correct.
> 
> As I mentioned in the linked issue, I was trying to make sense of what the documentation said about `gl1_overbrightbits`, and why there was an inexistent cvar on its validator. Nothing more. As I also mentioned, "3" was always a "valid" value, but that's because the validator was worrying about the inexistent cvar.
> 
> > This also appears to be an IBM specific extension to the gl1 specification that was promoted in opengl 2.0, support for this should be tested at start-up in the gl1 code to avoid generating errors.
> 
> Current Yamagi GL1 renderer needs OpenGL 1.4, and the needed extension for this (`*_texture_env_combine`) was already a core feature since 1.3: https://registry.khronos.org/OpenGL/specs/gl/glspec14.pdf (page 285)
> 
> I'm currently working on a PR which not only solves this issue, but also shows OpenGL errors.

You are correct, my mistake.

**Comment by Yamagi** [comment]
> I never imagined it generated OGL errors using `3`

And it didn't on my Radeon with radeonsi. Either the error was suppressed or the driver accepted a value of `3` and rounded it up or down without telling.

**Comment by BraXi** [comment]
`glGetError()` right after `glTexEnvi` and it returns code 1281 `GL_INVALID_VALUE`
![err](https://github.com/yquake2/yquake2/assets/6434152/ff15592e-0345-41c9-8fda-aca0a514b768)

I was porting overbrightbits to my little pragma engine and noticed that it's throwing error code after a call, checked YQ and it is doing the same.
