### ISSUE TITLE
OpenAL Hand Grenade Sound

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#111]
I decided to give OpenAL another try, and it works how I would expect now. However, I noticed with the hand grenades that the ticking sound of an armed grenade does not play.

**Comment by DanielGibson** [comment]
good find, for some reason `ent->client->weapon_sound` (see `void Weapon_Grenade (edict_t *ent)` in `player/weapon.c`)  is not audible - same for the "background wirring" of the chaingun and hyperblaster, btw, which are also played through `ent->client->weapon_sound`.

**Comment by maraakate** [comment]
The problem is not in the gamex86 code as I just tested in Q2DOS and the Q2DOS "Windows port" and the sounds work OK there.

**Comment by DanielGibson** [comment]
the change that triggered this was the latest commit, more specifically this change: https://github.com/yquake2/yquake2/commit/4e13e3ee69b85d006e68aa052f987680968d5265#diff-2ad82b35bf3f373dd217df2fe08e3cddL242
(not adding s_volume to ch->oal_vol anymore)

this doesn't seem to cause trouble in most cases, so I assume that ch->oal_vol is 0 or otherwise very small. It's assigned in `S_IssuePlaysound()` like this: `ch->oal_vol = ps->volume * (s_volume->value);` (no idea why that value is multiplied with s_volume there, I guess this should've been removed for the decoupling commit as well)
However, not multiplying with `s_volume->value` doesn't fix the problem, so probably ps->volume is 0 in that case

**Comment by DanielGibson** [comment]
ok, the bug is in `AL_AddLoopSounds()` - it also calls `AL_PlayChannel(ch)` (like S_IssuePlaysound()), but it doesn't set `ch->oal_vol`.
