### ISSUE TITLE
Juggernaut The Civic Center map has no keys

### ISSUE THREAD

**Issue by igorpupkinable** [yquake2/yquake2#1117]
This may not be the right place to post Juggernaut issue, but I would appreciate if you could advice on how to fix the following.

Juggernaut **The Civic Center** map (jug13) is missing red and blue keys as well as security pass.
Keys and pass placeholders are empty from the start, so no chance to open doors and progress to the next stage.

Is it possible to fix this with _ent_ files or other tweaks without source code?

Steps to reproduce:
1. Either progress through the mission pack or just `map jug13` in the console.
2. `noclip` in the console after map loading and fly to the top center of the map where one of the keys supposed to be placed.
3. **Expected:** both key placeholders/podiums have keys. **Actual:** none of the podiums have keys and security pass.

Thanks.

**Comment by Yamagi** [comment]
@BjossiAlfreds, can you have a look?

**Comment by BjossiAlfreds** [comment]
The key explodes, getting crushed by the moving brush I guess. I tested in the original engine and the key is where it should be. So something in YQ2 is different that is making the collision detection a bit more sensitive. I have no idea where though, this could be in the trace code or the physics code.

**Comment by Yamagi** [comment]
Maybe another floating point problem. YQ2 is compiled with 64 bit floats, the original quake2.exe used 80 bit floats. This has bitten us before, no matter which way we go - 64 bit or 80 bit - some things break. We have choosen 64 bit because 80 bit precision is bound to the x87 fpu only available on x86 CPUs.

**Comment by BjossiAlfreds** [comment]
I played around with the triggering sequence of the keys a bit more. There is this func_door with targetname "overhead" that is supposed to open first, and then the brush the key is resting on lowers through the opening.

If I trigger the "overhead" event first, and then "g_key" to lower the key, it seems to work. So this is looking more like a timing issue. The level designers might have tried values until the key stopped exploding to get the timing right, but when that sensitive balance changes it can break it.

I'll see if I can make the timings more forgiving to avoid the collision.

**Comment by BjossiAlfreds** [comment]
I've made an ent file that hopefully fixes this. See if it works.

The red key trigger lacked a delay of 1 second that the other key triggers had. I don't know why this setup works in the original, probably some sensitive balance that let this map bug slip by. I also saw another map bug where some targets were incorrectly naked r_cl instead of r_key_cl, so fixed that too.

[jug13ent.zip](https://github.com/user-attachments/files/16046300/jug13ent.zip)

**Comment by igorpupkinable** [comment]
@BjossiAlfreds thank you for looking into this.
Unfortunately the fix did not work for me. I have tried various difficulty levels, but unless I am doing something wrong no red key is available to open the first door to the cube with buttons. Both podiums are still empty as per pictures below, the door to "the cube" is shut and all keys are in the unreachable box above the stage ceiling.

![podium2](https://github.com/yquake2/yquake2/assets/2854230/dd47826c-d075-4078-b3b6-9e11a185c95d)
![podium1](https://github.com/yquake2/yquake2/assets/2854230/0ab766d1-a951-4e87-867f-7dc1a21a8a8b)
![keys](https://github.com/yquake2/yquake2/assets/2854230/52a476ac-f403-45af-99ac-9565440d4be5)
![door](https://github.com/yquake2/yquake2/assets/2854230/9cc26f14-9447-4d0c-a832-70bed4877d0e)

**Comment by BjossiAlfreds** [comment]
Are you using savegames? You have to load the level again from scratch for the changes to take effect,  that means either loading it from console or going through the level transition from the previous level.

I did fix another bug with this level after the previous upload. The shootable button that reveals the red key can be shot again, which could cause the key to explode.

If this file doesn't work for you then I don't have any further theories, as it works great for me.

[jug13ent2.zip](https://github.com/user-attachments/files/16103218/jug13ent2.zip)

**Comment by igorpupkinable** [comment]
Thank you for noting a **shootable button**. I falsely assumed keys should be placed on the podiums in the room where the window is and on the top floor in the middle. I have finally found the button and managed to get the keys one by one.
Your fixes and improvements are definitely working with my testing.

Thank you so much for looking into this!

Here is a picture of a button you need to shoot for anyone stuck and not knowing what to do next.
![button](https://github.com/yquake2/yquake2/assets/2854230/9b97a8ec-145b-4a05-be75-013c2c1dcded)

**Comment by BjossiAlfreds** [comment]
When I revisited Juggernaut 15 years later this level had me stuck for a while exactly because of the shootable button which I had completely forgotten about. Overall a badly designed level if you ask me.

The coincidence here is pretty amazing, too. You couldn't find the red key for a different reason, and it just so happened this exact trigger chain was actually faulty.

Happy to help out! I'll PR this mapfix so it is more readily available.
