### ISSUE TITLE
should let SDL choose its default audio backend

### ISSUE THREAD

**Issue by smcv** [yquake2/yquake2#1132]
SDL has its own logic for choosing a preferred audio backend: for example, on modern Linux it will try PulseAudio, Pipewire and direct ALSA, in some reasonable priority order.

While importing a newer yquake2 version into Debian I noticed that yquake2 bypasses this logic, by always setting the environment variable `SDL_AUDIODRIVER` to a value that it thinks is appropriate.

I think it would be better if yquake2 would delegate this decision to SDL, at least by default: SDL knows about more platforms than yquake2 does, and it has much better heuristics for choosing the best audio backend on a particular platform.

Perhaps this logic?

* `s_sdldriver` defaults to the empty string, or some suitable placeholder string like `auto`
* if it's the empty string or "auto", yquake2 doesn't touch `SDL_AUDIODRIVER` and lets SDL decide
* if it's non-empty and not "auto", yquake2 continues to set `SDL_AUDIODRIVER` as before

**Comment by Yamagi** [comment]
Good idea. The hard coded choices are a remnant of SDL 1.2 and have been long forgotten. I think they even break the SDL sound backend on Windows.  I'll change it in 8.41, likely to be released either tomorrow or on friday.

The `s_sdldriver` cvar now defaults to `auto` which let's SDL select the drive. Any other string forces SDL to select the driver identified by the given string.

**Comment by Yamagi** [comment]
Here's a Window testbuild with this fix included: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20240807-409c508.zip

**Comment by smcv** [comment]
Ah, I'd missed that yquake2 uses OpenAL by default, and SDL only on an opt-in basis (and the OpenAL backend seems to already have behaviour equivalent to what I asked for here, letting OpenAL choose precisely where to send the audio).

**Comment by Yamagi** [comment]
Nevertheless this was a legitimate request and at least on Windows the SDL sound backend was broken by forcing the `directsound` driver.

For OpenAL we don't provide any configuation options. If the user wants something else than OpenAL chooses, they must configure it in the OpenAL library.

**Comment by Yamagi** [comment]
Under Win 11 I had no audio with `directsound`.

**Comment by Yamagi** [comment]
I think I see the problem. Under Windows SDL2 and SDL3 default to `wasapi`. That is a sensible choice, because `directsound` and `winmm` use APIs declared as deprecated by Microsoft. However WASAPI guarantees only 32 bit floating point samples to be supported. Other samples might work, but they are depended on the driver or whatever.  
YQ2 leaves SDL when requesting the sample format. YQ2 requests something with 16 bit or even 8 bit samples, depending on the sound quality choosen by the user -> SDL might overwrite that with 32 bloat float -> YQ2 can't deliver that -> no sound. I have an experimental patch which forces SDL to obey YQ2s requests. With that `wasapi` should work under all circumstances.

Because that is rather invasive and there are other bugs in the SDL or sound backend...

> I noticed that a snd_restart would crash when started with +disconnect option.

...is only one of several `snd_restart` problem I found in ~10 minutes of testing, I'm going to set the default for Windows to `directsound` for the 8.41 release and look into it after the release.

**Comment by Yamagi** [comment]
And another test build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20240808-8cc3361.zip

**Comment by 0lvin** [comment]
> And another test build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20240808-8cc3361.zip

@Yamagi what do you think about use GitHub action to create windows build same as in remaster repository? It provides fast and simple way to create windows test build.

**Comment by Yamagi** [comment]
@0lvin, I have added CI builders with published artifacts for Linux, MacOS and Windows triggered on push and new or edited pull request. They should make our lives a little bit easier.

**Comment by 0lvin** [comment]
> @0lvin, I have added CI builders with published artifacts for Linux, MacOS and Windows triggered on push and new or edited pull request. They should make our lives a little bit easier.

Thank you, I have my rebased code over your version with small changes related to ffmpeg usage, and create release to tags for faster access to artifacts.

It looks like LTS version has used different version of ffmpeg, so I had also disabled ffmpeg for Linux build :-(

**Comment by Yamagi** [comment]
You can stay at something newer, of course. :) I choose ubuntu-latest - with is always the latest LTS - to have some confidence that the binaries work on older distributions and don't require a very up to date glibc and SDL.

My worker definitions are in fact based upon yours. I just altered the file structure in the generated archive a little bit to match the official Windows releases better (but not 100%) and added the code to rule out parallel builds for the same commit or pull request. And other triggers.

Other triggers because I didn't want to bind the builds onto tags. I want to preserve tags for official releases only, otherwise some overly motivated package maintainers will start to packet every tag for each testbuild I create. Instead an artifact should be generated after every push into the master branch and for every pull request.

I will update the README and homepage in the next few days to point to the generated artifacts. And I will give some love to the addons. A better README for them, maybe better documentation and CI builds.

**Comment by 0lvin** [comment]
I see :-)  I just added logic to put binary files to release if initiator was tag where it will stored for unlimited time, and left store to artifacts for default 90 days if it was pull request/master branch change.

It should help with case when we will have rarely changes in rerelease repository and last build are dropped. Or I need to check regression with windows builds as I manually remove release - 2 versions.
