### ISSUE TITLE
Idea For Meshes That Should Not Cast Shadows

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#121]
Having shadows enabled is nice but it gives shadows to all meshes, including things like blaster projectiles, turrets, and the plasma beam which wouldn't have shadows, as well as occasional things like lifts and other parts of the environment. Perhaps a CVAR configurable list of meshes that should not get shadows could be added in a similar fashion to how the console characters and crosshair are part of a list of graphics that should not get linear filtering? I think the main reason for people not to have shadows enabled (other than playing the game on old hardware) is because of these odd cases and many of them could be solved via this method.

**Comment by DanielGibson** [comment]
the shadows look crappy, not (only) because projectiles etc cast shadows, but because in the projected shadows polygons overlap and create darker spots within the same shadow, and they also flicker.
So I think it's unlikely that more people would use shadows with a CVar that disables shadows for some models, because they look bad for basically all models.

See:
![uglyshadow](https://cloud.githubusercontent.com/assets/1216493/12697099/09164f58-c77b-11e5-9971-7c03a00db930.png)

**Comment by deuxsonic** [comment]
Strange, they appear solid for me. Perhaps it's a difference with video drivers or hardware?
