### ISSUE TITLE
Improper particle scaling

### ISSUE THREAD

**Issue by SQU1D** [yquake2/yquake2#122]
Since executing 'pacman -Syu' the day before yesterday, I've had a problem where all particles are huge, like they're right up against the player, regardless of distance. Some examples [here](http://imgur.com/a/3ccYT).

**Comment by Yamagi** [comment]
Heh. That old problem again. Try turing the OpenGL point parameters extension of: gl_ext_pointparameters to 0 and vid_restart.

**Comment by maraakate** [comment]
Speaking of gl_ext_pointparemeters.  During Q2DOS testing with various Mesa versions we found out that once it was working properly (it was broken in early mesa revisions) that it had barely any impact on performance.  This may be true even today, but I haven't done any hard benchmarks on modern hardware.  May be worth disabling by default if this is a common issue.  It's disabled in Q2DOS by default since it had no real impact and certain Mesa versions it's broken anyways.
