### ISSUE TITLE
.md2 warping during animations - Any way to fix?

### ISSUE THREAD

**Issue by Thraka** [yquake2/yquake2#137]
Not sure if there is a command or anything like that with this engine but the way the models animate and warp (jello effect?) *always* bugged me. Is there anything in the engine that can fix that?

**Comment by Yamagi** [comment]
Hmm... Yes, that's annoying. The 'warping' is a side effect of the rather crude animation system built around keyframes. Each md2 model consists of a number of frames, several frames forming one animation. As a random example the code knows that frame 30 to 50 represent the 'crouch' animation of monster X, to be played with 10 fps. That's one keyframe each 1/20=0,05s. But of course the renderer draws a much higher number of frames, 60 fps means only one animation update each 6 frames. The animation would stutter. 

To prevent that Quake II interpolates artificial  animation steps between these keyframes. In the example given above the 5 steps are interpolated, each step with a small error. That Quake II relies on rather inaccurate floating point math doesn't make things better. So: There's no fix for it. One could try to write a more accurate interpolation code but that's lot of work and without new models with more keyframes likely no big improvement.

Quake III Arena works around that problem by using much more key frames. Most animations in Quake II have between 5 to 10 keyframes per second, Quake III Arena has 20 to 30. Half Life did better, it uses a skeletal animation systems. It hasn't such problems by design.

**Comment by Thraka** [comment]
Thanks for the great reply. I suppose supporting other model types is out of scope for this code base... ? 😺
