### ISSUE TITLE
gl_palettedtextures on or off?

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#150]
I've been confused about this cvar, because if I remember correctly, this corresponds with the 8-bit textures video option in vanilla quake. If I enable gl_ext_palettedtextures (now simply gl_palettedtextures), it would show "yes" for 8-bit textures under the video options. Then disabling palette textures would show "no" for 8-bit textures. 

To my understanding, if you have 8-bit textures enabled in Quake 2, this lowers texture quality. If I want best texture quality, what should I set gl_palettedtextures to?

**Comment by maraakate** [comment]
Set it off.  It's a relic from the 3DFX Voodoo 1 and 2 days where video 
memory was important.  With the Voodoo cards it can reduce image quality 
in exchange for more performance.  The palettedtextures implementation 
on Quake 1 itself is rather hit or miss even on those Voodoo cards.

Imo, because of the confusion like this and that very few people would 
remember it's specific reason for existence and that few to no people 
are going to run yq2 on a voodoo 1 (borderline unplayable) or voodoo 2 
maybe it should be deprecated?

Frank

**Comment by shoober420** [comment]
Thanks for clearing that up maraakate. I'll leave it at "0".
