### ISSUE TITLE
Corpses On Lifts Will Gib And Cause Lift To Go Back Down

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#156]
Very minor thing, but I thought I would mention it, as it seems this shouldn't be the desired effect. When you kill an enemy and there on a lift, if you press the button to activate the lift, it will gib the corpse and cause the lift to go back down so you have to hit the button again. I would imagine that the desired effect would be that the corpse comes along for the ride up the lift without gibbing.

**Comment by Yamagi** [comment]
That's the good old "corps is blocking the door or lift" problem. When a corps falls into the wrong place it may block other entities like doors or lifts. Since there may be a small difference between the entities origin (the position where the game logic sees it) and were the actual model is drawn, the block may not even be visible. As an example: The corps is lying in the middle of the elevator platform and there's no reason for the lift to get stuck. Unvisible to player the corps origin is right at the wall and clipping against it. So the lift can't move. The only way out is to gib the corps and - at least when things go really wrong - to wait until all gibs have disappeared. This was rarely seen in baseq2, but a common problem in poorly designed custom maps and the first addon.

As a work around we made lifts and doors more aggressive, the chance getting squished is higher than in the original Windows client. The client may even despawn gibs and debris, it'll just disappear if that happens. That may not be an ideal solution, but it's much better than adding map hacks for every lift prone to this.

**Comment by shoober420** [comment]
Ok awesome, thanks for the detailed answer.
