### ISSUE TITLE
Explosions don't render when player is half way submerged in water

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#161]
When you're half way submerged in water,  with your head still poking out, explosions don't render. A rocket launcher is best to test this with. The best example to try this out on is the tank commander in lower mines that the rock falls on when you pull the lever. There's a pool of water there in the room with him.

**Comment by maraakate** [comment]
Do they only not render on water where the water isn't transparent?

**Comment by shoober420** [comment]
I meant when your in the pool of water with a rocket launcher,  and shooting an enemy while your half way submerged in water, the explosions won't render. I worded that badly, sorry.

**Comment by maraakate** [comment]
Is the water transparent or not?  There are some areas of the game that you can dive underwater and look up and see outside.  Other maps you cannot, and this is a per-mapper choice to do this for (at the time) performance reasons.

I ask this because, if the water is not transparent and you're kind of bobbing to the surface to pull it off the game is probably getting confused on which "area" it should be rendering and clipping.

There may not be a proper fix for this particular problem due to that.

**Comment by shoober420** [comment]
It's non-transparent at that location. Could you think of a location with transparent water that has enemies you can shoot at off the top if your head I can test this at?

**Comment by maraakate** [comment]
map base3

As soon as you start there is a pool you can see the floor and inversely you can also be in the water and see outside.

I just tested on Q2DOS (which uses very similar codebase to YQ2) with the rocket launcher in this pool and I was able to see the explosions.

**Comment by maraakate** [comment]
You can start the map on hard, turn on god mode and lure the enemies out near the pool area as well.

**Comment by Yamagi** [comment]
That's a long standing issue. For performance reasons the game doesn't render some temporary entities when the player is inside an non transparent brush. For some reasons the game doesn't check if the player is just partly or complete inside the brush, rendering is always omitted.

**Comment by shoober420** [comment]
Sorry for thinking that was a bug lolol. Thanks for explaining that to me guys.
