### ISSUE TITLE
AI Bug In Base1?

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#174]
I've noticed this enemy will not be in this spot on the map if you don't adventure around (0:45). But, if you go through most up the map up until that point, he will show up there (2:15), and won't chase after you if you confront him. Its very odd. I'm not sure if this is enemy is supposed to behave this way and why he doesn't appear there unless you go through most of up map. Here's the video.

https://www.youtube.com/watch?v=BirkvNn6VA4

**Comment by DanielGibson** [comment]
Two things:
1. That guard (and one right behind the door to the last room) is only spawned after you grab the shotgun - otherwise it will turn up in the counter, but you won't find it and can't kill it.
2. That guard is connected to a point_combat, which is connected to a second point_combat which has the "hold" flag, which means the guard is supposed to stay there. Both are directly in front of the guard so it will only walk a very short way. I guess it's supposed to ambush the player from behind the crate and not run into players sight once it hears shots.

So it's all good, no bug here :)

**Comment by shoober420** [comment]
Awesome, thank you for the information.
