### ISSUE TITLE
Crash when trying to skip intro video

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#188]
When hitting esc or enter duirng the id intro video, the game crashes. I'm using the latest git build with the new OpenGL 3 renderer.

**Comment by shoober420** [comment]
Here's the error.

Product:      Yamagi Quake II
Version:      6.01pre
Platform:     Linux
Architecture: x86_64
Compiler:     6.3.1 20170306
Signal:       11

Backtrace:
  yamagi-quake2(+0x5c28b) [0x55b1c2d9e28b]
  yamagi-quake2(+0x5c485) [0x55b1c2d9e485]
  /usr/lib/libc.so.6(+0x33a90) [0x7f78c6461a90]

zsh: segmentation fault (core dumped)  yamagi-quake2

**Comment by DanielGibson** [comment]
can't reproduce - starting the game and then pressing escape (or another key) while the video is playing doesn't crash here.

when do you press escape? right at the beginning or more like 2-3 seconds into the video?

what happens if you don't press escape, does the demo start afterwards, do you get into the menu without crash when pressing escape then?

unfortunately the backtrace is not very helpful, as for some reason it's lacking the function names

**Comment by DanielGibson** [comment]
oh, and does it also crash if you press the "console key" (the one between Esc, 1 and Tab)? it should open the console instead of the menu then

**Comment by shoober420** [comment]
I found out what it was lol. I'm listening to music right now with Deadbeef, and while a song is playing, the game crashes if you try to skip the video, no matter how quick or long you wait during the id intro video. When stopping the song, I can skip the video with no problem. Not sure what to say about this lol

**Comment by DanielGibson** [comment]
wtf

must be some bug in the sound system (pulseaudio?) or driver or sth.. most strange.

**Comment by shoober420** [comment]
I don't use Pulseaudio, just plain ALSA. I have Deadbeef set to play bit exact audio, so it won't play any other sounds on the system except the music. It's he same thing with Foobar on windows and using the WASAPI output.
