### ISSUE TITLE
Missing libgcc_s_dw2-1.dll

### ISSUE THREAD

**Issue by Matthaiks** [yquake2/yquake2#205]
Yamagi Quake II 7.00 for Windows won't start without libgcc_s_dw2-1.dll.

**Comment by Yamagi** [comment]
*hmpf* I wonder why that didn't happen on one of my 4 Windows test VMs. The problem is, that all Quake 2 components and libz1.dll aren't build with -static-libgcc. Here's a new version: https://deponie.yamagi.org/quake2/misc/quake2-7.00-repacked.zip Can you give it a try and tell me if it solves the problem?

**Comment by Matthaiks** [comment]
The new version is fine. Thanks!

**Comment by Yamagi** [comment]
Cool, thank  you. I'll update the binary package in minute.
