### ISSUE TITLE
ref_ref_gl3.so

### ISSUE THREAD

**Issue by asuter-savvi** [yquake2/yquake2#209]
I am testing in Linux under Ubuntu 17.04 (currently the latest).
I am testing with stock Yamagi quake2 7.01.

I get an error when following this procedure:
- delete my ~/.yq2/baseq2/config.cfg
- start quake2: quake2 +vid_renderer ref_gl3
- quit from menu
- start quake2 a second time like this: quake2

It prints:-
...
----- refresher initialization -----
LoadLibrary(ref_ref_gl3.so)
Sys_LoadLibrary failed: /usr/lib/yamagi-quake2/ref_ref_gl3.so: cannot open shared object file: No such file or directory
Shutting down OpenAL.
Cmd_RemoveCommand: force_centerview not added
Cmd_RemoveCommand: +mlook not added
Cmd_RemoveCommand: -mlook not added
Shutting down input.
recursive shutdown
Error: Loading ref_ref_gl3.so as renderer lib failed!

:-)

**Comment by Yamagi** [comment]
`vid_renderer` sets the renderer name, the library name is deduced from it. So valid values are `gl1` for the old OpenGL1.4  renderer and `GL3` for the new OpenGL 3.2 renderer. The problem is, that vid_renderer is written to the config file even if it contains an invalid value. If pushed a small fix that ensures that vid_renderer is reset to `gl1` in case of problems.

**Comment by DanielGibson** [comment]
`gl3`, not `GL3` ;-)

so yeah, do `quake2 +vid_renderer gl3`
