### ISSUE TITLE
Problems with WITH_SYSTEMWIDE & distro packages putting binaries there; basepath

### ISSUE THREAD

**Issue by DanielGibson** [yquake2/yquake2#214]
Recently some problems with WITH_SYSTEMWIDE (as used by Linux/BSD distribution packages) and related things came up, e.g. in #183, #211, #213

WITH_SYSTEMWIDE lets you specify a directory (WITH_SYSTEMDIR) when compiling, that Quake2 will look in for game data and game dlls (game.so on Linux/BSD).

If I recall correctly, we added that long ago for debian packages I used to build (based on debian packaging scripts for their old "quake2" package, that used ioq2 or quake2forge or something).
Anyway, debian separated binaries and game data: binaries would go to /usr/lib/games/quake2/, while the game data was expected in /usr/share/games/quake2/ (and the quake2-data package used to put it there). There was also a /usr/games/quake2 shellscript (that directory is in $PATH) that changed the directory and called the real executable.

So SYSTEMDIR was supposed to be used for game data, not binaries - but unfortunately we didn't document that anywhere.. And the $mod/game.so still could be loaded from there, because all the game data search paths are searched for game.so (for mod support).
I don't even remember when exactly, but at some point we removed the old render lib (ref_gl.so) stuff and just integrated the renderer in the executable, as we only supported that one rendering backend anyway. So the only yq2 binary parts where the quake2 (or q2ded) executable and the game.so, no further plugins.

Now some distributions packages (at least Fedora, an Archlinux AUR and OpenBSD; the AUR has been fixed recently) just put the quake2 executable in /usr/bin/ (or some other directory in $PATH) and the game data **and** game.so's into the SYSTEMDIR - and while we didn't really intend that usage, it worked (because the only q2-specific lib yq2 was loading was the game.so).
(Debian now has an official yamagi-quake2 package, and it still separates binaries and data - I think the reasoning is that this way multiple installed quake2 ports can share the same game data. I think quake2 in some $PATH dir is a symlink to the real executable + indirection over /etc/alternatives/ magic. This seems to work well.) 

With 7.00 we reintroduced render libs (ref_gl1.so, ref_gl3.so), together with the new OpenGL3 renderer. These are expected to lie next to the executable itself, **so suddenly putting the executable in /usr/bin/ isn't that great anymore - you don't want ref_gl\*.so there..**

Now people have suggested loading ref_\*.so from SYSTEMDIR, but we don't really like that to be honest - we want the renderer plugins to lie next to the executable so people (possibly manually) updating their quake2 installation don't accidentally only update parts of it, causing weird bug reports we have to deal with.
And, as I said, SYSTEMDIR was supposed to be for game data, not executables (even if we failed to communicate that).

So now that is one big problem, but there are at least two related problems:
* To load ref_*.so, we get the executable path (Sys_GetBinaryDir()) and try to load it from there.  
  We get the real executable path there, so if you have /usr/bin/quake2 symlinked to /usr/lib/yamagi-quake2/quake2, the path will be /usr/lib/yamagi-quake2/.  
  This works great on all platforms we know of - **except for OpenBSD** which for some reason has no way to get the path to the executable (anymore? I think they used to support `/proc/$pid/file`...).  
  So OpenBSD would especially benefit from things being loaded from SYSTEMDIR, but maybe it'd also be ok to just make Sys_GetBinaryDir() return "./" and demand that $PWD is the binary dir. In that case, /usr/bin/yamagi-quake2 (or whatever) would just be a wrapper shellscript, like in the ancient debian packages.
    * If we fall back to "./" in Sys_GetBinaryDir(), should we try to do some sanity checks to make sure we actually are in the right directory and exit the game with an error if we're not? Like checking if ./quake2 exists?
      => what if it's not "quake2" but has been renamed to "yquake2" or whatever? Get executable name from main()'s argv[0]? Can we trust that?
* You can use `quake2 +set basedir /path/to/quake2/` to tell quake2 where to find the game data, in case it's not in the SYSTEMDIR or next to the binaries.  
  Unfortunately, **SYSTEMDIR is just used as the default value for the basedir cvar**, so setting the basedir will overwrite the compiled in SYSTEMDIR and stuff in SYSTEMDIR will be ignored - this includes SYSTEMDIR/baseq2/game.so for certain distro packages (see above)...
  Should we just always add SYSTEMDIR to the internal search path and also add basedir if set? Or is this not necessary as SYSTEMDIR *should* not contain binaries anyway?
* Whatever we decide to do, we should document it properly this time ;-)

**Comment by DanielGibson** [comment]
@fredericolima: you're maintaining the fedora quake2 package, right? Do you wanna chime in? :-)

**Comment by Yamagi** [comment]
Some general thoughts:

* The search path is divided into two sections. The game specific directories are at the beginning, the general directories including baseq2/ at the end. Since baseq2/ is added as a general directory it may not be added again as special directory. Some time ago I've added code to ensure that. And - to point it again - whatever is done to the search path, special directories *must* be placed in front of the general directories, e.g mod/ before baseq2/. Otherwise things will break. 

* This afternoon we had short internal discussion about the `cddir` stuff. I had a deeper look and it's still working. While I don't think that anyone is still using a partial install and loads parts of the game from CD the code is rather simple and not intruding. We won't gain much if we remove it.

* If SYSTEMWIDE is defined, the `basedir` cvar is set to SYSTEMDIR/ by default. Otherwise it's set to the current working directory. This is very problematic since defining `basedir` at the command line breaks the SYSTEMWIDE stuff. A trivial and easy to implement solution would be to introduce a new cvar `systemdir' or something like that. It's only available it SYSTEMWIDE is defined at set to SYSTEMDIR/ by default, it's content is added to the search path right behind `basedir`.

* In theory the same could be done for the binaries. Introduce a new cvar `bindir`, that's only available if SYSTEMWIDE is set. It's set to SYSTEMBINDIR/ by default, the various LoadLibrary() dialects look into it. The question is: If multiple binaries are available (on in `bindir`, one in `systemdir`, one in `basedir`, etc.) which one should be loaded?

**Comment by mulander** [comment]
From an OpenBSD perspective a clear approach would be to have:
 - binaries in `/usr/local/bin`
 - libraries in `/usr/local/lib/yquake2`
 - gamedata in `/usr/local/share/yquake2`

The responsibility for keeping updates clean and atomic lies on the package maintainer (me in this case).
That said and out of the way. I do understand why you don't want to do this as that obviously enables people to mix up setups in horrible ways.

Regarding obtaining the current executable - the proc file system has been removed from OpenBSD 5.7 in 2015 because it "always suffered from race conditions and is now unused". I don't think relying on argv is safe on any OS.

If you really want to keep control of where things live, then I think having a way to externally define the installation directory (since you want everything under the same tree) and explicitly due searches on that. I'm OK with that being a compile flag, environment variable or a flag I need to pass to the main executable before running it (that should also work with the dedicated server).

While writing this a reply from @Yamagi showed up. My vote is in favor for a SYSTEMBINDIR but I would like to point out that SYSTEMBINDIR will have one problem that needs to be documented - that the .so files need to live in the same folder or someone will point SYSTEMBINDIR at executables installed in `/usr/local/bin` and will complain that libraries loaded from `/usr/local/lib/yaquake2` are not loaded.

**Comment by Yamagi** [comment]
Maybe it would be better to choose `libdir` as cvar name and SYSTEMLIBDIR as internal name.

**Comment by mulander** [comment]
> Maybe it would be better to choose libdir as cvar name and SYSTEMLIBDIR as internal name.

That would actually allow me to install .so files into `/usr/local/lib/yquake2`. I assume `game.so` would still reside under `SYSTEMDIR` for mod compatibility. Regardless, if that setup is *allowed* I would happily implement and maintain integrity on our side. If you otherwise intend to enforce a single root for executables and shared libraries then I will of course also adhere. Just saying, being able to split them up feels warm and fuzzy ;)

**Comment by DanielGibson** [comment]
this does make things more complex though

**Comment by DanielGibson** [comment]
Oh, I'd like to add one thing to
> And, as I said, SYSTEMDIR was supposed to be for game data, not executables (even if we failed to communicate that).

Exception: Putting the game data *and* **all** binaries (executables, libs) there *should* also be ok and work with the code as it is now (except for the broken Sys_GetBinaryDir() thing on OpenBSD).  
(Though I still think that the debian way of separating binaries and data makes sense for distro packages, as it would allow installing another quake2 port, for example one with a stronger multiplayer focus, that could use the same game data)

**Comment by DanielGibson** [comment]
We fixed several of the problems discussed here in the searchpath branch (which is now merged to master) and we now have documentation for package maintainers: https://github.com/yquake2/yquake2/blob/master/stuff/packaging.md

We decided against introducing SYSTEMLIBDIR or similar, because it would add even more complexity to the already fragile search path magic.

**Comment by Yamagi** [comment]
Windows binaries with the refactored search path stuff can be found here: https://deponie.yamagi.org/quake2/misc/quake2-7f46d80.zip
