### ISSUE TITLE
Possible maps.lst behavior regression

### ISSUE THREAD

**Issue by deuxsonic** [yquake2/yquake2#260]
Before updating to the latest build, I had been using 5.33, which could seemingly read maps.lst placed inside of a PAK file, as there is no error in creating servers and all maps are selectable. The game now will show an error about not finding the file and will not allow creation of a server.

**Comment by CrusoeDaWolf** [comment]
I also have the same issue with version 7.02a. I didn't have this problem before updating.

**Comment by DanielGibson** [comment]
It was broken before: It loaded the maps.lst from baseq2's pak0.pak instead of the filesystem (regular directory) - but some Q2 update added new MP maps and added maps.lst in the filesystem which included the new maps.
Because in Q2 pak files generally have a higher priority than the filesystem, the outdated maps.lst was used, see #217 
Our fix/workaround is to only load maps.lst from the filesystem.
Please just put it there instead of into a pak.
