### ISSUE TITLE
Portable mode still saves to Documents folder

### ISSUE THREAD

**Issue by buvk** [yquake2/yquake2#276]
When I launch the game using +set portable 1, cfg files, log files, saves, etc all save to %userprofile%\documents\yamagiq2

I am running Windows 10 + Yamagi 7.10.

**Comment by DanielGibson** [comment]
I think we changed this in one of the last releases: You need to use `-portable` now instead of `+set portable 1`

**Comment by buvk** [comment]
Thank you.  That works.

**Comment by DanielGibson** [comment]
Great! Have fun :-)

**Comment by iButane** [comment]
> You need to use -portable now

This should be the default. Most people always look in, and expect, the current folder's (baseq2) config.cfg to be the active one.

**Comment by DwarfFighterCleric** [comment]
I also vote for this being the default. Users folder is such a hassle...
I like the way the Daikatana fan patch did it: if you create a text file named portable.cfg the game will make everything portable, so it's easier to switch back and forth... (that being said, this file should be shipped with it by default... so much unnecessary hassle...)
Just trying to help.

**Comment by buvk** [comment]
I agree.  Having that option would be great.  Dolphin emulator has a similar feature (portable.txt).

**Comment by maraakate** [comment]
> 
> 
> I also vote for this being the default. Users folder is such a hassle...
> I like the way the Daikatana fan patch did it: if you create a text file named portable.cfg the game will make everything portable, so it's easier to switch back and forth... (that being said, this file should be shipped with it by default... so much unnecessary hassle...)
> Just trying to help.

DK 1.3 dev here.  The reason it is not shipped this way by default is because practically all modern software (Windows, Linux, Mac, etc. does not matter) saves USER DATA in USER FOLDERS.  The old way was fine in 1998 when everyone was an Administrator but this is not the case any more.  It is not hard to right click -> new text document and type portable.cfg.  My theory is that if you know enough about this behaviour and can install this on your own you can handle making a portable.cfg file.

**Comment by Yamagi** [comment]
Or a little Batch file with something like this: `yquake2.exe -portable`

**Comment by DwarfFighterCleric** [comment]
> It is not hard to right click -> new text document and type portable.cfg

On that I agree. But at least mention it somewhere in the game's directory after shipping it. Don't force users to search it on google and waste their time. 
People asking this same question here more than once is a sympton that this information is not presented in a clean manner there.

**Comment by Yamagi** [comment]
The full documentation is shipped with the official Windows binaries. And you can always do something like `yquake2.exe -h`.

**Comment by lafoxxx92** [comment]
+1 for having this mode enabled by default.
Cool feature (like all these Win Vista "improvements"), but took me a while to locate the files.

**Comment by DwarfFighterCleric** [comment]
This issue is super annoying since NO ONE than I ever know that used computers for years, decades even, EVER NEEDED separate documents files for different users. People in families share the same computers and NEVER ONCE any of these measures were ever needed or used.  
It's just one of these things that are made unnecessarily complicated over-engineered just for the sake of it.  
And you can see by the developer's reaction that he is being stubborn, refusing to admit and refusing to perform this simple change.  
NO ONE ever reads "documentation" for a quake port, or doom port for that matter LOL The insanity of some people... enforce rules in a videogame... sounds like a perfectly reasonable idea LOL

**Comment by maraakate** [comment]
The reason Vista started enforcing this is because older applications (like Quake 2) were typically installed in Program Files directory.  Everyone was an Administrator on their computer which meant these programs had write access to everything.  It's too easy for something to corrupt files inside the directory (or even outside of it!).

The save games and config is saved to your local user directory.  This has the advantage that if you mess up a config, or it somehow becomes corrupted you can just delete this directory and start over.  The Quake 2 PAK files are unaffected, you don't have to sit there and guess if this file is important or not to the core application.

Also, installing the game today may default to not having write access to those directories.  I noticed this when installing Daikatana in Windows 10, so the game could crash in some situations when attempting to save the config file.  Which happens when changing a menu item, or exiting the game.

All other operating systems have been writing to separate local user directories for years; this is nothing new.  It's new to you on Windows because Windows allowed this bad behaviour for literally a decade.  It's one of the main reasons Windows was considered insecure and unstable.

You should read documentation on things you install to your computer.  Remember how easy it was to get a virus on Windows?  People neglect to read or understand what they are installing.  Thankfully, Windows has some fairly competent built-in scanning software these days, but it didn't for the XP-era.

**Comment by maraakate** [comment]
Also, the reason this is called 'portable mode' is because that is intended for being installed on a USB key with FAT32.  FAT32 has no concept of folder security/access control lists.  And if you're moving your USB key around to other machines then yes, you may want to keep those saves with you.  It's not really intended as a way for you to bypass proper user data segregation.  But, it works as such.

I think you are making this a bigger issue than it needs to be.  Practically every commercial game made in the past 10-15 years writes to your user data.  And I know someone will rebut with "well R1Q2 is a popular, stable port and doesn't do this crap!" and yeah you're right, but R1Q2 has not been maintained since 2008 or so.  It's a stable port, and R1CH put a lot of work into it, but it was from a different era and he hasn't worked on it in a very long time.

We're not making this default behaviour to piss you off; we're actually doing this because it's the right thing to do from a security standpoint and also because Windows is now enforcing this stuff.  Disabling UAC can cause strange side effects if not done properly.

If you say data corrupt is not an issue or is very rare... Daikatana had a bug where it was possible for the config to save improperly and loop through all the files in your data\ directory and zero them out.  It's just as easy to do in any Quake based engine, or any game rather.  A bug could introduced in YQ2 at any time which could cause this to happen.  If it did, with the new behaviour it would only ruin your config file and a couple of save games and maybe some custom multiplayer assets you downloaded via the client.

**Comment by maraakate** [comment]
And by failing to read documentation for things you install you're also robbing yourself of potential features that could be enabled (or in this case disabled) that you would be unaware about.

**Comment by DanielGibson** [comment]
Another thing is that it can happen that Windows doesn't even write the files into the installation dir, but (invisible to the game itself) writes them to some %appdata%/Roaming directory, which would make it even harder to find (User/Documents/YamagiQ2/ is pretty easy to navigate to, after all)

**Comment by maraakate** [comment]
Cool man.  Enjoy using R1Q2.

**Comment by maraakate** [comment]
And enjoy insulting other FOSS projects as I've looked back at your comment history.

**Comment by Yamagi** [comment]
I've blocked that guy. He's annoying.
