### ISSUE TITLE
Building 32 bit binaries?

### ISSUE THREAD

**Issue by ewg118** [yquake2/yquake2#300]
Is it possible to build 32 bit binaries instead of 64? I am attempting to run the Rocket Arena mod, which isn't functioning as it should. I believe it is because there's a gamei386.so and no 64 bit version. The documentation for ioquake3 indicates that Rocket Arena for Quake III should also be run as a dedicated server from the 32 bit binaries, rather than 64.

**Comment by Yamagi** [comment]
Hi,
that's perfectly possible. In fact our Windows releases are still 32 bit only since there's next to no advantage in having 64 bit binaries. How you do it depends on your distribution. If the distro has a working 32 bit environment it's often enough to install 32 bit versions of the dependencies (at least libvorbis, openal-soft and sdl20) and to pass -m32 to the compiler. You can do that by editing the CFLAGS in the Makefile line 172. Another way is to build a more or less complete 32 bit chroot environment, compile yquake2 there and set LD32_LIBRARY_PATH to the chroot when calling the executable.

And there's one big caveat: Very old mod libraries from the late 1990th or eary 2000th may be linked against libc.so.5 and not the modern libc.so.6. Since there can be only one libc instance in each process that's a deal breaker. I've never tried it but I don't think that's possible to link yquake2 against libc.so.5.

Regards,
Yamagi

**Comment by ewg118** [comment]
Thanks for the answer. I will try a few things and report back to the ticket if I get it compiled correctly.
