### ISSUE TITLE
Strange issue with audio quality setting

### ISSUE THREAD

**Issue by ghost** [yquake2/yquake2#301]
When you change the audio quality and hit left again or right again it'll end up playing a random music track.  It's even correctable by disabling and enabling ogg music but it'd be nice if it just didn't do that at all.  Shuffle is disabled too if you're wondering

OS: win10 1803
yamagi quake 7.20

**Comment by DanielGibson** [comment]
Congratulations, you're the first to find this bug (or at least weird behavior) - looking at the commit history, it has been in the client since 2009! :tada: :sparkles: :fireworks:

What's really weird is, Yamagi and me reworked the music code today, stumbled upon code that apparently plays a random track if the ogg code is (re)initialized and wondered what that's about and when it happens (apparently not when the game starts and that's first initialized).
A few minutes later you reported this bug..

Anyway, the next version will not do this anymore. For now I'd suggest to just not change the audio setting (leave it at high, it shouldn't even make a difference with the OpenAL sound backend that's used by default).

**Comment by AcceptableSpare** [comment]
Woo i feel special... v: sorta. Funny story I only found out about it by hitting the option by accident on my keyboard because I was testing the ogg files i ripped from the ground zero mission pack. It's pretty much a useless option to me unless I found a slower pc loaded with an old sound blaster card

**Comment by Yamagi** [comment]
This is fixed in 7.30.
