### ISSUE TITLE
New game bug

### ISSUE THREAD

**Issue by Sovero4ek** [yquake2/yquake2#318]
Help pls, I can't begin a new game I won't remove old preservations yet ( old save games ). After the beginning of a new game all progress remains, enemy not spawns.

**Comment by Yamagi** [comment]
So you're somewhere in the game, open the menu and start a new game through it. Instead of starting a new game it loads the last savegame?!

**Comment by Sovero4ek** [comment]
New game begins with the first level and dead opponents. Preservation, but since the beginning of a game is kind of loaded. Quake 2 the license steam, I reinstalled a game.

**Comment by Sovero4ek** [comment]
The last preservation from the first level will be loaded.

**Comment by DanielGibson** [comment]
I can't reproduce this - when I start a new game via menu (GAME => medium; or even with "map base1" in the console) I get a fresh level with all the monsters alive.
Even if I just saved at the end of the first level or the beginning of the second.

**Comment by Sovero4ek** [comment]
I will upload video of my problem.

**Comment by DanielGibson** [comment]
That would be very helpful, thanks!

**Comment by Sovero4ek** [comment]
https://www.youtube.com/watch?v=8dQJuum-Q0Y&feature=youtu.be My video

**Comment by Sovero4ek** [comment]
Hi, I reinstalled a game and a patch several times. I started a game from the folder yquake2.exe. Nothing has changed.
[stdout.txt](https://github.com/yquake2/yquake2/files/2430836/stdout.txt)

stderr.txt is empty

**Comment by maraakate** [comment]
Just out of curiosity... try running yquake2.exe directly.  Do not launch within steam or with the steam overlay.  I have found in the past some updates of steam with DK 1.3 would cause funny things to happen with corrupting the DLLs with the way it tries to hook into things, especially when the overlay is enabled.

**Comment by Yamagi** [comment]
Than you for the log. I've finally found the problem: When a new game is started the server needs to wipe the current state from the working directory. It just called remove() which is not Unicode compatible on Windows. Since you have some Unicode characters in your Windows user name that operation failed, the state was still there and reused by the new game...

A new set of Windows binaries with the fix can be found here: https://deponie.yamagi.org/quake2/misc/quake2-012ab85.zip

Thank you for the report and your help!
