### ISSUE TITLE
Entities on rapidly ascending plats physics bug

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#320]
https://github.com/yquake2/yquake2/blob/d96a46dc1f832c5d4ab94dee871fb27d0ee6a385/src/game/g_monster.c#L265

This line causes entities on rapidly ascending plats (by rapidly i mean plats with speed >= 200) to jump around. Reverting this line to original Id implementation (ent->velocity[2] = 0) fixes this issue.

See the attached map for an example of this behaviour.

[plat_rise_phys_bug.zip](https://github.com/yquake2/yquake2/files/2356158/plat_rise_phys_bug.zip)

**Comment by Yamagi** [comment]
That's an interesting one. I did the change during the great game code audit in 2b4f223566ecd9f654412ca0d2ae73dc7d12db46. And looking at the code I'm still thinking that my change is more correct than the original correct. 

The original code sets an entities z axis speed to 0 if it's standing on another entity. If the lower entity moves down, the upper entity will fall until it touches the lower entity again. That could lead to unwanted damage to the upper entity. More critical is the other way. If the lower entity moves up it'll push the upper entity to a higher position. That could lead to situations were the upper entity gets stuck in the lower entity. Because of entity update code getting called in the wrong order, rounding inaccuracies, timing issues, etc.

WIth my change the upper entity moves with the same speed as the lower entity up and down. What you're seeing looks like a more general problem, maybe another short over- oder underflow somewhere or another floating point problem. That'll require a deeper look.

**Comment by m-x-d** [comment]
I investigated the issue a bit, and it seems to me happening because in this case entity origin is modified twice in SV_Physics_Step:
1. in M_CheckGround, which also sets vertical velocity.
2. in SV_FlyMove, which uses velocity set in M_CheckGround to modify entity origin again.

**Comment by Yamagi** [comment]
If commited the first fix that you suggested. Thank you! :)
