### ISSUE TITLE
Software mode static gun fov.

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#334]
Find one issue. In software mode gun position is static and not depend of screen resolution, so if you play in 1980x1020 gun position is fine, but in 640x480 it is very high. It is only software mode issue, in both of gl modes gun fov is fine.

**Comment by Yamagi** [comment]
I just had a look at this and don't think that this can be fixed completely without too much hassle:

In the GL renderers we're telling OpenGL to render the gun with the given r_gunfov and a static Z offset of 4 units. In the soft renderer that's not possible because the fov is part of the global state and cannot be set for a single model. Therefor we're just calculating a scaling factor relative to the overall fov and pass that down the render path. That's a hack and there're 2 problems:

The code that calculates the the scaling factor is wrong, it takes a hardcoded aspect ratio of 4/3 into account. That's unnecessary for a 4:3 aspect and distorts the gun for all other aspects. Fixing only that is easy, the fix can be found here: https://github.com/yquake2/yquake2/commit/1755980af82cf06b81aadaa47654208c1d61f9ed

But that's not enough. With the correct scaling factor the gun is rendered with the correct perspective, regardless of the resolution and / or aspect ratio, however its Z offset is still "wrong". In a aesthetic sense. The gun appears too near to the 'camera', looking ugly. And with the existing scaling factors alone that cannot be fixed. It may be possible to hack some kind if Z scaling into the renderer path if someone understands all that undocumented math and is brave enough... If someone wants to try: Have a look at sw_alias.c, especially at `R_AliasProjectAndClipTestFinalVert()` (applys the scaling factors) and `R_AliasPreparePoints()` (does magic with vertexes).

**Comment by Yamagi** [comment]
I've merged my fix, it'll be part of the next release. Thank you!
