### ISSUE TITLE
Wrong keyboard layout bindings

### ISSUE THREAD

**Issue by hfc2x** [yquake2/yquake2#339]
The game doesn't treat keyboard inputs as raw key inputs, but rather as a specific character bound to that key in-game.

For example, the "\`" key is bound to open the console, but my system has an International Spanish keyboard distribution, therefore the "º" key (which is beside 1 in the keyboard) will not open the console in-game. This is not the case with most other games which happen to use a console, because most games will treat keys as raw inputs, and therefore don't mind if the key I'm pressing doesn't really match what they expect, so in these cases, they _do_ open the console if I press the key beside 1, regardless of system keyboard distribution. This includes both Quake 1 and vanilla Quake 2.

For me opening the console in-game is troublesome, because I either have to open it from the options menu, or press the "\`" key repeteadly (which is in a whole different area of the keyboard) for it to open, since in Spanish, "\`" is a tilde character and cannot be typed by itself. My other solution is changing keyboard distribution before launching the game, but this is for obvious reasons, not ideal. Vanilla Quake 2 instead treats my keyboard layout as English regardless of system settings, which causes key inputs to be accurate.

**Comment by DanielGibson** [comment]
You can open the console with Ctrl+Esc and YQ2 should not treat your keyboard as English, but use (and show) the appropriate keynames in keybindings menu etc.

Opening the console with the key left to 1 sucks for lots of reasons: With German layout you'll always and up with a `^` in the console, in Brazilian layout that key is used for `"` so you couldn't write a quote in the console without closing it, ..

**Comment by hfc2x** [comment]
Ctrl + Esc opens the Start Menu in Windows 10, so that's a really bad combination. Besides, some players may bind Ctrl to some other action in-game (bound to attack by default, for example), and that action presedes the opening of the console regardless, which in my opinion is worse than a single character appearing in the console when it's brought up.

Besides, the keys don't show in my language in the keybindings menu in any case. They show up in English, so the program is just detecting my keys in the wrong places.  Even binding from the console is inaccurate, because the console expects a character and not a key. I'm not saying that the game should expect they keyboard in English, but detecting the keys being pressed rather than the character is a better option, since in my case, I cannot even unbind "\`", because it's hard-coded.

**Comment by Yamagi** [comment]
Ist Shift + Esc **not* Ctrl + Esc :) Son't know why @DanielGibson wrote Crtl + Esc.

For the general case: Quake II is one of those old games with no understanding of keyboard layouts, locales and character encodings. And it's not possible to teach Quake II these things since they would require invasive changes up to the lowest level like the client <-> game ABI (changing that would break mods) or the configuration file. So, either way we take, we do it wrong.

* If we stick to raw key codes that's nice for all users with keyboard layouts similar enough to the standard us-qwerty keyboard. But it's a real pain for everyone else, and there are a lot of strange layouts out there. Not only in asia or africa, but some european layouts too.
* If we use intepreted key codes some keys that were bindable before might get lost. For example in the raw case the german `ü` key is bindable since it's raw code correspondents to `]` on the us-qwerty layout. With interpreted key codes it's not since the console doesn't accept the character `ü`.

We went for the second options since interpreted key codes have only small disadvantages for some users, but on the other hand they're a great advantage for a much bigger group of users with strange keyboard layouts. In fact switching to interpreted key codes was one the most requested features in the first years of YQ2.

So: Shift + Esc should open the console on all keyboard layouts. ^, ~ or whatever character is left to the 1 is just supported for historical reasons. Also Alt + Return should switch to fullscreen on all layouts.

**Comment by DanielGibson** [comment]
Oh sorry, that was a brainfart, should've been Shift+Esc of course.
(ioq3 and dhewm3 use that key combination as well, by the way)

**Comment by hfc2x** [comment]
But what about making the console key unbindable? (Or re-bindable for that matter) Since the console can be opened from the menu in any case, so it's not like users will not be able to open it anymore if they unbind the key.
