### ISSUE TITLE
vkQuake2 Vulkan render support?

### ISSUE THREAD

**Issue by shoober420** [yquake2/yquake2#373]
I just came across this vulkan source port of Quake 2.

https://github.com/kondrak/vkQuake2

Is there a way that the Vulkan render from this port can be used with Yamagi?

**Comment by kondrak** [comment]
I'm not really familiar with Yamagi port but I'll try to add my 2 cents here. :)
According to one of the devs on Twitter, it should be "fairly easy" to add the new renderer - there are some differences in the initialization process but overall, the entire backend would likely remain untouched. The "Vulkan part" of vkQuake2 is agnostic enough so it can be pulled out rather easily with some minor changes (I introduced some dependencies on the internal Quake 2 types but nothing really critical). 
With that said - there's really no added value introduced by Vulkan rendered in this case, other than being able to say that Yamagi supports Vulkan now - performance gains will be insignificant in comparison.

Once I clean up all the rough edges in vkQuake2, I might be considering helping out on this one since Yamagi seems to be one of the best Quake 2 source ports out there. Can't really give any specific timeline for this though, with it being just a side-project and all.

**Comment by Yamagi** [comment]
Some years ago when we've added the GL3 renderer we've designed a completely new renderer API. That renderer API is much cleaner than the original one and should be - now that we've gone through 2 or 3 iterations of improvements - fairly stable. So it shouldn't be a be a big problem to support "inofficial" renderers. 

The client side entry point is here: https://github.com/yquake2/yquake2/blob/master/src/client/vid/vid.c#L332

That said, I'm always happy merging new features. :) But only if there's someone volunteering as a maintainer, at least until the feature as working as expected and doesn't have too many bugs. A good example is the softrenderer which was contributed by @0lvin. He did the initial work, solved many bugs and problems and is now getting to the point that the code is some kind of maintenance mode where it's just working.

That said,

**Comment by DanielGibson** [comment]
Thanks for chiming in, Krzysztof! :-)

The DLL interface (structs passed between client and renderer) is at https://github.com/yquake2/yquake2/blob/master/src/client/vid/header/ref.h#L124

> He did the initial work, solved many bugs and problems and is now getting to the point that the code is some kind of maintenance mode where it's just working.

But still occasionally bugs turn up and *he* fixes them. If he stopped doing that and there would still be too many issues we'd probably remove the soft renderer again, as we don't want to spend much time on maintaining it ourselves.

And would have to be the same with a Vulkan renderer: Neither Yamagi nor me are familiar with Vulkan, so we *couldn't* even maintain it ourselves (and I have no idea if/when we get around to learning Vulkan ourselves, we're both busy with our jobs and other YQ2 and dhewm3 maintenance duties). If problems turn up (and there are always problems turning up, even if it's just driver bugs that need to be identified and maybe be worked around), someone else would have to fix them.
Once a Vulkan backend is stable, maintaining it will probably not be *a lot of work*, but it would be at least *some work, occasionally* and thus require a practically indefinite commitment (or until Vulkan is not relevant any more and replaced by something even newer, or someone else steps up maintaining it).
