### ISSUE TITLE
Black debris on sloped surfaces.

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#407]
In some cases debris/gib models are rendered black on sloped surfaces regardless of surface brightness. This bug is not specific to YQ2 and happens in all YQ2 renderers.

In my KMQ2 branch I've [fixed](https://github.com/m-x-d/KMQuake2/commit/319c78235340450e51d5ee58b6dc79dae74b2e2e) that by adding a small offset from target surface in SV_PushEntity(), but I'm not sure that's the proper way to fix this.

![q2_0000](https://user-images.githubusercontent.com/7252064/58917479-fe82c200-8726-11e9-98f2-9bdbdc489339.jpg)
[debris_test.bsp.zip](https://github.com/yquake2/yquake2/files/3254672/debris_test.bsp.zip)

**Comment by DanielGibson** [comment]
Thanks for pointing out! :)

I *guess* the workaround makes sense (would be the first thing that comes to my mind as well)..
But I wonder what exactly goes wrong there (where/how the brightness is applied and why it's wrong) and if it's sufficient to only add the offset when calculating the brightness instead of moving the whole entity. If this is not possibly (or unreasonably hard) your workaround should be good enough though, I doubt it makes a visible difference if they're moved one unit above the surface (assuming the normal is indeed normalized and 1unit long)

**Comment by m-x-d** [comment]
My guess is that model origin ends up slightly below the surface plane (float math imprecisions in SV_Trace()?), so RecursiveLightPoint() can't find a surface to grab brightness from.

**Comment by DanielGibson** [comment]
Hmm sounds plausible - and if we add an offset in RecursiveLightPoint() that might break other cases where something is supposed to be behind a face.. so your solution of lifting up the entity a bit (and only for non-horizontal planes) is probably safer :)

**Comment by m-x-d** [comment]
Knightmare fixed ([#1](https://bitbucket.org/Knightmare66/kmquake2_stable/commits/0eac80b08ae6386d3ce2daac8ae8fe2eb1eedb69) [#2](https://bitbucket.org/Knightmare66/kmquake2_stable/commits/8e5184bfb38032723e55a3bb20408f731d71b620)) this issue by setting gib/debris model mins/maxs.
