### ISSUE TITLE
Reshade and Quake II compatibility problems

### ISSUE THREAD

**Issue by Screamerofstars** [yquake2/yquake2#410]
i don't know if you may call this an issue, i'll even enter in contact with crosire at reshade forums about this issue later.

but the latest updates for both Yquake2 and Reshade broke the mouse interaction with both, Rehsade used to work with YQ2 in the past, but the latest update broke mouse support and the cursor is stuck at the center if you open the reshade editor.

i tested it with other ports and it works well, but only YQ2 has this issue.

**Comment by Yamagi** [comment]
We had several reports of problem between Reshade and YQ2 over the years; input problem, render grlitches, etc. I think this is due to SDL 2.0, while most (all?) other ports are still using SDL 1.2 or even the old Windows native backend. We haven't changed anything in the mouse input over the last year, if the problem is new it may be due to an updates SDL.dll. We're shipping version 2.0.9 since YQ2 7.40 earlier this year. You could try an older version, SDL 2.0.8 or 2.0.7.

**Comment by Yamagi** [comment]
P.S.: At least in theory all SDL 2.0 versions should work.
