### ISSUE TITLE
Camera interpolation issue after loading game. 

### ISSUE THREAD

**Issue by m-x-d** [yquake2/yquake2#411]
Here's an issue with player view interpolation after loading a save when a player is within 32 map units from 0, 0, 0 coords.

How to reproduce: load a map, where player start spot is at 0, 0, 0 (the map from my [other issue](https://github.com/yquake2/yquake2/issues/407) will do). Without moving, save game, then load it (reloading the map using "map debris_test" ccmd produces the same result).

Here's what I think is happening:
1. When loading the game, cl.predicted_origins are set to 0, 0, 0 in CL_ClearState().
2. cl.frame.playerstate.pmove.origin (which is [0, 0, 22-ish] in this case) is compared to 
cl.predicted_origins[frame] (which is [0, 0, 0]) in CL_CheckPredictionError(), the length of resulting delta is less than 640, so the view gets incorrectly interpolated.

This can be fixed by setting at least one coordinate of all cl.predicted_origins to a value outside of supported playable area (for example, to 8192 * 2) in CL_ClearState().

**Comment by Yamagi** [comment]
The analysis is correct, there's a high chance of the view being misspredicted after savegame load due to the VectorCopy() in cl_prediction.c:69 being executed when it shouldn't. The fix however is at least somewhat problematically, it introduce an artificial prediction reset, leading to one frame (the first one after the load?) being rendered from a totally wrong position or view origin. It can be seen as a short flickering. However, I don't have better idea. It may be possible to introduce some kind of 'client state was reset' flag and don't take cl.prediction_error into account for the first frame, but that has a high chance to introduce other problems... Maybe just leave things as they are? It isn't a huge problem after all, just a minor inconvenience.

**Comment by Yamagi** [comment]
@DanielGibson and I agree that a fix is too complicated and offers too little gain by a high risk of breaking things. So we won't fix this one. If anyone has a good idea for a non-invasive fix feel free to reopen the issue.
