### ISSUE TITLE
Loaded save games are not starting at the saved point

### ISSUE THREAD

**Issue by 77Mynameislol77** [yquake2/yquake2#417]
I just noticed this while playing, i saved a game, loaded it and when it finished loading i was dead.

**Comment by Yamagi** [comment]
That's the good, old "World needs to forward when loading saves" problem. When loading a savegame the game logic needs to process some frames to spawn all entities in, etc. During this frames action happens and the player dies. Since it's possible to load a game in paused state (try `load quick` in the console to load the quicksave) it might be possible to hack the loading code to put the game into pause mode before processing the frames. That's been on my todo list forever...

**Comment by 77Mynameislol77** [comment]
That worked! Yeah, what you suggested would be optimal, put the game in pause mode while it's loading.

**Comment by Yamagi** [comment]
I had a deep look into this and that's a rather complicate problem:

When the player loads a savegame the server reads its part of the save and tells the games to read the remaining parts. During this reading the world is advanced 4 frames. I could work around this by introducing a new variable `loadgod` or so that puts the player into a special god mode. The world would still move, but monsters and the environment can't hurt the player. 

In case that the player enters a level that he or she already visited, the server advances the world by 100 frames after the savegame was loaded. That are about 5 seconds of play time. In practice this isn't a big problem because the starting areas of almost all levels keep the player unreachable for monsters until he moves at least some units forward. During that 5 seconds the server can't be put in pause mode (because pause mode only means that no world frames are processed) and I can't put the player into god mode (because the god mode is in the game and can't be triggered by the server).

The real problem is the client. The server loads the savegame, tell the client to join and begins processing world frames. So the game is already running while the client is still joing, loading the assets and so on. On my machine base2 takes 2373 milliseconds to load, 21 milliseconds are the server and the game. 2352 milliseconds are the client. That are over 40 world frames, more than enough time for monsters or the environment to kill the player. 
 
The easiest way would always be to put the client into pause mode when joining a game. The problem here is that we don't know what game we're joining. If it's a single player game everything would be okay. If it's a deathmatch, a coop game or some mod things break if the client is in pause mode, you can't pause a deathmatch and the like...

Maybe we could send a parameter to the client if it should go into pause mode or not. That's the same kind of hack that we're using to communicate the HTTP download URL from the server to the client. If it would work it leads to another problem. The assets are loaded asynchronously, it's hard to determine when the client is ready. One possibility would be to hijack the loading plaque, as soon as it's turned down the pause mode is left.

I'll need to ponder a little bit more over this. :)

**Comment by Yamagi** [comment]
I just pushed a possible fix. It's completely on client side, it doesn't need any changes to the server and should work with all game dll. Of course I can't be sure that it doesn't break some mods. If `cl_loadpaused` is set to `1` (the default) the client is put into pause mode when connect to a local server that runs a single player game. Pause mode is left as soon as the first regular server frame is received, that's the same time at  that the loading plaque is turned down. If the cvar is set to `2` pause mode is never left, the player needs to do it by hand. If set to `0` pause mode is never entered, that's the Vanilla Quake II behavior.

This works only for local single player server. It doesn't work for coop and deathmatch server, because the client must not enter pause mode in multiplayer games. It's considered cheating, the server would drop the client. And it doesn't work for remote single player games, if anyone is mad enough to do such things.

I'll upload a new set of Windows binaries tonight.

**Comment by Yamagi** [comment]
The binaries can be found here: https://deponie.yamagi.org/quake2/misc/quake2-20190903-b7bb9f2.zip

**Comment by 77Mynameislol77** [comment]
Seems to work just fine on my end

**Comment by Yamagi** [comment]
Thank you for testing. I've merged it to master, it'll be part of the next release.
