### ISSUE TITLE
trying to use yquake2 with dispmax on pi

### ISSUE THREAD

**Issue by HereticOne** [yquake2/yquake2#424]
Wonder if i can put it in software mode so i can use a spi display on my pizero without needing opengl

**Comment by HereticOne** [comment]
The problem is FBCP cannot grab frames from the pi running the openGL gpu driver.

**Comment by Yamagi** [comment]
YQ2 was never really useable on my RPi 3. The crappy GPU and its even more crappy driver are too slow for the gl1 renderer, even 1024x768 is unacceptable slow. The gl3 renderer doesn't work because the GPU has no OpenGL 3 support. While it has OpenGL ES 2.0 support, we don't have a renderer for that. And the CPU isn't strong enough the run the softrenderer.

I can't comment on FBCP, I have no experience with it. A lot of other tools, Reshade being the mot prominent example, always had problem to interact with YQ2 due to the way how SDL creates and manages the OpenGL context. Maybe someone over at SDL can help.

**Comment by HereticOne** [comment]
Unfortunate.
As i am unable to find a way to grab the frame buffer from gl.

**Comment by Pickle** [comment]
@HereticOne,
I had a fork branch for opengles 1.0 that i ran on rpi original. 2.0 ES is
not likely to make any difference in speed.
https://www.raspberrypi.org/forums/viewtopic.php?p=1399964
