### ISSUE TITLE
HTTP download bug

### ISSUE THREAD

**Issue by SiemensSchuckert** [yquake2/yquake2#429]
**Example 1:**

_Server missing files:_
/baseq2/players/male/cipher.pcx
/baseq2/players/male/cipher_i.pcx

_Player2 missing files:_
/baseq2/players/male/cipher.pcx
/baseq2/players/male/cipher_i.pcx

Player1 selected skin "cipher" and entered game on Server

Player2 can connect to Server, but will never enter game - trying to download files in an endless loop.

**Example 2:**

_Server missing files:_
/baseq2/players/male/cipher.pcx
/baseq2/players/male/cipher_i.pcx

_Player2 missing file:_
/baseq2/players/male/cipher.pcx

Player1 selected skin "cipher" and entered game on Server

Player2 can enter the game, with just two HTTP and UDP download errors (as intended)

_console output:_
HTTP download: /baseq2.filelist - Queued
HTTP download: players/male/cipher.pcx - Queued
HTTP download: players/male/cipher.pcx - File Not Found
HTTP download: /baseq2.filelist - File Not Found
Downloading players/male/cipher.pcx
Server does not have this file.
Player2 entered the game

**Comment by Yamagi** [comment]
This may be related to the *baseq2/* special case. I'll look into it, it might take a few days.

**Comment by Yamagi** [comment]
This was an interesting one, an error in the r1q2 -> q2pro -> UDP fallback logics special case for servers that are missing one or more files. In such cases we would start over at r1q2. That works as long as we are able to get all files. But in some cases were at least one file cannot be downloaded we run into an endless loop.

I've worked around this by starting over just once. As long as a server is missing only file we get this file over UDP and all other over HTTP. But if it's missing more than one we're falling back to UDP for everything. Since this is a corner case this behavior should be okay.

So: You'll see the missing skins being requested twice, after that the client gives up and proceeds with joining the match.
