### ISSUE TITLE
Damage/Weapon pickup screen flash is too much. How to tone down?

### ISSUE THREAD

**Issue by object404** [yquake2/yquake2#434]
The screen flash during player damage and weapon pickup is too much and I become blinded and can't see anything onscreen when I pick up weapons or get damaged.

How do I town down its opacity so that objects onscreen are still visible during weapon pickup or damage screen flash? I can't find anything in the docs.

**Comment by Yamagi** [comment]
Hmm... If I remember correctly we didn't change the blending style. It should be the same as in Vanilla Quake 2, but may appear brighter because of the different renderstyle of the GL3 renderer and bigger screens. Currently there's no way to tone it down, it can be only switched of by setting `cl_blend 0`. It might be possible to implement something. I'll look into it, it may take some time.

**Comment by object404** [comment]
After installing a whole bunch of map, env, texture, etc packs from http://tastyspleen.net , it went away and I can now see stuff through damage and weapon pickup flashes.

But a vanilla install of Quake 2 via Steam + Yamagi + the model/texture pack recommended on the Yamagi site has the problem.

**Comment by Yamagi** [comment]
I think that this caused by the way how the screen flashes are applied to the scene. And I dond't think that there's much we can do about it. But maybe we should compile a new retexturing pack based upon the stuff found on Tastyspleen.
