### ISSUE TITLE
Add FLAC Support for Their Respective Games' Soundtracks

### ISSUE THREAD

**Issue by MasterO2** [yquake2/yquake2#445]
I am requesting FLAC support for the in-game soundtracks for Quake 2 and its two expansion packs.  

I say this because many other sourceports for open-sourced 90s FPSes have had this for many years:

Quakespasm has it for Quake and its expansion packs.
DXX-Rebirth has it for Descent 1 and 2.
Chocolate Hexen has it for Hexen and its lone expansion pack.

**Comment by ptrb78** [comment]
I am supporting MasterO2 position:)

**Comment by DanielGibson** [comment]
See #418 (we have no interest in this, you can't tell the difference between high quality OGG/Vorbis and FLAC anyway, unless maybe if you're a cat in which case please provide us a video of you playing Quake2 because we'd love to see a cat playing it)

**Comment by Marat-Tanalin** [comment]
Daniel, if it’s not clear, I added comments to the issue #418 _not_ to force anything, but just to provide _additional information_ that _could_ potentially be useful for yQuake2 developers **if** they eventually decided to implement support for lossless audio (if not, _no action required or implied_). Such additional information naturally includes examples of open-source projects that corresponding code could potentially be _borrowed from_. This does _not_ mean those projects are better than yQuake2.

Disable commenting for such issues just makes it impossible to provide additional useful info in future, though Yamagi themselves did show interest in a ready-to-use implementation e.g. in the form of a single-file Wave (*.wav) decoder.

**Comment by Marat-Tanalin** [comment]
ScummVM is another open-source project (GPL) that [FLAC](https://github.com/scummvm/scummvm/blob/master/audio/decoders/flac.cpp) support could potentially be borrowed from. (Fwiw, ScummVM itself has nothing to do with Quake series.)

**Comment by Yamagi** [comment]
What have Quakespam or ScummVM to do with YQ2? We have our own music backend, written by @DanielGibson and me. No code out there, be it from another Quake series source port, from ScummVM or any other game can be ported. It's just not compatible with YQ2. And I said before, neither Daniel nor I have any interest in FLAC. But I **may** be willing to merge a good pull request. So: If you really want it, send a PR. Otherwise shut up.

**Comment by Marat-Tanalin** [comment]
> What have Quakespam or ScummVM to do with YQ2?

They are open-source and have a lossless-audio (FLAC or Wave) decoder that could potentially be reused in Yamagi Quake 2. **Not necessarily** by YQ2 developers themselves, but by a third-party developer who could be willing to do that.

QuakeSpasm is an engine for Quake 1, not Quake 2 (that’s why the Daniel’s “use quakespasm then” [comment](https://github.com/yquake2/yquake2/issues/418#issuecomment-538014156) was as relevant as “Use Surge” or “Use ScummVM” would).

Surge is a virtual musical synthesizer.

ScummVM is an engine for running multiple old games like “Broken Sword”.

> neither Daniel nor I have any interest in FLAC.

No problem. My intent was just to provide additional, potentially useful info so that there are more options which is usually better than fewer options. You don’t have to be rude.

Doesn’t GitHub provide an option to disable email notifications about comments to _closed_ issues? Otherwise I have no idea how such informative comments to such closed issues could disturb you in any way. Would it be better to collect such information somewhere else?

> If you really want it, send a PR.

Unfortunately, I have some experience in C++, but not C. And yQuake 2 doesn’t even support compiling with Visual Studio. I still consider this option though, thanks.
