### ISSUE TITLE
7.41 and "wrong" difficulty

### ISSUE THREAD

**Issue by voodoo84** [yquake2/yquake2#446]
Hi,

I've started a clean new game (main campaign, not expansions) on Easy yesterday (with Steam version of the game). The mission objective screen (F1) also says Easy skill all the time.

However, from the start it fellt a bit off regarding number of spawned enemies (I played the game on Easy and Normal numerous times). For example, directly on the first level when you proceed crouching into the crack to the secret area which contains the shotgun, at on point a guard will wait for you behind the corner on Normal, but he shouldn't be spawned at all on Easy, which made me thing this may not be Easy skill at all.

Then after advancing to the warehouse and jail, it became obvious it's not, due to increased number of gunners and berserkers chasing me around.

Can you please check the difficulty selection code and if there are any regressions compared to 7.40 and previous?

**Comment by Yamagi** [comment]
That's strange. At level load all monsters and items are processed. If an monster or item has a skill setting higher than the requested skill it isn't spawned in. We've never touched that code... But there were some changes in the hub systems code (the code that transitions the player between levels)  between 7.40 and 7.41  to fix several bugs with level transitions and savegames in coop mode. Maybe the skill setting is lost somewhere.

Can you check what the `skill` cvar is set to? It should be `0` for easy, `1` for normal, `2` for hard and `3` for hard+ / nightmare.

**Comment by voodoo84** [comment]
I've checked, skill is set to 0.

I don't "feel" that the enemies are any smarter or dealing more damage, just that there are more of them.

**Comment by Yamagi** [comment]
Okay, I can reproduce this. 7.40 didn't spawn the optional guard in base1. The current git head does. I'll need to figure out what broke it. Since this is gonna be a busy week it may take some days.

**Comment by BjossiAlfreds** [comment]
I looked at the entity string in base1.bsp, and I can not find any monster there with only SPAWNFLAG_NOT_EASY set. There are 2 infantry guys with spawnflags 769 (not easy + not medium + deaf), and they are pruned correctly based on skill in YQ2 7.41.

There are 2 triggered spawns in base1, a light guard and shotgun guard. Both of them have spawnflags 2 which means they spawn on all difficulties. Their targetname is t55 which links to the shotgun which has spawnflags 0 (spawns on all difficulties). So these guys always spawn and are accessible in the level.

I also tested jail2. On easy mode only 1 gunner and 1 infantry spawn in the starting area but 2 of each on medium and above. This is consistent with the entity string in jail2.bsp and I get the same results in vanilla Q2 with original 1998 dll and YQ2 7.41 + game.dll.

So unless for some reason I have different bsp files than the Steam version, it seems that YQ2 7.41 + game.dll is working correctly as far as my testing goes.

**Comment by Yamagi** [comment]
I think that you're right. When I tested this at Monday morning the guard behind the boxes (near the stairs) in base1 didn't spawn for some reason. Maybe I didn't walk over the trigger or something like that. So I thought that I managed to reproduce it. But when I started to find a way that's reliable enough for a `git bisect` it didn't happen again... There're are some cases left that I want / need to check: Saving and loading games, transitions between levels and returning to already visited levels. It's unlikely that we've broken something but it's Quake II and you never know.

**Comment by BjossiAlfreds** [comment]
That guard not spawning is indeed a weird one. If you pick up the shotgun, you 'should' be guaranteed to spawn both guards, including the combat point one behind the boxes, since the shotgun's target is t55 (the targetname of both guys). If this happens seemingly randomly, it could be caused by undefined behaviour somewhere, or the level time, either way would be an annoying bug to find.

**Comment by voodoo84** [comment]
No problem men, it was just weird that, at several points in warehouse and jail, I had two berserkers spawning and chasing me at places where I recall it never happened in ~18 years of playing.
Fortunately, the game is not hard so it's not a really big deal, but if you do a code review at some point, just to know what also to look :)

**Comment by Yamagi** [comment]
I did some more thorough testing. Level changes, savegame loads, and  I counted monsters by hand. So far I'm unable to see any differences between 7.30 and the current git HEAD. Since this is Quake II with its crappy code it **doesn't** that there isn't a problem. It may depend on something in your configs, we might have introduced a savegame compatibility problem somewhere, etc. 

A new Windows build of the git HEAD as of now can be found here: http://deponie.yamagi.org/quake2/misc/quake2-20190914-cf742c0.zip

If you want to continue with testing (asuming Windows):
* Make sure that everything (quake.exe, all ref_*.dll and the game.dll) are up to date.
* Rename `c:\users\username\documents\yamagiq2` to something else so that you can start over with a clean config.
* Do not use an old savegame.

If it still occurs things get interesting. ;)

**Comment by BjossiAlfreds** [comment]
Also, if you can run it, try use the original engine and gamex86.dll to compare. If you find a case where YQ2 and original binaries disagree under the same difficulty level, then indeed there is something interesting going on.
