### ISSUE TITLE
q2ded Crashing after map timer expires

### ISSUE THREAD

**Issue by sl1ngblad3** [yquake2/yquake2#457]
For the q2ded Yamagi v7.41 server on Linux (Ubuntu/Fedora) the server will crash after the first map with the error "couldn't load maps/.bsp". All the files are in the right place and I can load maps just fine with the config file or from shell. After the map timer expires you can use rcon to change map and the server will not crash, but if you let it go to the next map on it's own it crashes. I have built from source on both Ubuntu 19.04 and Fedora 30 and both exhibit the same behavior. I can run the v7.41 Windows binary on Server 2019 with the same .cfg files from the Linux boxes and the server loads the next map just fine. Any ideas?

**Comment by sl1ngblad3** [comment]
Probably should add this is when running in DM mode. Had the server running in COOP mode for a while and didn't experience any issue progressing through the game.

**Comment by Yamagi** [comment]
Hmm... That may be another bug ins this stupid map list crap. We'll look into it, but it may take a few days.

**Comment by Yamagi** [comment]
I'm starting my server with `./q2ded +set deathmatch 1 +set timelimit 1 +set sv_maplist q1dm2 q2dm2 q2dm3 +map q2dm1` and it cycles through the maps as it should. If I give the options as server.cfg, they behave exactly the same:
```
deathmatch 1
timelimit 1
sv_maplist q2dm1 q2dm2 q2dm3
map q2dm1
```

Can you give some more background how to reproduce the problem?

**Comment by sl1ngblad3** [comment]
Running it with the commands you provide above the below is the result after the timer expires. I was attempting to run it using a maps list file, but get the same result running it as you posted above.

![Screenshot from 2019-09-28 11-16-11](https://user-images.githubusercontent.com/16858875/65818702-0e487980-e1e2-11e9-9eb8-8d139232be26.png)

`[quake2ded@virtual2 quake2]$ ./q2ded +set deathmatch 1 +set timelimit 1 +set sv_maplist q1dm2 q2dm2 q2dm3 +map q2dm1

Yamagi Quake II v7.41
=====================
Platform: Linux
Architecture: x86_64
Byte ordering: little endian

Added packfile './baseq2/pak0.pak' (3307 files).
Added packfile './baseq2/pak1.pak' (279 files).
Added packfile './baseq2/pak2.pak' (2 files).
Added packfile '/home/quake2ded/quake2//baseq2/pak0.pak' (3307 files).
Added packfile '/home/quake2ded/quake2//baseq2/pak1.pak' (279 files).
Added packfile '/home/quake2ded/quake2//baseq2/pak2.pak' (2 files).
Using '/home/quake2ded/.yq2//baseq2' for writing.
execing default.cfg
couldn't exec yq2.cfg
execing config.cfg
couldn't exec autoexec.cfg
==== Yamagi Quake II Initialized ====

*************************************

-------- game initialization -------
LoadLibrary("game.so")
Game is starting up.
Game is baseq2 built on Sep 16 2019.
------------------------------------

------- server initialization ------
0 entities inhibited.
0 teams with 0 entities.
------------------------------------

SL1N9BL4D3 connected
SL1N9BL4D3 entered the game
Timelimit hit.
------- server initialization ------
********************
ERROR: Couldn't load maps/.bsp
********************
==== ShutdownGame ====`

**Comment by sl1ngblad3** [comment]
After I corrected the map typo from above "q1dm2" it works correctly. I was trying to call the maps from a maps list file. That seems to work on Windows and even works with no maps list, it will restart the map. On Linux it just crashes. Calling the maps for the command line or from the config as you describe above does work.

**Comment by Yamagi** [comment]
Okay:

1. `./q2ded +set deathmatch 1 +set timelimit 1 +set sv_maplist q2dm1 typotypo base1 +map q2dm1` sets `sv_maplist` to `q2dm1`. The other 2 maps are ignored. This might be correct, the command line parser isn't that robust.
2. `./q2ded +set deathmatch 1 +set timelimit 1 +set sv_maplist "q2dm1 typotypo base1" +map q2dm1` Surround the maplist in quotation marks leads to some command line parser errors at startup. The same as above, likely the crapy parser.
3. Setting `set sv_maplist "q2dm1 blubb q2dm3"` crashes the server with "ERROR: Couldn't load maps/blubb.bsp". That is arguable correct, I think it might be better if the server would skip over non existing maps. 

>  I was trying to call the maps from a maps list file.

Can you show us the file?

**Comment by sl1ngblad3** [comment]
Initially I was using this command in the config set mapqueue "maps.lst" with either the game default maps.lst or a custom text file with 1 map name per line. Didn't seem like that worked at all or that the file was ever parsed.

**Comment by sl1ngblad3** [comment]
The only way I can get it to continue and not crash is to include the +set sv_maplist q2dm1 on the command line. I can set that line exactly in the config file, but the parser must not be working because it won't advance. If I set it on the command line it will keep looping the q2dm1 map or whatever map I set it to. At least the server doesn't crash and someone with rcon password can change the map.

**Comment by Yamagi** [comment]
Okay. `mapqueue` won't work, YQ2 hasn't got that command. I think it was an addition by r1q2 and some other source ports took it from there. We may implement it too, because it shouldn't be too hard and it's much more comfortable than the half-broken `sv_maplist` stuff.

`sv_maplist` works for me, but only if I set it through the config with `set sv_maplist "q2dm1 q2dm2 q2dm3"`. Note the quotation marks. It doesn't work without them and not if set through the command line. This is at least counterintuitive. We need to decide if want to keep it as it is (for compatibility reasons), alter the behavior or just rip it out and go with `mapqueue`.

**Comment by sl1ngblad3** [comment]
I found the same to be true. Adding sv_maplist with the set command and map names in quotations works.

**Comment by Yamagi** [comment]
After a lot of pondering and going through  the options we've decided that the best way is to leave things as they are:

* The `set` command accepts exactly two arguments, a cvar and it's value. If the value contains whitespaces, it must be enclosed in quotation marks. When giving the value through the command line, the quotation marks are removed by the shell and the cmd parser breaks. It's not possible to solve this in the code, so the user needs to enclose the string in ticks. Like this: `+set sv_maplist '"q2dm1 q2dm2"'` I've added it to the documentation.
* Skipping over nonexisting maps is hard to implement, because a missing map kills the server and it's nearly impossible to recover from that. So there's nothing we ca do there. I've added a hint to the documentation.
