### ISSUE TITLE
[Suggestion] Increase available cross-level trigger bits from 8 to 27

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#477]
A while ago I noticed that game.serverflags are not used for anything but cross-level triggers, and only the first 8 bits of the entity spawnflags are being used + 5 spawn condition bits. That leaves 19 bits being available but unusable.

There is a fairly simple code tweak one can do to unlock the remaining bits, without changing any data structures and thus maintaining full savegame compatibility. It's pretty much only a matter of changing the cross-level trigger bit mask's value from 255 to ~0 (0 because the condition bits get cleared by SpawnEntities).

This would obviously only aid custom maps and custom ent files but might be handy to have available for the future. Is this something you would be interested in?

**Comment by Yamagi** [comment]
I don't think that wasting the unused bit for crosslevel triggers is sensible. Because only custom maps that are build for YQ2 (and other source ports that implement more crosslevel triggers) could use it and we may need those bits in the future to hack bugfixes or something like that in a savegame and / or internal API compatible way into the code.

**Comment by BjossiAlfreds** [comment]
On the subject of savegame compatibility, there is a simple way to add support for increasing data structure size without needing to update the savegame format, given that you are willing to update the savegame format once to make that change and enforcing strict rule on appending new fields only at the end of the data structure (similar to edict_t and gclient_t). Simply write the byte size of the struct before the struct data itself. That gives you enough information to read the struct correctly from the file and initialize new fields. This could in theory work for any data structure, including game locals, level locals, edict_t, etc.

**Comment by Yamagi** [comment]
Yeah, a field with a version number, the length or something like that. Or the good old dummy fields and FreeBSD and most other Unixes used before symbol version was invented.

Nevertheless, I don't think that it's sensible to waste fields for a feature that will likely never be used, because we're the only or at least one of very few clients supporting it.
