### ISSUE TITLE
no audio with fullscreen resolutions not matching desktop resolution on win10

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#483]
there is an issue with yquake2 when playing on windows 10 with current Intel drivers and audio device is Intel Display Audio ( Audio over HDMI , DP )
This 'bug' is only exposed if game's fullscreen resolution does not match desktop's resolution.
Reason for this is that Intel drivers are disabling Display Audio device during a modeset for a few seconds.  Take a look at this [Intel advisory](https://www.intel.com/content/www/us/en/support/articles/000035049/mini-pcs/intel-nuc-kits.html) for details.

This can be amended manually by restarting sound subsystem in console with snd_restart command. It would be better, if yquake2 could do this automatically, Code should check for errors from audio device and restart when needed.

GOG's version does not have this issue,  Audio is restored automatically after a few seconds.  Client is nightmare's unofficial 3.24 patch

**Comment by j4reporting** [comment]
did some more tests:

firstly I was wrong about GOG's version, sometimes audio device is lost as well at startup.  But once game has started it's possible to switch between different fullscreen resolutions without losing audio device. 

this lead to some more tests with yamagi q2:
with **s_openal = 1**   audio device was lost  every time  the fullscreen resolution changed.
snd_restart  needed to get audio back. Audio device is never aquired at startup.

s_openal 0    // SDL_audio  
starting yquake2  with a fullscreen resolution set to 1920x1080  (desktop resolution 2560x1440 )  works,  and  ingame fullscreen resolution changes never loses audio device.

**Comment by Yamagi** [comment]
I had a deeper look into this and I don't see a way to fix this in YQ2. The basic problem is, that Intels GPU driver destroys the DisplayPort and / or HDMI audio devices when the resolution is switches. That detaches openal-soft from the audio device and the only way to recover is to reinitialize openal-soft. `snd_restart` does that by unloading and reloading openal-softs DLL.

Of course we could inject a `snd_restart` after `vid_restart`. But that can't work because the audio devices reappears at an unknown later time. On my Skylake desktop it's somewhere between  2 and 850 milliseconds. Additionally we have no way to ensure that openal-soft really bound to the correct device. If Intels audio device isn't up and running openal-soft chooses the whatever device is Windows default device at that time.

So: This is a problem with Intels crappy GPU driver and needs to be fixed there.

**Comment by j4reporting** [comment]
I understand that the recently released openal-soft library v1.20 does have some code in place to recover a previously disconnected audio device.

quoting from  http://openal.org/pipermail/openal/2019-October/000738.html

> Additionally, the alcResetDeviceSOFT function (from the ALC_SOFT_HRTF 
and ALC_SOFT_output_limiter extensions) can now attempt to recover a 
device that became disconnected (as reported by the ALC_EXT_DISCONNECT 
extension; sources that were forced to stop on disconnect will remain 
stopped, though). So if a USB device gets unplugged, or an HDMI video 
mode change causes the audio output to drop, you can hold on to the 
ALCdevice for a little bit and try to reset it to see if it comes back 
if you prefer, keeping your contexts, buffers, sources, etc.


I underastand this is going to need some additiobal code in yq2. But I have no idea how much work this would need. A simple drop-in of current openal-soft.dll  won't resolve this issue.

**Comment by Yamagi** [comment]
Hi,
I've coded a work around for this problem. I'm checking every frame if OpenAL is still connect to it's output device. If not the code waits for 2.5 seconds and injects a 'snd_restart' into the command buffer. I can't test the work around, because I don't have a DisplayPort setup for my Windows box. A build with the fix can be found here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200111-778eb0e.zip Can you give it a try?

**Comment by j4reporting** [comment]
Hi,

no, this did not work. It looks like it's never been triggered. 
soundinfo  shows the usual output, reports audio device  Intel display audio (default) 
Tried with openal 1.19.1  and 1.20.0.
Could you maybe add some debug info to soundinfo, or is there another debug output I can enable?

btw.  with s_openal = 0  sound is been restored during the first few frames of the ID logo animation.

**Comment by j4reporting** [comment]
here is  openal-soft   debug output  enabled with 
set ALSOFT_LOGLEVEL=3 
set ALSOFT_LOGILE=openal-log.txt

openal_log.txt    / game resolution !=  desktop 
openal_log_normal.txt  / game resolution ==  desktop resolution

[openal-log.txt](https://github.com/yquake2/yquake2/files/4050852/openal-log.txt)
[openal-log_normal.txt](https://github.com/yquake2/yquake2/files/4050853/openal-log_normal.txt)

**Comment by Yamagi** [comment]
Hi,
thank you for testing. Here's another test build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200113-0d36a7b.zip It fixes one stupid bug and updates openal-soft to version 1.20.0. The last build still shipped with 1.19.0. It adds a lot of debug output, therefore it will properly run rather slow. Can you test it and send me the stdout.txt from the config dir if it doesn't work?

**Comment by j4reporting** [comment]
Hi Yamagi,

this new build works fine. Sound is been restored after a few seconds, either at startup or during a game after a mode set.

**Comment by Yamagi** [comment]
I've just merged the fixt to master. It'll be part of the next release. I'll build another set of Windows binaries tonight.

**Comment by Yamagi** [comment]
The build is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200115-29d607c.zip It has the fix without the debug messages.
