### ISSUE TITLE
switching between fullscreen and window on win10 have some unexpected results

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#484]
desktop resolution 2560x1440 
configured game fullscreen resolution 1920x1080

yquake2 7.41:
switching to window  with ALT-RETURN or via VIDEO menu  do not create a proper window. Display is stuck in top left corner.  Switching back to fullscreen  via ALT-RETURN    enables  fullscreen mode with **keep resolution**.    Fullscreen with **switch resolution** would be the preferred option.

starting yquake2  in window mode  does create a proper window centered at desktop.

yquake2 7.42pre cf742c0:
same issue when switching from fullscreen to window mode 
switching back to fullscreen with ALT-RETURN  resets video settings to 640x480 window mode! 
It does not switch back to fullscreen at all.

**Comment by Yamagi** [comment]
Unter hat operating system is that? And I need the full console log (can be found in %Documents%/YamagiQ2/stdout.txt under Windows or copied from the terminal Quake II was started in everywhere else) for the cf742c0 case to figure out what's going on.

**Comment by j4reporting** [comment]
windows 10  1903  with Intel Iris Graphics 540

[stdout.txt](https://github.com/yquake2/yquake2/files/3831975/stdout.txt)

**Comment by j4reporting** [comment]
I have no idea why resolutions greater than  display's native resolution are reported.  EDID data looks ok.

**Comment by Yamagi** [comment]
Ah, I see. There's something wrong with the work around for SDL bug #4700 - https://bugzilla.libsdl.org/show_bug.cgi?id=4700 - when switching from fullscreen to windowed mode. It would the best for everyone if SDL would fix it on their side. I'll come up with a fix but it'll take a few days.

**Comment by j4reporting** [comment]
don't let this stop you from releasing 7.42!  :)
I stumbled upon this when I did some tests for issue #483 

While we are at this, Links to documentation need to be updated in README.md  and on yamagi.org/quake2 

s/01_index.md/010_index.md/

**Comment by Yamagi** [comment]
Mkay, the SDL docs "forgot" to mention, that the 'fullscreen window mode' implies the internal flag for 'real fullscreen mode'. So the work around magic for SDL bug #4700 triggered when entering 'fullscreen window mode' (which is the case when pressing alt-return) and messed things up. I think I fixed it.

A new set of Windows binaries can be found here: https://deponie.yamagi.org/quake2/misc/quake2-20191113-fed2e14.zip Can you give it a try and see if it really fixes the problem?

**Comment by j4reporting** [comment]
ok this version does not reset settings to 640x480 like cf742c0.

I guess there is still some logic missing if game resolution is not desktop resolution.
Switching to fullscreen mode  creates fullscreen with desktop resolution and game surface is in bottom left corner of the screen.
Changing from fullscreen to windowed mode creates a window without any window decorations in top left corner. So it's not possible to move window on desktop.

**Comment by j4reporting** [comment]
windowed mode has all window decorations but they are not visible because  window's position is set to -3, -26.

**Comment by Yamagi** [comment]
* Alt-Return sets `vid_fullscreen 1`, that the same as the *keep resolution* option in the menu. Or a *fulscreen window*, like some other games calls it. There's no mode switch, SDL creates a big window covering the whole screen and places Quake II somewhere in it. That works nice as long as Quake II has the same resolution as the desktop, which is often the case. The big advantage is, that it's very reliable, even on Linux with X11 (where mode switches are prone for messing up the desktop) and in multi-monitor setups. The disadvantage is that there's a black border (most often above and to the left) around the actual game, if Quake II runs in lower resultion than the desktop. You can set `vid_fullscreen 2` or choose *switch resolution* in the menu to force the old behavior, Quake II will (at least try to) switch into the selected resolution.

* I've noticed the window position problem, too. It should be possible / would be a good idea to force the window to coordinate (0,0) or . That won't happen before version 7.42 because it's another bigger addition the already overcomplicated window creation logic and as a risk of breaking things.

* I'll update the documentation link to the docs of the latest release. That will solve the broken link and avoid confusion.

**Comment by Yamagi** [comment]
@DanielGibson convinced me to fix around the 'window is positioned outside the screen' problem before the next release. We implemented a small hack that ensures that the window is 24 pixel (the height of the window titlebar in Win 10) below the screens upport edge, giving enough room to grab it with the mouse and move it around.

A new build - hopefully more or less that same as the upcoming 7.42 release - can be found here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20191117-fbf103b-7.42-RC1.zip

**Comment by j4reporting** [comment]
Window is now centered on desktop. That's fine.

vid_fullscreen:   I agree most users will use desktop resolution anyway. But in case someone has configured another game resolution, then vid_fullscreen=1 is quite unusual on Windows.
