### ISSUE TITLE
MOD & LAN Bots?

### ISSUE THREAD

**Issue by inukaze** [yquake2/yquake2#490]
Hi there i just want to know, if the Yagami Quake 2 

1 ) Came with Yagami Quake own version of the "CooP" (MOD) to make the "Single Player Caimpaing" with friends in a LAN Party ?

2 ) include their own version of [Gladiator](http://mrelusive.com/oldprojects/gladiator/download.shtml.htm) / Eraser , bots can be enable by an option on menu, just to the players we can make by the ease way something very similar to Quake 3 Arena, and set very ease the bots and the map rotation for a LAN Party without internet :D

Thanks by any answer.

**Comment by Yamagi** [comment]
Good morning,

1. YQ2 includes the original coop mode. So yes, you can play the single player compaign with the main game (baseq2) and both addons with your friends, either over LAN or internet.

2. We don't include a bot, but YQ2 for Windows is compatible with (nearly) all existing mods for Quake II. You should be able to use Gladiator or Erasor like with the original client or most other source ports. We can't include Gladiator, because only parts of the source were released, the wayfinding routines are still closed source. And since Mr. Elusive dies a few years ago that's very unlikely to change.

Regards,
Yamagi

**Comment by inukaze** [comment]
Hi there, thanks for the fast answer. well 

1. Tomorrow i test how i can do that with GNU/Linux & Windows client of Yagami Quake 2

2 - Well yesterday i test under Windows 7 Professional x64, Eraser mod, dont add bots, Gladiator don't work, when i try to add boot, appears the message like the bots are added but too appears some error saying something like "gladiator.dll is not compatible", and the last i try was "CRBot" this works better add bots, the unique thing was under the MiniLaptop i try. when i press TAB show me a Menu (Very good the menu) the think its need a NumKeypad to work and the characters bindings are not compatible with the key on the keyboard, becuase i need to press [ ] to move on that menu but the minilaptop i use for that with Spanish / Spain Layout dont work on menu that keys.

Well i had new dunno know, its not possible adapt bots from Quake 3 Arena to Quake 2, or from Urban Terror ?
