### ISSUE TITLE
Can't load Vanilla Quake2 save games

### ISSUE THREAD

**Issue by gaschka** [yquake2/yquake2#499]
I have a Quake2 copy from Steam, it's v3.20 and recently jumped in for a new play through. Now I tried to load my save game with Yamagi Quake 2. But this don't succeed. I get the following error:
![Anmerkung 2020-01-06 190902](https://user-images.githubusercontent.com/10585836/71838358-ead27c00-30b8-11ea-986a-45c302efe5d6.jpg)

**Comment by Yamagi** [comment]
Yamagi Quake II can't read the savegames from the original client. This is because of their terrible implementation, the savegames only worked with exactly the version they were created with. Every patch broke the savegames, player had to start from the beginning. And Quake II had many patches...

But Yamagi Quake II has a much improved savegame system. Neber versions can read savegames from older versions, so once you've got a YQ2 save you're (mostly) save that your savegames will never get broken by an update.

**Comment by gaschka** [comment]
Hello Yamagi,
thanks for the clarification. Keep up the good work.
