### ISSUE TITLE
Skiping video after changing resolution.

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#502]
If you change resolution with different aspect ratio before loading any saves and starting game in main menu, then start a new game, intro video will be skiped after few seconds after begining. But maybe it is not very important thing

**Comment by Yamagi** [comment]
The video is canceled because at least one key is either left in *down* state or an input event is still somewhere in the queue. I never figured out were things go wrong. Some years ago I've added a `In_FlushQueue()` call to `SCR_PlayCinematic()`. That made things much better but not perfect. I'll have another look.

**Comment by Yamagi** [comment]
Mkay, I think I understand what's going on:

- When changing anythings that require a `vid_restart` through the menu, a `vid_restart` is injected and executed at the next frame after *apply* is invoked with K_ENTER. When `vid_restart` is entered into the console, the last key hit is also K_ENTER.
- When processing the K_ENTER the ugly hack in cl_keyboard.c:1233 triggers and `anykeydown` is incremented.
- The `vid_restart` triggers a renderer restart, that clears the input queue (really?) and the key up event is never received. Therefore `anykeydown` is bigger than 0, even if no key is pressed an in cl_input.c:741 a `BUTTON_ANY` event is put in the current *user cmd*.
- The check in cl_input.c:798 sees that there's a pending button event in the current *user cmd* and aborts the cinematic.
