### ISSUE TITLE
Reckoning background sound looping.

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#506]
In the Reckoning addon at map xship.bsp there is small issue. The one of the background sounds loop not correctly. You can hear this sound at start of the map. Wait until noise is gone and you ccan hear that backgroun sound has pause in looping, but in original it looping without pauses.

**Comment by Yamagi** [comment]
I can hear it. Debuging this going to be interesting...

**Comment by BjossiAlfreds** [comment]
Can reproduce this as well.

The sound in question is called world/amb4.wav (baseq2 pak file) and it is being played by xatrix' misc_amb4 entity. The way they loop it is by setting nextthink of the entity to precisely level.time + 2.7. This is a very sensitive system, could easily break if timing of G_RunFrame calls or sound scheduling changes, or heck, maybe the speed of the sound playback is slightly faster?

I was able to "fix" it simply by changing 2.7 to 2.6 but I wouldn't consider this a satisfactory fix, at least not until the root cause of the different behavior is known.

**Comment by Yamagi** [comment]
I have a theory: The sample is exactly 2720 milliseconds seconds long, so 2.7 seconds should be okay. But Vanilla Quake II was synchronous, every renderer frame was also a client frame. And the whole internal timing stuff was in milliseconds. With enough renderer frames it's pretty save to asume that `level.time + 2.7` is nearly always reached in time. YQ2 is synchronous, `R_RunFrame()` is called cl_maxfps times second, independent of renderer frames. And our timing is in microseconds, they're rounded down to milliseconds when leaving the timing code... With the increased timing resolution and some rounding errors it might become more or less impossible to to reach `level.time + 2.7` before the 2.7 seconds are over. And even 10 milliseconds to late is enough for a small, annoying pause. 

And indeed, changing cl_maxfps has an audible effect, lowering or increasing it also changes the length of the pause. So lowering the interval to 2.6 or even better 2.5 should be okay.


But Vanilla Quake II was synchronous and the internal timings rather inaccurate, `SV_Frame()` was called at every renderer frame and the server <-> game . YQ2 is asynchronous  and calls `SV_Frame()` about `cl_maxfps` times a second. It might actually a little bit more or less, nevertheless it should be in a margin of about 6 frames around the requested value... While the game should run with excatly 

(Setting `cl_async 0` doesn't really change that, it just forces every renderer frame to trigger a package frame. That's more a simulation of Vanilla Quake IIs behavior than an exact implementation)

rather than calling the game.dll every 50 milliseconds it could have been
