### ISSUE TITLE
Software gunFOV

### ISSUE THREAD

**Issue by StepanST** [yquake2/yquake2#507]
I have some ideas to slove wrong gun position in software mod in resolution wuth not 4;3 aspect ratio. To slove this problem I jast change r_gunfov valuse. In 4;3 r_gunfov=90, in 3:2 r_gunfov=98. in 16;9 r_gunfov=105, and in OpenGL r_gunfov=75. What if use diferent cvars for gun position in OpenGL and Software modes and make some function, that deteckts aspect ratio and if aspect ratio is not 4;3, multiply  gunfov cvar for some value depending on wich aspect ratio is now. Maybe it posibl to find some formula.

**Comment by Yamagi** [comment]
I had a deeper look into the soft renderer. Read: I tried to actually understand the math and did some calculations. 

It's impossible - at least with lager changes to the model transformation code - to get a perfect gun fov like in the GL renderers, because the soft renderer is missing a way to configure the perspective matrix. But with some small  hacks it's possible to manipulate the transformation matrix for each entity. In fact we're doing already that to render the gun with some kind of fake fov.

In e466554 I've changed that manipulation to give a more or less correct perspective for the gun, regardless of the scenes fov. The problem with that is a wrong gun position, while the perspective is correct, the Z axis (would be the X axis in the GL renderers) is off. I think that can be corrected by adding an offset to the weapon entities view matrix.

It would look like this:

![z_offset](https://user-images.githubusercontent.com/1224576/74960172-211b4f00-540c-11ea-8696-ca8e73ec7d08.jpg)

If everybody is okay with that I would a new cvar `sw_gunzoffset` to make the gun Z offset configureable.

**Comment by Calinou** [comment]
I like the idea of being able to configure the gun offset freely. Maybe this should work in the OpenGL renderer as well? Many popular FPSes such as CS:GO feature such an option (not just on the Z axis).

**Comment by Yamagi** [comment]
I've just pushed the addition of `sw_gunzoffset`. It defaults to 8` which more or less matches the GL renderers. It can't work this way in the GL renderers, because they're just manipulating the perspective matrix used to render the gun. A freely configurable gun position would likely require some transformations to the model and I'm not sure if that can work, the gun models are designed to be rendered at the bottom right edge of the screen.
