### ISSUE TITLE
[Bug] gl_nolerp_list doesn't seem to work properly

### ISSUE THREAD

**Issue by eduardodesigner** [yquake2/yquake2#526]
I'm not sure if it's a bug or if i'm doing something wrong, but any longer list for gl_nolerp_list, 
such as this one:

gl_nolerp_list "pics/areyousure.pcx pics/backtile.pcx pics/ch1.pcx pics/ch2.pcx pics/ch3.pcx pics/conchars.pcx pics/help.pcx pics/inventory.pcx pics/loading.pcx"

when put in autoexec.cfg, results in an empty list when checked in the console.

Is this cvar really not meant to take longer lists such as this one? And if not, is there a way to tell gl_nolerp_list to consider all the files in pics folder?

**Comment by Yamagi** [comment]
Hi,
the problem here is likely the string tokenizer, after a very first look:

1. Each line in a config ends up in Cmd_TokenizeString().
2. Cmd_TokenizeString() calls COM_Parse().
3. COM_Parse() limits one token to MAX_TOKEN_CHARS which is 128 chars.

Both COM_Parse() and MAX_TOKEN_CHARS are part of the game API and cannot be changed. Give @DanielGibson and me a few days to have a deeper look into this.

**Comment by eduardodesigner** [comment]
Take all the time you need, of course!
Thanks for the quick response.

**Comment by Yamagi** [comment]
I've just pushed a fix. Arguments passed to cvars can now be up to 1024 bytes long, instead of only 128 bytes before. While even longer strings would be preferable we must be sure that we don't overflow the stack. So this is all we can do. I'll upload new Windows binaries to https://deponie.yamagi.org/quake2/windows/testbuilds/ tomorrow.

**Comment by BjossiAlfreds** [comment]
You can actually use the same strategy as strtok() and just work with the input string directly rather than copying sub-strings to a separate buffer, temporarily replacing chars with null-terminators to get the desired sub-strings and return those from the function to whoever wants the token. This avoids any copying and so the buffer limit is as long as the the amount of memory used for reading the config file into memory. Escaping and other text processing can then be done "last-minute" (only when really needed) by whatever code requested the token, whether it is command handlers or something else.

Of course this would require a re-write of COM_Parse() from scratch pretty much, and update all places where it is called. It'd definitely be an adventure to do this but from where I stand it seems fairly do-able.
