### ISSUE TITLE
[Bug/Discussion] Commands, config files and quotation marks

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#527]
The result of executing commands with parameters inside "" is not consistent. use "Hyper Blaster" does not work from the in-game console because this command uses gi.args() to parse the parameter.

The say command is even more curious. If you say "hello there" it removes the " for the output message, but if you say "hello" "there" both groups of " are still there in the output message.

Another aspect of this is that the input parser does not support escaped ". So writing for example bind 3 "use \"Super Shotgun\"" would not work even if gi.args() removed the non-escaped ". This makes it impossible to bind complex commands to keys where you need to wrap some parameters into quotes, this is for example the case with give "mag slug" 20 in xatrix.

In general this is not a big issue, at least for the standard game.dll's and most players, but I do think it would be beneficial to make gi.args() remove quotes like gi.argv(x) does, and support "-escaping, as with these features it would always be possible for users to adapt their config entries if necessary.

However I wouldn't apply these changes for the parsing of the level entity string, as it would require us to ship fixed .ent files with the package to fix any issues that come up. I do know about a few cases in map train where some fields have a \ as a last character for some reason.

Any thoughts on this? Be adventurous or play it safe and leave things as-is?

**Comment by Yamagi** [comment]
@DanielGibson and I had a look into this while we discussed the fix for #526. On the one hand fixing this sound tempting, because it might be a problem in some corner cases and for custom game DLLs. At the other hand this has a high probability for some strange, unwanted side effects. The whole command parsing stuff is already highly complicated, buggy and works only by luck. A fix would require changes to `Cmd_Args()` or a wrapper around it and both option sound dangerous. So we're inclined to play it save.
