### ISSUE TITLE
Crashes when fullscreen activated on Dual Screen Mac OS X Mavericks

### ISSUE THREAD

**Issue by kevpatts** [yquake2/yquake2#53]
Running Hackintosh, but should not matter as using internal Intel graphics (i7 4770K). Primary screen HDMI, secondary DVI. Disabling the DVI screen makes it work fine.

**Comment by Yamagi** [comment]
Nice. :) Maybe I'm a bit late to the party, but the biggest problem would be that YQ2 on OS X was never ported to SDL2. That shouldn't be too hard...

**Comment by jdolan** [comment]
Yea. Frankly, there's no reason it can't just use the same code path as Linux for SDL2. I think the vast majority of the NSApplication class in YQ2 could go away. A couple lines to resolve the game directories so that resources and the game module can be loaded from the app bundle are all that is necessary. SDL takes care of the rest. Here's the relevant code in Quake2World that determines if the game is running from an app bundle in order to kickstart the VFS:

https://github.com/jdolan/quake2world/blob/master/src/sys.c#L63
https://github.com/jdolan/quake2world/blob/master/src/filesystem.c#L589

I've already managed to get yquake2 compiling and running on Yosemite, ignoring all sdl_osx/SDLMain.m. I'll see if I can get a pull request together soon (won't be this weekend tho).

**Comment by Yamagi** [comment]
OS X support was dropped.
