### ISSUE TITLE
Multiplayer Powerup Pickups

### ISSUE THREAD

**Issue by oGkspAz** [yquake2/yquake2#547]
Picking up Powerups in multiplayer with 'Instant Powerups' enabled still plays pkup.wav instead of damage.wav or protect.wav as needed

**Comment by ulatekh** [comment]
The DF_INSTANT_ITEMS logic in yquake2's game code looks identical to the logic in the original game code. Are you sure Quake II used to behave that way?

**Comment by oGkspAz** [comment]
I tested normal q2 vs yamagi before posting just to be sure. Just ran another test with s_show 1. Images attached.
![Quadpickup_Q2_default](https://user-images.githubusercontent.com/13630539/78472522-c9c20b80-7739-11ea-9a43-beb637af6f80.jpg)
![Quadpickup_Q2_Yamagi](https://user-images.githubusercontent.com/13630539/78472524-cb8bcf00-7739-11ea-8e74-88c22d41ad20.jpg)

**Comment by BjossiAlfreds** [comment]
The quad sound is scheduled for playback before the item pickup sound, so the latter will override it. This was not the case until recently because we reversed the order in which sound events with identical play times are scheduled as a quick fix for monsters playing outdated sound effect when dying/gibbing (especially when killed by the shotguns).

One quick fix I can think of is to add a check for DF_INSTANT_ITEMS and powerup pickups to the general pickup sound to make sure these sound events are mutually exclusive.

**Comment by oGkspAz** [comment]
I just tested so I could give feedback for now: Rebreather and Environment Suit play normal pkup.wav in default Q2 so that should be fine.

**Comment by BjossiAlfreds** [comment]
I've made pull requests that I believe fix the bug in Q2 and the 2 expansion packs. If anyone here has the tools and knowledge to build and test my changes then feel free.

**Comment by Yamagi** [comment]
I've merged the pull requests.
