### ISSUE TITLE
Vsync cause slight input lag

### ISSUE THREAD

**Issue by richterdeveloper** [yquake2/yquake2#554]
In Windows, when I set vsync on in OpenGL 1.4 or 3.5, it causes a slight input lag in the keyboard commands (forward, crouch, jump, step left, step right, etc) compared to original game running in OpenGL 1.4.

Tested in:

Processor: Intel Core i7 3770k (stock clock)
Video: Asus Nvidia GTX 970 (lastest Geforce drivers)
Sound: Realtek ALC892
SO: Windows 10 x64 (ver. 1909)
USB Keyboard and mouse

Thanks!!

**Comment by DanielGibson** [comment]
Hmm.. no idea how to even measure (or reliably notice) this, shouldn't be more than one frame (16ms at 60Hz?) of input lag at least?
Does all kind of input lag, or only keyboard or only looking around with the mouse or..?
What operating system are you on?

We get all the events from SDL each frame and react to them in the same frame (I think? Or is there anything that could cause delay @Yamagi ?), so if there indeed is further lag, that's caused by SDL and we can't do anything about it.

If this can be reproduced and measured though (any ideas?) the SDL developers might be interested in figuring out what causes it.

**Comment by richterdeveloper** [comment]
> 
> 
> Hmm.. no idea how to even measure (or reliably notice) this, shouldn't be more than one frame (16ms at 60Hz?) of input lag at least?
> Does all kind of input lag, or only keyboard or only looking around with the mouse or..?
> What operating system are you on?
> 
> We get all the events from SDL each frame and react to them in the same frame (I think? Or is there anything that could cause delay @Yamagi ?), so if there indeed is further lag, that's caused by SDL and we can't do anything about it.
> 
> If this can be reproduced and measured though (any ideas?) the SDL developers might be interested in figuring out what causes it.

Information updated in the first post.

**Comment by Yamagi** [comment]
> Or is there anything that could cause delay @Yamagi ?

Nothing I know of.

**Comment by Yamagi** [comment]
I had a look at the code: This is very likely the 16ms delay introduced by the vsync. Input is read by the operating system as soon ans the event is generated and by Q2 at the beginning of the frame. The vsync is at the end of the frame. So in the worst case there's a 16ms delay (at 60hz) between the user input and the time the corresponding frame is displayed. I'm afraid that there's nothing we can de about it.
