### ISSUE TITLE
Screen border artefacts on OpenGL keep resolution settings

### ISSUE THREAD

**Issue by runlevel5** [yquake2/yquake2#555]
![Screenshot from 2020-04-10 11-37-58](https://user-images.githubusercontent.com/135605/78954507-bfc85000-7b1f-11ea-8401-7a09f63bf531.png)

```
$ uname -ar
Linux orion.dev 5.6.0-0.rc7.git1.2.local.fc33.ppc64le #1 SMP Sun Mar 29 10:28:55 AEDT 2020 ppc64le ppc64le ppc64le GNU/Linux
```

Is it normal to have the flickering artefacts when running in 'keep resolution' settings?

**Comment by Yamagi** [comment]
This is a long standing problem in SDL. OpenGL doesn't require the GPU driver to clear the framebuffer and at least Mesa3D doesn't do it. SDL doesn't clear it either, so you'll get garbage in the area surround the YQ2 windows. We can't do anything about it, because we can only write to out part of the framebuffer.
