### ISSUE TITLE
Can't hear firing own weapons in dday mod

### ISSUE THREAD

**Issue by InFerYes** [yquake2/yquake2#558]
In DDay when I fire **any** weapon in the game, my own gunshot is not heard. I can hear other people fire the same guns.

I have checked with `developer 1` in console but see no missing files or errors.

I have tried compiling [q2pro](https://github.com/skullernet/q2pro) to check if the problem is local (missing files) but after symlinking the same folders (baseq2 and dday) it properly plays the gunshots in q2pro, so I'm suspecting it's a yamagi bug. 

An example: (https://github.com/InFerYes/dday/blob/master/gbr/gbr_guninfo.c)
```C
GunInfo_t gbrguninfo[MAX_TEAM_GUNS]=
{
....
	{//Lee Enfield
		{4},{86}, 16,101, 81,81,

			"gbr/303/unload.wav",
				{58},
		
			"gbr/303/reload.wav",
				{67},
		
		"gbr/303/fire.wav",
		"gbr/303/lastround.wav",

		MOD_RIFLE,
		DAMAGE_Enfield, 0,
		13//17
	}
...
};
```
![https://i.imgur.com/uzMr2br.png](https://i.imgur.com/uzMr2br.png)

unload.wav and reload.wav are played properly, fire.wav and lastround.wav are not.

**Comment by Yamagi** [comment]
This could be another fallout from 16ee007. @bibendovsky, @BjossiAlfreds: What do you think?

**Comment by BjossiAlfreds** [comment]
A simple way to check is to reverse that change and then test the mod. Though that change only affects sound events with same scheduled time (reversing the priority so that newest scheduled sound event plays over old ones), so unless I'm missing something there would have to be another sound event that is overriding the firing sounds.

**Comment by InFerYes** [comment]
I reverted this locally and now the firing sounds are played correctly.

**Comment by BjossiAlfreds** [comment]
The old sorting was that the first scheduled sound overrides others that come after it with the same play time. What I wonder now is what sound event is being scheduled after the firing sound to cause this to happen? It should be relatively easy to trace the source code for that, at least assuming it is on the game API side - Quake 2's muzzleflashes and effect stuff does a lot of hard-coded shenanigans outside the game API.

**Comment by InFerYes** [comment]
I don't know enough about the game to find how the sounds are being played and trace everything. I just fix trivial things as I come across them.

**Comment by BjossiAlfreds** [comment]
Is the source code available somewhere? I'd be curious to take a look. One quick thing you could try is temporarily change the channel of the gi.sound() calls for the firing sounds and see what happens.

If we can figure out what is happening, that would be a ground for discussing whether to permanently change the ordering back.

**Comment by InFerYes** [comment]
Yes, the code/repository is in the OP.

**Comment by BjossiAlfreds** [comment]
I looked at the firing functions in dday/g_weapon.c. There is nothing really wrong there, it plays the gun firing sound with a simple gi.sound() call and sends a muzzleflash message, no other sound events happen after that that I can see.

I did some testing of my own in the default Q2 game code and I think this is because of the muzzleflashes. I made the original Q2 machinegun fire function play snd_fry. In YQ2 this was completely ignored and it played the normal gun sound, while in original Q2 only the snd_fry sound played but the machinegun sound was completely ignored. So the muzzleflash itself is playing a sound outside the game API.

This is actually a pretty fatal issue as it could affect pretty much all mods with custom guns, as long as they play custom gun sounds and use the default gun muzzleflashes. On the game API side it is always possible to ensure mutual exclusion of sound events, however the muzzleflash sounds are hard-coded and not possible to control from the default game API. Regardless of when you play the gun sound during ClientThink it will always be overriden by the muzzleflash with the current ordering of sound events.

The only possible fix I can think of here is to create a blank sound file and play that on CHAN_WEAPON, and play the actual custom gun sound on a different channel. Would be hacky and probably error-prone too.

What are your thoughts on this guys?

**Comment by Yamagi** [comment]
What about reverting the client to the old behavior for all games / mods except baseq2, rogue and xatrix? Something like this:

```
diff --git a/src/client/sound/sound.c b/src/client/sound/sound.c
index e146183e..8106cd26 100644
--- a/src/client/sound/sound.c
+++ b/src/client/sound/sound.c
@@ -723,10 +723,27 @@ S_StartSound(vec3_t origin, int entnum, int entchannel, sfx_t *sfx,
        }
 
        /* sort into the pending sound list */
-       for (sort = s_pendingplays.next;
-                sort != &s_pendingplays && sort->begin <= ps->begin;
-                sort = sort->next)
+       cvar_t *game = Cvar_Get("game",  "", CVAR_LATCH | CVAR_SERVERINFO);
+
+       if ((strcmp(game->string, "") == 0) ||
+               (strcmp(game->string, "rogue") == 0) ||
+               (strcmp(game->string, "xatrix") == 0))
+       {
+               printf("Neu\n");
+               for (sort = s_pendingplays.next;
+                               sort != &s_pendingplays && sort->begin <= ps->begin;
+                               sort = sort->next)
+               {
+               }
+       }
+       else
        {
+               printf("Alt\n");
+               for (sort = s_pendingplays.next;
+                               sort != &s_pendingplays && sort->begin < ps->begin;
+                               sort = sort->next)
+               {
+               }
        }
 
        ps->next = sort;
```

**Comment by InFerYes** [comment]
Are there no (total conversion) mods that just heavily modified baseq2?

**Comment by Yamagi** [comment]
They would still have a distinct game dir in the `game` cvar.

**Comment by BjossiAlfreds** [comment]
This may be the best solution for backwards-compatibility. At some point I might play around with muzzleflash sound prioritization but for now that check will do the trick.

**Comment by Yamagi** [comment]
I've just pushed the fix to master.

**Comment by Yamagi** [comment]
And I've merged @bibendovskys pull request. A new set of Windows binaries is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20200504-3492dff.zip
