### ISSUE TITLE
Strange bug with lifts/doors and saves.

### ISSUE THREAD

**Issue by xDShot** [yquake2/yquake2#58]
My OS - Manjaro Linux x64. Used latest (current) git build of Yamagi Quake II

How to reproduce:

1. Provoke movement of lift by standing on it or pressing button.
2. (Quick)save your game while it moves.
3. Load this game.
4. You will see that lift is NOT on the same position as it was during the saving of the game.

Here are the video demonstrations which can clearly show what does happen:

http://youtu.be/LTb83H26okQ
http://youtu.be/y8dW_3PzcKw
http://youtu.be/rkjhm2YxUUM

And it seems the doors can somehow be related to this issue. It began closing while it was yet opened:
http://youtu.be/8uxB02qeHjE

Let me know if you need additional info and sorry for my poor English :)

**Comment by Yamagi** [comment]
Yeah, I would call it a bug, too. But it's not something that can be solved. Quake II needs to advance the game by a few frames after a savegame was loaded. That is by design, because some entities can only spawned in on frame changes. Therefor you never get the exact state which was saved, but something else a few frames later. It's annoying, I know. :(
