### ISSUE TITLE
Music tracks play even with ogg_enable set to "0"

### ISSUE THREAD

**Issue by tdm4** [yquake2/yquake2#583]
In https://github.com/yquake2/yquake2/blob/master/src/client/cl_view.c#L364-L367
it calls OGG_PlayTrack but it doesn't check if ogg_enable is not 0

So if you have the music disabled, it still plays a track on level startup.

**Comment by Yamagi** [comment]
That bug was a little nastier than I thought. The problem was, that `ogg_enabled` toggled whether the backend should be initialized or not. Once it was initialized, changing the cvar didn't shot it down. So the next call to `OGG_PlayTrack()` started the music... I've changed the code, if `ogg_enabled == 0 && ogg_started == true` `OGG_Shotdown()` is called. Thank you for the report! :)

**Comment by tdm4** [comment]
Thanks! Always glad to help!
