### ISSUE TITLE
Git version is a bit buggy and not smooth

### ISSUE THREAD

**Issue by AngryPhantom** [yquake2/yquake2#591]
Hello, guys

First, thank you very much for this port of Quake2!

I was having problems to make my double jump alias to work but to no avail in ANY _release_ version.

```
//Doubble Jump
alias wt "wait;wait;wait;wait;wait"
alias +dj "+moveup;wt;-moveup;wt;+moveup"
alias -dj "-moveup"
bind MOUSE2 "+dj"
```

I'm on Debian and using Yamagi from the repos: version 7.40. So I decided to compile 7.43 from here.
Still no way to make double jump work. I've tried all possible aliases out there.

Today I *git cloned* Yamagi and compiled it. And now double jump works! But... I'm getting like 150 fps and a strange *tearing* gameplay instead of smooth one with 300 fps with release versions of the game (configs are the same, I didn't touch them).
Now I guess it has something to do with the fps thing, I'm not sure...

Can you advise me something? Is it possible to make it smooth again? Is there some magic config variable? What has changed in the git version? Can I help you debug it somehow?

P.S. I also cannot make the game use female models to work. It's just the default one regardless of my configs. Any clue?

Thanks in advance.

**Comment by DanielGibson** [comment]
Are you building with the Makefile or with CMake?
If CMake, you might be building an unoptimized Debug build which can be slower (for the Makefile the default is an optimized build, unless `DEBUG` is set)

**Comment by AngryPhantom** [comment]
@DanielGibson No. Simple `make`

**Comment by AngryPhantom** [comment]
> you need the baseq2/players/ subdirectory

Yes, I have it too.

**Comment by DanielGibson** [comment]
Interesting - no idea about the playermodel issue right now, if it's there (`/baseq2/players/female/*`) it should work - and does for me, with latest git: If I select a female playermodel in the Multiplayer -> player setup menu and start a game and jump, I hear the female grunting noise.

Regarding performance: Can you try building 7.40 and 7.43 yourself and see if you also have the performance issues with them?

* If you have them with 7.40, something is going wrong with building (because your 7.40 debian package doesn't have them).
* If 7.43 doesn't have them either we know they have been introduced afterwards.
* If 7.43 **does** have them, can you also try 7.42 (and if 7.42 has the issues, also 7.41) so find out which was the first version with the issues?

Thanks in advance! :)

**Comment by AngryPhantom** [comment]
@DanielGibson Oh, never mind. Probably the directory was missing some models. Downloaded and unarchived the q2-3.20-x86-full-ctf.exe you mentioned and now it's fine. Thanks. Now the performance part. Will try that soon...

**Comment by DanielGibson** [comment]
Glad to hear the models work now!

One quick check for performance: do `make clean` and then `make VERBOSE=1` and paste the output for one file, like

```
===> CC src/client/cl_inventory.c
mkdir -p build/client/src/client
cc -c -O2 -Wall -pipe -fomit-frame-pointer -std=gnu99 -fno-strict-aliasing -fwrapv -MMD -DYQ2OSTYPE=\"Linux\" -DYQ2ARCH=\"x86_64\" -mfpmath=sse -fvisibility=hidden -Wno-unused-result -DUSE_CURL -DUSE_OPENAL -DDEFAULT_OPENAL_DRIVER='"libopenal.so.1"' -DHAVE_EXECINFO -I/usr/include/SDL2 -D_REENTRANT -DNOUNCRYPT -I/usr/include -o build/client/src/client/cl_inventory.o src/client/cl_inventory.c
```

If it doesn't contain the `-O2` part (but maybe `-O0` instead) you're getting an unoptimized debug build.
Furthermore, the output of `cc --version` would be interesting to know.

**Comment by AngryPhantom** [comment]
@DanielGibson 7.40 and 7.43 are fine as I've already said in my post. It's been introduced afterwards, somewhere in the git version. The interesting part is that now my double jump alias is working! But the performance is really strange, it is a bit jerky/tearing/not smooth (sorry, English is not my native language).

**Comment by DanielGibson** [comment]
sorry, it wasn't clear to me that you also tried 7.43 (or rather, you only mentioned double jump doesn't work, not what the performance was like)

However, as we have another report about bad performance in latest git (https://github.com/yquake2/yquake2/issues/588#issuecomment-677675764) it's likely we introduced some problem afterwards.

If you're familiar with git, you could try bisecting it to find the exact commit that introduced the issue

**Comment by AngryPhantom** [comment]
@DanielGibson Yeah, I guess he's got the same problem.

1.
> cc --version
cc (Debian 8.3.0-6) 8.3.0

2.
> ===> CC src/client/cl_inventory.c
mkdir -p build/client/src/client
cc -c -O2 -Wall -pipe -fomit-frame-pointer -std=gnu99 -fno-strict-aliasing -fwrapv -MMD -DYQ2OSTYPE=\"Linux\" -DYQ2ARCH=\"i386\" -ffloat-store -fvisibility=hidden -Wno-unused-result -DUSE_CURL -DUSE_OPENAL -DDEFAULT_OPENAL_DRIVER='"libopenal.so.1"' -DHAVE_EXECINFO -I/usr/include/SDL2 -D_REENTRANT -DNOUNCRYPT -I/usr/include -o build/client/src/client/cl_inventory.o src/client/cl_inventory.c

3.
> try bisecting it to find the exact commit

Oh, that's beyond my knowledge. I'm really sorry for that :(

**Comment by DanielGibson** [comment]
Ok, no worries; I just realized that I can reproduce the problem on my machine so I can bisect myself :)

**Comment by AngryPhantom** [comment]
@DanielGibson 

> I can reproduce the problem

That's nice. I hope you'll find it and I will be able to use aliases. Actually, I couldn't figure out why they didn't work. But there is a slight suspicion that if you fix the performance it won't work again...

**Comment by DanielGibson** [comment]
alright, I think I found it, in src/common/frame.c line 148

```c
				if (Sys_Microseconds() - spintime >= 5000)
				{
					break;
				}
```
shouldn't be `5000` but `5` - can you make that change and see if it also helps on your system?

**Comment by AngryPhantom** [comment]
@DanielGibson Should I git clone again or simply `make clean`?

**Comment by DanielGibson** [comment]
just modify the file and run `make` it will rebuild what's changed (I haven't checked it into git yet)

**Comment by AngryPhantom** [comment]
@DanielGibson Yes, now the performance is back again. Thanks! And yes, I've figured out that if I **enable** vertical sync in the game Video options menu I get 60 fps and the double jump alias is working but the gameplay is a bit laggy (it's not jerky as in my original post, but my mouse is a bit strange, it lags some milliseconds when I make a move).
But when I **disable** vertical sync I get 300 fps (the maximum in the config) but no double jumping. And the performance is just great, smooth and the mouse is not laggy Strange. 
Probably, I just got extremely used to Quake III engine as I play OpenArena a lot and decided to remember old times with Q2 just a couple of days ago... Maybe it has something to do with the Q2 engine and you really can't do anything about it in the code. So I will just play myself with video resolutions/vertical sync/nvidia card options.
So, I guess I will close the issue as the main problem is gone - the performance is normal again. Thanks!

**Comment by DanielGibson** [comment]
I guess the wait is framerate-dependent? So maybe at 300fps you need to wait 5x as much?

Haven't checked where/when wait is executed, so maybe this is bullshit, but it would explain the issue

**Comment by AngryPhantom** [comment]
@DanielGibson Yeah, I guess so. That is what I was wondering. So will try to put more waits. Thanks :)

**Comment by DanielGibson** [comment]
We might have ideas for making `wait` framerate-independent, but we'll have to think about that more thoroughly when we have some more time (and figure out if it really is possible without breaking other things).

I'll reopen this as a reminder that `wait` could be improved.

**Comment by AngryPhantom** [comment]
@DanielGibson Oh, that would be nice indeed. Thanks.

**Comment by AngryPhantom** [comment]
@DanielGibson Well, after trying every possible number of _waits_ I still cannot make it work with _vertical sync disabled_. Tried 5x as much and even more, like 10x and 20x to no avail. I'm out of ideas.

**Comment by Yamagi** [comment]
`wait` delays the execution of further commands by one call to the command buffer code. In Vanilla Quake II that was one call every render frame, the faster your system was, the more `wait` commands were needed to make the macro work. In YQ2 we've rewritten the internal timing code, mostly to make the client asynchronous. The command buffer code is now called up to 1000 times a seconds, unless the game gets slowed down by waiting for the vsync or network. Because of that the macro work with vsync enabled, but that's only by luck. 

We'll try to decouple `wait` from the internal timings, maybe something like 'each `wait` command delays all further commands by 16 milliseconds'. 16 milliseconds are about 60 FPS.

**Comment by AngryPhantom** [comment]
@Yamagi Ok, thank you. So it's not possible to make it work at the moment, right?

**Comment by Yamagi** [comment]
Nope, no chance. Even `cl_async 0` won't help and would add the physic problems caused by the 125 hz bug.

**Comment by DanielGibson** [comment]
well, vsync @60Hz helps ;)

**Comment by AngryPhantom** [comment]
@Yamagi Ok, got it. Will wait;wait;wat for the fix... :)

**Comment by AngryPhantom** [comment]
@DanielGibson Awesome! Now it works with **vertical sync disabled** with my maximum framerate as needed. I just had to reduce the number of waits from 5 to 3 in order to fine tune it a bit:
```

//Doubble Jump
alias wt "wait;wait;wait"
alias +dj "+moveup;wt;-moveup;wt;+moveup"
alias -dj "-moveup"
bind MOUSE2 "+dj"
```

One last thing... I don't know how to describe this one properly. When you run with a strafe (in order to run faster) the gameplay, so to say, strangely reacts to left or right turns (when you change them while running) and you just stop or just slide to the side. That thing is absent with **vertical sync enabled**. Is it possible to fix that?

**Comment by Yamagi** [comment]
Without having looked into the code: I don't think so, because client updates are interpolated over renderer frames. And the more frame you renderer the bigger the error gets. You could try to set `cl_async 0` to force a client update at every renderframe but that will introduce physics and movement error starting at about 95 FPS.

**Comment by AngryPhantom** [comment]
@Yamagi Well, `cl_async 0` fixes this partially, but still the gameplay is a bit wacky and strafe-running is not nice :(
Should I open a new issue? Or can you reopen it in order to not forget?

**Comment by Yamagi** [comment]
This isn't really a bug but deserves some explanation: Vanilla Quake 1 to Quake 3 were synchronous. Each render frame the complete client was executed, among other things all movement and physics calculations. Quake 1 and 2 were build against a minimum framerate of 10 FPS, because in 1996 Pentium CPUs were still expensive. The bigger the difference between 10 FPS and the actual framerate got, the greater the error margin of the movement and physics calculations were. On lower framerates that led to effects like strafe jumps or double jumps being fast and / or longer than normal jumps. Starting at about 95 FPS things got haywire, until the point that the player could rocketjump through walls and the like. Therefor deathmatch players liked high framerates, because it gave them advantages. And server admins hated them, because every render frame send at least one package to the server flooding the slow 56k line.

Q3A rearranged things quite a bit. The game was build against a minimum framerate of 30 FPS, things moved between the client and the server and the calculation were more precise. The point were the problem started moved up to about 120 FPS, and the problems weren't as big. Just a little but faster movement here and further jumps there. With some of the later patches id Software added `pmove_fixed 1`, solving the problem one and for all.

The first Quake 1 or 2 sourceport, that tried to solve the problem, was r1q2. It's solution was only half baked, setting `cl_async 1` had side effects. Most noteably was the player getting stucked in walls. Nevertheless some other sourceports ported that effort and made it somewhat better. For YQ2 we've rewritten the internal timings from scratch. We bumped the millisecond resolution to microseconds, thus removing most inaccuracies. And we've split the client into 2 distinct timing zones, the client and the renderer are completely independent. The only constraint is, that there must be more render frames than client frames, because every client frame must be processed by the renderer. The code enforces that.

There're four cvars controlling the timing:
* `cl_maxfps` are the client frames. They're set to 60 by default. You can set them to whatever you want, but the source will limit them to `vid_maxfps - (vid_maxfps * 0.03)`. If you set `cl_maxfps` to something higher than about 95 the movement and physics will start to degrade. To get strafe and double jumps you'll likely need to increase `cl_maxfps`.
* `vid_maxfps` are render frames. The renderer will try to render `vid_maxfps` frames. If it renders fewer frames it either hits the CPU or GPU limit or is slowed down by the vsync. You can increase `vid_maxfps` to up to 999 (parts of YQ2 still build with milliseconds in mind, so a frame can never be shorter than 1 millisecond).
* `cl_async` set to1 emulates the Vanilla Quake 2 timing. In that case `cl_maxfps` is ignores and the both the client and the renderer are called `vid_maxfps` times a second. It's often better to leave `cl_async` at 0 and increase `cl_maxfps` to get "broken" movements and physics.
* `r_vsync` tells the renderer to wait for the next frame. The renderer is entered, it waits and returns. When `r_vsync` is set to 1 or 2, `cl_maxfps` is limited to `display_refresh_rate - (display_refresh_rate * 0.03)`.

There's one corner case: Client input must be interpolated onto render frames. For example the player needs to move every frame, otherwise the game would stutter. But this interpolation is error prone. That's likely the reason for slightly different behavior with `r_vsync' 0 and 1.

**Comment by AngryPhantom** [comment]
@Yamagi First of all, thank you very much for such detailed explanation!

What I meant is that when I'm strafe-running (pressing *forward* while interchanging *left* and *right*) pressing of *left* (or *right*) makes me just step aside occasionally, thus making strafe-running a bit uncontrollable. And such behavior is absent with **vertical sync enabled**. Is this what you meant explaining the timing and frame rates?

So, is there hope to fix it if I just play with all these cvars and parameters in the config?

**Comment by Yamagi** [comment]
I finally found the time to test this and I can't reproduce the problem. With a new config file, just display resolution changed to 2560x1440, all keystrokes are recognized when pressing *forward* or *backward* and strafing *left* to *right*. Even if I'm pressing the *left* and *right* unreasonable fast all keystrokes are recognized. The game was running at 300 FPS. That doesn't mean that the problem doesn't exists, only that it is not that easy to reproduce.

@DanielGibson can you give it a try?

**Comment by AngryPhantom** [comment]
@Yamagi

Ok, **enable** vertical sync in the game video settings (I have it also *disabled* system-wide, in the NVidia settings).

Now strafe run: press *forward* and interchange *left*/*right* (without releasing *forward*). Try to run a bit in an arc/arch direction, not just straight. But it actually doesn't matter.

It should be smooth and perfect.

Then **disable** vertical sync in the game options and try to do the same.

When vertical sync is disabled interchanging *left*/*right* buttons strangely interferes with strafe running and I really don't know why: accidental pressing on *left* or *right* makes the player just stop running and swerve to the side instead of continue speeding up.

Here are my two configs (in case there are some wrong cvars or something, if it helps): [config.cfg](https://pastebin.com/raw/3P6whVZb) and [dm.cfg](https://pastebin.com/raw/L9fsJFuV) (additional one, executed upon start).

**Comment by AngryPhantom** [comment]
Update: you can also try to make a circle strafe run on some open space map. Just press *forward* + *right* and run. It also makes me *step to the side* after some time.

**Comment by AngryPhantom** [comment]
@Yamagi Oh, and I also have `cl_async 1` (it's in the dm.cfg). Should I use `0` instead?

**Comment by AngryPhantom** [comment]
Update: tried cl_async 0, but now it's really hard to jump on long distances like the one to get megahealth on q2dm1. Well, it fixes the movement a bit but it's not that perfect as with enabled vertical sync (bit it's giving other problems with wavy and uncontrollable mouse...).

**Comment by DanielGibson** [comment]
What if you use `cl_async 0` with a more reasonable framerate, like 120 (instead of 300)?
Maybe it works better and is a good compromise?

**Comment by AngryPhantom** [comment]
@DanielGibson Nope. Just the same :(

**Comment by Yamagi** [comment]
I really don't know. You're on Linux?

**Comment by AngryPhantom** [comment]
@Yamagi Yes. Debian and Void Linux.

**Comment by Yamagi** [comment]
Hmmm... Let's wait in Daniel can reproduce it. At the moment I'm clueless. :/

**Comment by AngryPhantom** [comment]
@Yamagi

I'm having:

```
set vid_displayrefreshrate "-1"
set vid_rate "-1"
```

Probably because of `r_mode "-1"` (custom resolution is set). Can it be the culprit?

Please can you give me your config? I'll test it too.

**Comment by Yamagi** [comment]
Yeah, `vid_displayrefreshrate` is only for some buggy drivers that give a wrong refresh rate. As far as I know that's only AMDs Windows driver for GCN GPUs. On Linux everything should be okay. `vid_rate`isn't supported by YQ2, so that's a noop.

My config is here: https://pastebin.com/FEmPHHMV

**Comment by AngryPhantom** [comment]
@Yamagi Thanks for the config but it didn't help much.

I've recorded two demos for clarity, to guide your eyes, so to say.

The first one: https://gofile.io/d/43nLMs (**vertical sync disabled**, bad strafe running but perfect in-game mouse movement*)
The second one: https://gofile.io/d/NJuKYp (**vertical sync enabled**, perfect strafe running but bad in-game mouse movement*)

Just put the files in _.yq2/baseq2/demos_ and type `map bad.dm2` and then `map good.dm2`

_*bad in-game mouse movement, as I've mentioned above, means a bit laggy mouse (like wavy). It doesn't react INSTANTLY to my moves, thus has a tiny millisecond lag._

**Comment by AngryPhantom** [comment]
I don't know if it helps you. But thanks for your patience and feedback :)

**Comment by AngryPhantom** [comment]
I guess I've found out why that happens. It's because of my double-jump binding to the right mouse button. I'm just constantly double-jumping while strafe running instead of simple jumps...
The other thing that's strange is that it doesn't happen when the _vertical sync_ is _enabled_.

**Comment by Yamagi** [comment]
Hi,
thank you for the demos, they make clear what's going wrong and the hint with the double jump. I have a vague idea what could be wrong (two key events with the same timestamp and maybe the same key number in different frames), but need some help to proof it. Can you add this line above *src/common/cmdparser.c* line 240: `Com_Printf("%s\n", line);`

It should look like this:
```
/* execute the command line */
Com_Printf("%s\n", line);
Cmd_ExecuteString(line); 
```

After that recompile the game and run it from terminal. It'll all raw input commands as seen by the command parser to the console and stdout. Try to reproduce and send me the full output. Thank you!

**Comment by AngryPhantom** [comment]
@Yamagi Sorry, 240 line is Cmd_ExecuteString(line); (using the master branch, not the release)

**Comment by Yamagi** [comment]
Looks like Github has some problems again. I received your comment by mail, but it doesn't show up in the web interface. :/

You'll need to add the line above the `Cmd_ExecuteString(line);` line (and below the comment). We want to print the variable `line` before it get's executed.

**Comment by AngryPhantom** [comment]
@Yamagi Do I have to rebind my left mouse button to the standard jump and test it or can I leave my "+dj" binding?

**Comment by AngryPhantom** [comment]
@Yamagi That was me actually. I deleted the comment, sorry. A bit sleepy in the morning and was searching `cmdparser.c` for the line `Com_Printf("%s\n", line);` :)

**Comment by Yamagi** [comment]
Ah, okay :) 

You can leave the "+dj" binding. In fact, I think that it is somehow related to the macro.

**Comment by AngryPhantom** [comment]
Ok, here are 3 variants for you: [one](https://hastebin.com/raw/cegavuleqe), [two](https://hastebin.com/raw/woqabuyuce) and [three](https://hastebin.com/raw/apovafuzec). Look somewhere by the end of these outputs since I stopped the game as soon as this strange behavior occurred.

**Comment by Yamagi** [comment]
That helps, thank you very much! You get a spurious key up event for the forward key, for example in the first log: `-forward 119 10453` 119 is the key and 10453 are the timestamp, in milliseconds since the game was started. This isn't caused by the macro, because movements created by macros don't have a key associated with them. And it isn't a problem with the timestamps. So the next step is to figure out why the game things that you've released the forward key. And why it doesn't happen on my box.

A last question: Can you tell me your SDL2 version? Mine is 2.0.12.

**Comment by AngryPhantom** [comment]
2.0.9 on Debian and 2.0.12 on Void Linux.

**Comment by Yamagi** [comment]
Mkay, this looks the same like that one: https://github.com/Rust-SDL2/rust-sdl2/issues/754 Not with the Rust wrapper of course, but with the plain C API. Apparently this was never reported to SDL, at least I'm unable to find a matching bug report in the SDL bugtracker. We're processing SDLs input event code at every renderframe, so every 16.6 ms at 60 FPS and every 3,33 ms at 300 FPS. I had a short look at the SDL event handling stuff. The event queue gets locked and unlocked at several places. So the working theory is a missing lock somewhere, chances hitting it are higher the more often `SDL_PeepEvents()` get's called.

I've just pushed a new branch *inputfix* with a proof if concept for a work around. I doesn't really work, the input precision is very low. I just want to see if my theory is right: https://github.com/yquake2/yquake2/tree/inputfix It'll generate a lot of output. Not only the commands, but also all key events. Can you send me the full log after your test?

There're a lot of locks in SDLs input handling. So the working theory is, that there's something wrong

**Comment by AngryPhantom** [comment]
@Yamagi Should I simply `git clone https://github.com/yquake2/yquake2/tree/inputfix` ?

**Comment by Yamagi** [comment]
No, you'll need to switch the branch. In your existing checkout: `git pull ; git checkout inputfix`

Or download the ZIP: https://github.com/yquake2/yquake2/archive/inputfix.zip

**Comment by AngryPhantom** [comment]
Again, 3 outputs: [one](https://hastebin.com/raw/qilodexopa) (somewhere near the end), [two](https://hastebin.com/raw/duvucuxabo) (should be somewhere in the beginning) [three](https://hastebin.com/raw/macadopuni) (just a lot strafe running around the map with several occasional "cases").

**Comment by Yamagi** [comment]
Hmpf. At least its not a problem at the Quake II side of things. Every key up event was generated by SDL, for example:

```
Key: 119, State: 0
-forward 119 60917
```

Key 119 is marked up (state changes to 0 -> *down* is false). The input code generates a *-forward* command and the player stops moving. The big question is, were the event comes from. Is it really an SDL bug, X.org, Linux, the keyboard... I'm somewhat out of ideas and need to think a little bit over it.

**Comment by AngryPhantom** [comment]
@Yamagi Well, I can test with different keyboards and mice. Concerning SDL, X.org, Linux all I can say is that I'm running YQuake on two very different machines: Debian (known for its pretty outdated software) and Void (rolling Linux from scratch, everything is updated as soon as any program or system library comes out). Of course, it doesn't mean that some bug can sit there for decades...

**Comment by DanielGibson** [comment]
I think testing different keyboards (and possibly mice, but as far as I understand the incorrect events come from the keyboard?) might be worth a try

**Comment by AngryPhantom** [comment]
Changed the keyboard and the mouse. The same behavior.

**Comment by DanielGibson** [comment]
Could it be that what you're seeing here has nothing to do with YQ2 or SDL, but a lack of [n-key rollover](https://en.wikipedia.org/wiki/Rollover_(key)#n-key_rollover)?
i.e. you're sometimes pressing more keys at the same time than your keyboard supports so it doesn't register all the key presses anymore? It doesn't even have to be the "global" keyboard limit (6 keys on USB keyboards), there's also lower limits within groups of keys in many keyboards.

**Comment by AngryPhantom** [comment]
@DanielGibson I'm not sure, but I have only like 2-3 keys pressed at the same time, not more actually. Well, I have no such problem in OpenArena/Quake3 at all. I'm sure, it has to do with the Q2 engine itself and I'm asking too much from you guys to go deep in the code and fix something like this (I really feel like I'm forcing you to "use a cannon to kill a fly"). So, probably we should close this. At least strafe-running and key pressing has nothing to do with this original issue. Sorry again.
