### ISSUE TITLE
Rocket Arena mod on Linux

### ISSUE THREAD

**Issue by miquecg** [yquake2/yquake2#597]
Hi,

I'm trying to make RA2 mod work with Yamagi on Linux. So far I know Yamagi on Windows is compatible with this mod, but when it comes to Linux, available binaries don't work. Probably because they were compiled for [32 bits architecture](https://github.com/yquake2/yquake2/issues/300) as others have mentioned.

Anyway, I've found this [open source port of RA2](https://github.com/packetflinger/openra2) and compiled it for x86_64. I was expecting it to work but the result is the same as with the original binaries: mod is not completely loaded. The game starts like a regular deathmatch although console background is different and I can see in the logs that arena paks were picked. When I try to bring up RA2 menu nothing happens. On Yamagi side there are no apparent errors.

So this is my question, is this even possible on Linux 64 bits?

**Comment by Yamagi** [comment]
> So far I know Yamagi on Windows is compatible with this mod, but when it comes to Linux, available binaries don't work. Probably because they were compiled for 32 bits architecture as others have mentioned.

Or because they're old build von 15 years ago, linked against libc.so.5. That's a common problem with very old binaries. :/ Since the code for the original RA2 isn't available, it'll likely never work on linux.

> Anyway, I've found this open source port of RA2 and compiled it for x86_64. I was expecting it to work but the result is the same as with the original binaries: mod is not completely loaded.

That mod isn't the original RA2, but some kind of half baked reimplementation. I was able to get it working, but only with caevats. If I start the game with `./quake2 +set game openra` it crashes somewere in the game.so. If I start a map from the command line with `./quake2 +set game openra +map q2dm1` the game starts and some kind of startup menu is shown and the cvars mentioned in the readme are available.

**Comment by Yamagi** [comment]
Forgot to mention: You could try to compile a 32 bit version of YQ2. The code is - of course - 32 bit compatible. But that will only work if RA2 is linked against libc.so.6 and not if it's too old for that. An alternative would be to try our Windows builds in Wine.

**Comment by miquecg** [comment]
Thanks for taking your time to answer :)

I'm wondering if public servers out there with arena deathmatch are running on windows or maybe a 32 bits compiled server.
