### ISSUE TITLE
no crosshair for Ground Zero mission pack

### ISSUE THREAD

**Issue by ppsspp-gamer** [yquake2/yquake2#60]
(1) no crosshair for Ground Zero mission pack, and no effect after adjusting crosshair in option menu.  
(2) it only happened for Ground Zero mission pack, no crosshair problem for both quake2 and The Reckoning mission pack.
(3) tested with 5.23 and 5.24 yquake2 win32 client.
![rogue](https://cloud.githubusercontent.com/assets/8726272/6652452/340fb07e-caaa-11e4-80cd-c776adca6afc.png)

**Comment by Yamagi** [comment]
I can't reproduce that. Can you tell me which mod you're running? The HUD looks non standard.

**Comment by ppsspp-gamer** [comment]
Thanks for the hint, I found what caused the problem. 

If I add a small mod of three crosshair TGA files, then the crosshair will disappear.

You can download the mod here (less than 1 KB) : http://www.mediafire.com/download/lo6mnzzlq7nd5pd/crosshair.pk2

**Comment by Yamagi** [comment]
I wonder why you're only seeing this issue with Ground Zero and not with the other games. Its clearly a client "problem" which should effect all game.dll. The case is: Quake 2 assumes that most graphics are in PCX format. That's hardcoded and can't be changed easily. When you select crosshair 3 the selected file is ch3.pcx. As soon as the file is actually loaded, the replacement code kicks in. But only if gl_retexturing is set. The replacement code first loads the original PCX to get it's width and height and than the replacement TGA. The replacement TGA is later scaled to the size of the PCX.

So:
- The original ch3.pcx has 8x8.
- Your ch3,tga has 32x32
- Your image is scaled down to 8x8 and the result is barley visible

You'll need to supply a ch3.pcx with 32x32. It can be actually a simple single colored file since it's only used to determine the sice. And it must be in a pakfile loaded after pak0.pak, of course.
