### ISSUE TITLE
Feature Request: Crossplatform game86.dll support

### ISSUE THREAD

**Issue by jlanzobr** [yquake2/yquake2#614]
Many old mods can only be played on Windows or through Wine due to them shipping with only a game86.dll and no equivalent .so file. If possible, please add support for these old binaries in the Linux and macOS versions of yquake2. Perhaps Wine can be leveraged for this.

**Comment by maraakate** [comment]
Not really possible, sorry.  Use Quake 2 3.24 in wine if necessary.

**Comment by DanielGibson** [comment]
One main problem with this is that it can only work if the yquake executable itself 32bit x86.
On macOS that's just not possible anymore (because they removed 32bit support) and on Linux it's not that useful because people usually use native 64bit YQ2 binaries (but on x86_64/amd64 Linux it's at least possible to run 32bit x86 binaries)

**Comment by Yamagi** [comment]
As @maraakate already said this is next to impossible. Q2 uses native code for the game and linking a Windows DLL into a Unix process won't work due to different libc implementations, calling conventions, etc. The best way is to ask the mod authors if they could release their source or at least compile it for Linux and / or Mac. Recompiling is often straight forward.

**Comment by xDShot** [comment]
Take a look on this:
https://github.com/FWGS/xash3d-fwgs
https://github.com/FWGS/xash3d-fwgs/blob/master/contrib/mittorn/README.md#using-dll-loader

These guys made mods dll loader for native clients.

**Comment by Yamagi** [comment]
If I understand it correctly xash3d is using some kind of wrapper library that allows dlopen() Windows DLLs in a Linux process of the same bit depth. There're some more wrappers out there, for example https://github.com/taviso/loadlibrary The question is, if such libraries work reliable with arbitrary DLL or if needs tweaking for every DLL. Anyways, I'm reopening this. With may look into it.

**Comment by xDShot** [comment]
@mittorn

**Comment by turol** [comment]
You could go full emulation route. This would require either integrating something like QEMU or writing your own x86 interpreter/JIT.

**Comment by mittorn** [comment]
dll loader is very simple, so maybe integrated as is on x86 platforms. it's alsopossible to integrate box86 on non-x86 ilp32 le platforms. On non-ilp32 you will need to get ilp32 engine working first, on be only full emulation possible

**Comment by mittorn** [comment]
https://github.com/FWGS/dllemu

**Comment by DanielGibson** [comment]
IIRC ARM recently announced that future ARM CPUs will be 64bit-only - so I'm not  sure that integrating a solution like box32 makes much sense at this point :-/

DOSBox should have code for running x86 code on any platform, but probably no DLL-specific code so one would have to add quite some work.. same for QEMU.
There's also https://github.com/buffer/libemu and http://www.codon.org.uk/~mjg59/libx86/ (ok, not sure how relevant the second one is). An alternative to libwine or dllemu could be https://github.com/taviso/loadlibrary but it has the same issue (no 32bit x86 emulation on 64bit platforms)

But on the Quake2 side all this isn't easy for 64bit platforms either, because pointers to structs are passed between the Q2 executable and the game DLL, and (some of) those structs *contain pointers* (=> the ones from old 32bit windows DLLs can't hold 64bit pointers needed by 64bit Yamagi Quake II), **including function pointers**.. and you'd have to rewrite (or wrap) parts of libc  that are used by game DLLs, like math functions, string functions and also `FILE` handling functions (`fopen()` etc;  used for savegames).

**Comment by mittorn** [comment]
But what if use aarch64 ilp32 target?

**Comment by DanielGibson** [comment]
Hmm.. no idea if that will be affected by arm32 being discontinued.

I also wonder how well that will be supported (on Linux) at all; the x86 equivalent ("x32") has been deprecated two years ago.

**Comment by mittorn** [comment]
x32 still supported, but abi support in kernel is only need to make syscalls with this abi. I think we can make libc/libgl shim and loader which may load ilp32 engine like it done in wine for osx (but it shims winapi, not libc). In this case no need for special support on host kernel or libc

**Comment by Yamagi** [comment]
Maybe we are thinking way to complicated. With the exception of very few mods, that won't run in YQ2 anyway, Quake II is fully network transparent. It's totally fine to run single player games in the dedicated server and save / load games through rcon. Something like this should work:

* Setup Win 98 SE in a CPU emulator like qemu or dosbox-x.
* Put a vanilla q2ded.exe in it and run the mod in it.
* Connect from the host over emulated network to the dedicated server.

That approach doesn't require any changes to YQ2, no emulation lib and has the big advantage that the game32.dll is running under a kind of 'native' Win 98 which should help the savegame problem and the often abysmal code quality, deep in the undefined territory.

**Comment by maraakate** [comment]
That's a good idea too, however I would use Win2k or later because Win98SE is so easy to take down from a rogue program.  Some mods may only work properly in SP and not Coop.  If that's the case, you may need to make an sv_ param that forces maxclients 1 and allow coop and deathmatch CVAR to be set to 0.

**Comment by mittorn** [comment]
something like this already done in old xash3d, so it's also useful idea. Also it is possible to build special x86 linux engine with loadlibrary and run in qemu

**Comment by Yamagi** [comment]
I've implement single player support into the dedicated server. When started with `+set singleplayer 1` the `deathmatch` and `coop` cvar are forced to `0` and `maxclients` is set to `0`. And I've added a little bit of documentation explaining the idea to run single player campaigns in a VM.
