### ISSUE TITLE
7.44 win bin not working

### ISSUE THREAD

**Issue by RealHelper** [yquake2/yquake2#620]
Hi,

I'm trying to upgrade 7.43 t 7.44 and Yamagi crash (go back to windows) when i try to select 'Game'.
I do a false upgrade 7.43 to 7.43 and it is working.

I tried a fresh install 7.44 not working
I tried a fresh install 7.43 it works

Regarding 7.44 each time the ID logo is working, the demo ingame is working, but with the same Game Menu crash.

Another strange thing is that all "exe, DLL and baseq2 directory" are under the 'doc' repertory, after an extraction of the 7.44 archive.

Thanks for your work ;-)

**Comment by DanielGibson** [comment]
> Another strange thing is that all "exe, DLL and baseq2 directory" are under the 'doc' repertory, after an extraction of the 7.44 archive.

And that's exactly the reason for the problems you're having, somehow the files got into the wrong places.
Can you try if the following works better for you: [quake2-7.44-fixed.zip](https://github.com/yquake2/yquake2/files/5394732/quake2-7.44-fixed.zip)
It's the files of the original quake2-7.44.zip rearranged into the proper places **plus** the ctf game.dll of 7.43 (because the 7.44 release was missing the ctf game DLL).
I hope it works, I didn't test it (I'm at my Linux machine currently)

**Comment by some0nebad** [comment]
Game crashes without any visible error when you press "Game" submenu from main menu. You can still load quicksave via F9 and play. Fix is not helping.

**Comment by robrich82** [comment]
I tried the fix as well, the Game option is broken across all expansions as well.

**Comment by DanielGibson** [comment]
Ok, thanks for testing!
Yamagi and me will fix it tomorrow (Saturday)

**Comment by Yamagi** [comment]
I wonder that happend. I used the exactly same script to build the release ZIP as I used for the test builds, which were packed right. Anyway, I've repacked it by hand and reuploaded it under the same file same: https://deponie.yamagi.org/quake2/windows/quake2-7.44.zip Thank you for telling is that we've messed up.

**Comment by RealHelper** [comment]
Hi, i test the fixed then the reack, same behaviour for me upgrade or fresh install. thanks

**Comment by Yamagi** [comment]
I know that :) I've just repacked that release, because the crash triggers only under some conditions and not always. After analysing the problem for two hours I think that we'll just revert the mod submenu and redo the whole release without it. There're several bugs in the path finding magic under windows (read: `Sys_FindFirst()' behaves different than under Unix) and fixing them has a very high probability of breaking other things. Just let me speak with @DanielGibson first, sometime later today.

**Comment by Yamagi** [comment]
Okay, let's forget about 7.44. It never happend... 7.45 is here: https://deponie.yamagi.org/quake2/windows/quake2-7.45.zip It's repacked and the crash when entering the game menu is fixed.
