### ISSUE TITLE
yquake2 overwrites mod config file with config from base game

### ISSUE THREAD

**Issue by warrex1979** [yquake2/yquake2#630]
It is already annoying that there is no way to bind weapons/items to keys within the game but why does yquake2 not respect the last configuration when accessing a mod via the in-game menu? It always overwrites the mod's config file with the config from the base game. This also means that e.g. all of Ground Zero's weapons/items are unbound.

I do know that I can directly launch mods with "+set game" but what is the point of the menu then?

**Comment by Yamagi** [comment]
Hmm... I'm not really able to reproduce this. The mod submenu is just a wrapper around the `game` cvar, typing `game xatrix` into the console is the same as selecting xatrix in the menu. Starting the game with `+set game xatrix` is somewhat different, because baseq2 never gets loaded.

If I do something like `game xatrix`, `bind r use Phalanx`, `quit` the binding is written to the config file and read back after a restart and another `game xatrix`. The binding doesn't get written if I switch to another game, something like `game xatrix`, `bind r use Phalanx`, `game baseq2`, `quit`. That's because configs are only written on client shutdown. I'll push a fix for that shortly.

Before I poke deeper: Do you have the latest Vulkan testbuild or the 7.45a rebuild? The openal32.dll included in the first Vulkan test build and 7.45 without a had a bug causing crashes at client shutdown. That might keep the configs from getting written.

**Comment by warrex1979** [comment]
Can't wrap my head around what you wrote right now. I am using this: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-vulkan-20201130-d4d61d0.zip

**Comment by Yamagi** [comment]
Mkay. I gave it a try on Windows. And I'm not able to reproduce it: Start yquake2.exe -> `game xatrix` -> `bind r use Phalanx` -> `quit` -> The binding is written to the config -> Start yquake.exe -> `game xatrix` -> `bindlist` -> The binding is read from config.

Maybe my fix in e86a678 was enough. Can you give it a try with the latest test build? Thank you! https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-vulkan-20201212-b7bdd0b.zip

**Comment by Yamagi** [comment]
Stale for 4 weeks -> Closing. Feel free to reopen if you have questions or new informations.
