### ISSUE TITLE
sound "is a stereo sample"

### ISSUE THREAD

**Issue by BenzoSt** [yquake2/yquake2#641]
I'm using the Quake 2 Heavy Metal mod which includes stereo sounds. However, these sounds aren't audible in Yamagi, and I get messages "so-and-so sound is a stereo sample".

**Comment by Yamagi** [comment]
Yeah, YQ2 - like Vanilla Q2 - doesn't support stereo samples. And it's not really usefull to add for them, because the game does the spartializing by itself to position everything that's not background music on a 2D plane. Feeding stereo samples into OpenAL wouldn't be too hard, as far as I know OpenAL accepts stereo samples just fine and playes them without spartializing. But adding them to the classic sound system would be a lot of work.

If someone wants to do it (read: a pull request would be welcome) they need to add decoding of stereo samples to the wave decoder and stereo sample support for both sound systems.

**Comment by DanielGibson** [comment]
The only sounds this *could* make any sense at all are ones that don't have a position in the world but belong to the player, like that notification sound, the players own footsteps/grunting/screaming and the players own weapons.
But I don't think it's worth it.

OpenAL also only allows stereo samples for such non-spatialized sounds.

**Comment by 0lvin** [comment]
@BenzoSt Could you please  check with a613932? 
Some time it is played some noise, but i am not sure that it expected or need more deep changes in sound system.

**Comment by 0lvin** [comment]
Sound with changes and without real stereo tracks:
[![yquake2: Vulkan render with stereo sound support](http://img.youtube.com/vi/lJprkub9xVY/0.jpg)](http://www.youtube.com/watch?v=lJprkub9xVY)

Sound with changes and with real stereo tracks and without OpenAL:
[![yquake2: Vulkan render with Heavy Metal mod(without OpenAL)](http://img.youtube.com/vi/KRzLRtVNPt4/0.jpg)](http://www.youtube.com/watch?v=KRzLRtVNPt4)

Sound with changes and with real stereo tracks and with OpenAL:
[![yquake2: Vulkan render with Heavy Metal mod (with OpenAL)](http://img.youtube.com/vi/xB9GEm2K8YA/0.jpg)](http://www.youtube.com/watch?v=xB9GEm2K8YA)
