### ISSUE TITLE
Windows: vulkan renderer,  fullscreen changed to 0  when switching to desktop via CONTROL+ ESC

### ISSUE THREAD

**Issue by j4reporting** [yquake2/yquake2#647]
System is windows 10 using latest  pre 8.0 build from Jan 13. 
 Intel iGPU Iris 540 (Skylake)  

`Vulkan API: 1.2
Header version: 148
Devices found:
   #0: Intel(R) Iris(R) Graphics 540
Using device #0:
   deviceName: Intel(R) Iris(R) Graphics 540
   resolution: 2560x1440
   driverVersion: 1647081 (0x1921E9)
   apiVersion: 1.2.148
   deviceID: 6438
   vendorID: 0x8086 (Intel)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
   gfx/present/transfer: 0/0/0
Present mode: VK_PRESENT_MODE_FIFO_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
Enabled layers: 
Reallocate space for 512 models.
Successfully initialized Vulkan!
Successfully loaded ref_vk.dll as rendering backend.
`

by trying to switch back to Desktop ( Control + ESC ) and leaving yquake2 running off-screen, the vid_fullscreen variable changes to 0 as well.
Using the GL1 or GL3 renderer this works as expected.

EDIT:  s/fullscreen/vid_fullscreen/

**Comment by Yamagi** [comment]
I cannot test it right now, but this may be fixed in the latest build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210310-2a18f02.zip

**Comment by j4reporting** [comment]
I was about to give an update on this. unfortunately it's got worse.  With SDL2.12  vulkan renderer now crashes when switching to desktop by either  ALT+TAB, left window key  or CTRL + ESC.

Faulting application name: yquake2.exe, version: 0.0.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.18362.1411, time stamp: 0x9ace5a5f
Exception code: 0xc0000005
Fault offset: 0x0004dbcd
Faulting process id: 0x269c
Faulting application start time: 0x01d715bdcb7b1d81
Faulting application path: E:\GOG Games\yquake2_pre\yquake2.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: aca9f18f-2473-4f35-9c49-b16037ebc4fb
Faulting package full name: 
Faulting package-relative application ID: 


Now the interesting part.  Using SDL2.14  prevents the crash, but the desktop is not restored properly. The desktop does not switch back to full desktop resolution (in case game resolution differ)  and the game 'screen' is still visible, just the taskbar and the application window selected by alt+tab is shown.

![yquake2_and_sdl2 14](https://user-images.githubusercontent.com/45177907/110650842-30a63b00-81bb-11eb-9021-bcba47b36bbe.png)



The GL3 renderer is affected here too.  I observe the same thing with other games like vkquake or quakespasm when using SDL2.14. So this might be a bug in SDL2.14  or a change from 2.12 to 2.14.

**Comment by j4reporting** [comment]
I can also force a crash in vid_fullscreen 0 mode  by minimizing  the yquake2 window. 

info from stdout.txt  same log as with vid_fullscreen 1   and switching to desktop with alt  tab

QVk_BeginFrame(): received VK_SUBOPTIMAL_KHR after vkAcquireNextImageKHR - restarting video!
Shutting down Vulkan
Enabled extensions: VK_KHR_surface VK_KHR_win32_surfac

here's  the vk_strings output from stdout:
Vulkan API: 1.2
**Header version: 148**
Devices found:
   #0: Intel(R) Iris(R) Graphics 540
Using device #0:
   deviceName: Intel(R) Iris(R) Graphics 540
   resolution: 2560x1440
   driverVersion: 1647081 (0x1921E9)
   **apiVersion: 1.2.148**
   deviceID: 6438
   vendorID: 0x8086 (Intel)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
   gfx/present/transfer: 0/0/0
Present mode: VK_PRESENT_MODE_FIFO_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
Enabled layers: 
Reallocate space for 512 models.
Successfully initialized Vulkan!
Successfully loaded ref_vk.dll as rendering backend.

**Comment by Yamagi** [comment]
Hmpf. I can't reproduce it under Linux. I'll have a look under Windows early next week. I don't have time before that. :/

**Comment by j4reporting** [comment]
yeah it sucks.  One more info, using my own build  (MSYS2  vulkan headers 168)  the game catches the error and exits / test with minimizing game window

stderr:   Error: Unable to restart Vulkan renderer

stdout: 
QVk_BeginFrame(): received VK_SUBOPTIMAL_KHR after vkAcquireNextImageKHR - restarting video!
Shutting down Vulkan
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 0x0
...trying swapchain image format: 44
QVk_Init(): Could not create Vulkan swapchain: VK_ERROR_OUT_OF_HOST_MEMORY
Shutting down curl.
Shutting down OpenAL.
Shutting down input.
Shutting down Vulkan
recursive shutdown


the only difference is a more newer build env. No other changes.

**Comment by j4reporting** [comment]
Is it really necessary to restart the VK renderer when game was minimized? The GL3 renderer is not restarted.
The problem here seems to be that in QVk_CreateSwapchain() 
the line  `VkExtent2D extent = surfaceCaps.currentExtent;`  does not return anything useful after window was minimized.

`...trying swapchain extent: 0x0`

Maybe we should check if window is minimized and delay the render restart, if such restart is really necessary.

Vkquake2 seems to restart the render only when using Vulkan fullscreen exclusive mode. This mode is not implemented in yq2's Vulkan renderer.
Otherwise, it looks like the vkquake2 renderer is not restarted when switching between desktop and non-exclusive fullscreen 
mode via ALT + TAB.  But vkquake2 does not use SDL.

**Comment by Yamagi** [comment]
Okay, these are two bugs. The first one is - like you said - something in SDL on Windows. Again. I don't known how many SDL bugs we found over the years and most of them get ignored by the upstream project. In the unlikely case that I ever start another sourceport, I will not use SDL for the Windows port. I'll revert to SDL 2.0.12 for the next test build.

The second one looks related to the `vid_fullscreen 1` bug. When anything changes with the window, the Vulkan render context blows up. The renderer detects that and either messes up the restart (there're still calls into the inconsistent renderer that crash the yquake2.exe process) or the video driver fails as soon as the renderer tries to reinitialize after the restart. This may be somehow related to the 'Mod_PointInLeaf error' mentioned in #676. This is - again - something where someone with Vulkan knowledge needs to look into.

**Comment by j4reporting** [comment]
you test builds are still using SDL2.0.12.  I did  just some tests with SDL2.0.14.  And it seems like Linux (at least with KDE) is affected here as well. 

Might be some driver limitations. I see vkquake2 (exclusive full screen)  waiting with the renderer restart until screen is selected/visible again.

**Comment by Yamagi** [comment]
Ah, yes. I've updated my test installtion on Windows to SDL 2.0.14 as soon as it was released, but so far haven't copied the new SDL2.dll into to test builds.

**Comment by j4reporting** [comment]
in SDL2.0.14 the default value for SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS  changed from 1 to 0.

just verified this with my build 
`set  SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS=1`

This has been marked as bug and added to the 2.0.16 milestone

**Comment by Yamagi** [comment]
I've added an explicit `SDL_SetHint()` call to force SDL_HINT_VIDEO_MINIMIZE_ON_FOCUS_LOSS to 1. That enforces the SDL 2.0.12 behavior without user interaction.

And I've pondering about the Vulkan restart problems. Part of the problem was, that there were calls into the renderer after it's render state got corrupted somehow. @rg3 added code to restart the renderer in place, as soon as the corruption is detected. Which is a nice and correct solution for the problem. But sometimes these inplace restarts get messed up. It look like the problems depend on the GPU driver, with my Nvidia card things seem to work fine and with AMD under Windows things tend to go wrong. My educated guess is, that the renderers shutdown sequence leaks some resources, the driver runs out of them and crashes or errors out. We can try to find theses leaks or whatever it is and solve them. Or we revert that part and add code to `R_BeginFrame()` that checks if the renderer requested a restart.

**Comment by Yamagi** [comment]
I found it. Or at least one serve bug in the whole re-initialization process: When the renderer detects a state inconsistency `QVk_Restart()` is called. That one calls `QVk_PostInit()` which in turn calls `Mod_Init()`. `Mod_Init()` sets `models_known = NULL`, but `models_known` was allocated by `malloc()` in vk_model.c:115. According to Address sanitizer this leaks 311296 bytes. After that `Mod_Reallocate()` is called, which allocates a new `models_known`. Models loaded before this new allocation are still referenced in the **old** `models_known` array, models loaded after this point are referenced in the **new** `models_known`. To make things worse models are sometimes referenced in both arrays. Part of the code works with old references, part of the code with new references. At best this ends with 'ERROR: Mod_PointInLeaf: bad model'.

The world model (the map) is always in the old `models_known`, because it's only loaded once when the client calls `RE_BeginRegistration()`.

**Comment by rg3** [comment]
Hey, thanks for debugging this and sorry for not commenting earlier. I had already started analyzing the "bad model" error reaching similar conclusions and taking a look at the original fix from vkQuake2. Basically, I'll need to change the renderer restart moment from BeginFrame to EndFrame, and also indicate to the server, like vkQuake2 does, that the client needs registration again. This will avoid the "bad model" error.

Second, thanks for noticing the leak, which had gone unnoticed to me. I'll fix both issues at the same time. Having a clean state of stuff so we can restart the Vulkan renderer quickly without completely shutting down the whole thing will pave the way for simplifications in the Vulkan part. We'll be able to cut down on the number of pipelines and combinations of state and just have what the settings indicate. If anything changes that forces a modification of that state, we can just restart the Vulkan part on the fly.

**Comment by Yamagi** [comment]
> Hey, thanks for debugging this and sorry for not commenting earlier.

No problem.

>  Basically, I'll need to change the renderer restart moment from BeginFrame to EndFrame, and also indicate to the server, like vkQuake2 does, that the client needs registration again.

If this changes the client <-> renderer interactions in an incompatible way the API version in ref.h must be bumped.

> Second, thanks for noticing the leak, which had gone unnoticed to me. I'll fix both issues at the same time. Having a clean state of stuff so we can restart the Vulkan renderer quickly without completely shutting down the whole thing will pave the way for simplifications in the Vulkan part. We'll be able to cut down on the number of pipelines and combinations of state and just have what the settings indicate. If anything changes that forces a modification of that state, we can just restart the Vulkan part on the fly.

That sounds like a good plan.

**Comment by Yamagi** [comment]
This should be fixed with latest test build: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210407-26bda18.zip

**Comment by j4reporting** [comment]
it's not fixed. game still crashes when window was minimized.

**Comment by Yamagi** [comment]
Mkay. We were able to reproduce the crash on Daniels Radeon 580 under Windows 10. There're two bug that cause the crash:
1. Missing code guards that prevent calls into the renderer when the renderer state is inconsistent.
2. The restart logic is still buggy, the client does a full restart when the renderer requests a partial restart.
A very hacky proof of concept fix for both problems is under https://github.com/yquake2/yquake2/commits/restarthacks. With the fix applied we're able to minimize the game under Windows and to alt-tab out of the fullscreen window without crashing. A correct fix will need a renderer API change, it'll take a few days to come up with that.

**Comment by Yamagi** [comment]
Another build to test: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-rendererrestart-20210411-ef248cb.zip

This build adds some code guard to the 2D draw functions (for the HUD, menu, console, etc.) that were present in vkQ2 and for some reason missing in our code. They prevent several possible crashes when the Vulkan state gets broken during a frame. For example when the window is minimized.

And it adds the promised renderer restart API. Until now the renderers abused the `vid_fullscreen` cvar to communicate restart intends to the client. That made the `vid_fullscreen` and `r_mode` cvars special, changes to them got applied immediately. After the change the renderers can call a function `ri.Vid_RequestRestart()` to request either a full or a partial restart. That simplifies things a lot. `vid_fullscreen` and `r_mode` are now normal cvars that are applied after an explicit `vid_restart`, that allows moving the fullscreen and mode setting handling completely out of the renderer. Which in turn should make things more robust.

With both changes together we're able to minimized the YQ2 windows and to alt-tab out of both the native fullscreen and the fullscreen window without crashes. Tested on Win 10 with AMD and Nvidia. Can you give a try? Since the graphics driver is a big factor, I can't promise that it'll work you.

**Comment by j4reporting** [comment]
Unfortunately game is still crashing using an Intel GPU. 
Current system is WIn10 20H2  / GFX driver version 27.20.100.9316

stderr:  Error: Unable to restart Vulkan renderer
stdout: 
```
------------------------------------
Vulkan API: 1.2
Header version: 148
Devices found:
   #0: Intel(R) Iris(R) Graphics 540
Using device #0:
   deviceName: Intel(R) Iris(R) Graphics 540
   resolution: 1920x1080
   driverVersion: 1647716 (0x192464)
   apiVersion: 1.2.167
   deviceID: 6438
   vendorID: 0x8086 (Intel)
   deviceType: VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
   gfx/present/transfer: 0/0/0
Present mode: VK_PRESENT_MODE_FIFO_KHR
Swapchain image format: 44
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
Enabled layers: 
Reallocate space for 512 models.
Successfully initialized Vulkan!
Successfully loaded ref_vk.dll as rendering backend.
------------------------------------
.
.
Number of OpenAL sources: 31

Sound sampling rate: 0
------------------------------------

QVk_BeginFrame(): received VK_SUBOPTIMAL_KHR after vkAcquireNextImageKHR - restarting video!
Shutting down Vulkan
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 0x0
...trying swapchain image format: 44
QVk_Init(): Could not create Vulkan swapchain: VK_ERROR_OUT_OF_HOST_MEMORY
==== ShutdownGame ====
Shutting down curl.
Shutting down OpenAL.
Shutting down input.
Shutting down Vulkan
recursive shutdown
```

**Comment by Yamagi** [comment]
Okay, the good news is that we solved the crash. The bad news is that we're now triggering another problem in the Intel Vulkan driver. Since the driver was able to build a Vulkan context at client start, my educated guess is that we're eitherleaking resources at restart or that something doesn't get reinitialized. This is something that someone with at least basic Vulkan knowledge must look into. Maybe @0lvin or @rg3.

The Error messages comes from vk_swapchain.c line 224.

And there at least one leak detected by asan. I don't know if it's the culprit:

```
Direct leak of 224 byte(s) in 2 object(s) allocated from:
    #0 0x7f21cf77f459 in __interceptor_malloc /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f21af80281a  (<unknown module>)
    #2 0x7f21afe5a2f5 in CreateDynamicBuffers src/client/refresh/vk/vk_common.c:1011
    #3 0x7f21afe67528 in QVk_Init src/client/refresh/vk/vk_common.c:2014
    #4 0x7f21afeafd5e in RE_InitContext src/client/refresh/vk/vk_rmain.c:1582
    #5 0x560394f18d1a in GLimp_InitGraphics src/client/vid/glimp_sdl.c:602
    #6 0x7f21afeac970 in Vkimp_SetMode src/client/refresh/vk/vk_rmain.c:1235
    #7 0x7f21afeace49 in R_SetMode src/client/refresh/vk/vk_rmain.c:1276
    #8 0x7f21afead06e in RE_Init src/client/refresh/vk/vk_rmain.c:1322
    #9 0x560394f252f0 in VID_LoadRenderer src/client/vid/vid.c:432
    #10 0x560394f25743 in VID_CheckChanges src/client/vid/vid.c:491
    #11 0x560394f25886 in VID_Init src/client/vid/vid.c:555
    #12 0x560394e88704 in CL_Init src/client/cl_main.c:903
    #13 0x560394f48fda in Qcommon_Init src/common/frame.c:361
    #14 0x560394fd99fb in main src/backends/unix/main.c:145
    #15 0x7f21cf225b24 in __libc_start_main (/usr/lib/libc.so.6+0x27b24)
```

**Comment by turol** [comment]
I don't see a `vkResetDescriptorPool` call anywhere and there's only `vkDestroyDescriptorPool` in `QVK_Shutdown` (on latest `master` branch). The descriptor sets should be destroyed when the pool is destroyed so somehow you're missing that.

**Comment by j4reporting** [comment]
I can restart the vk renderer many times in using console w/o any problems, This cannot be the real issue here. Besides 224 bytes is not much. 
Here's  what happens if I try to start the game minimized  with a command like  `start /min  yquake.exe <options>`.
Game was configured to 1920x1080  vid_fullscreen 0.  
Game created a visible window with 640x480 resolution 

```
----- refresher initialization -----
Loading library: ref_vk.dll
Byte ordering: little endian

Refresh: Yamagi Quake II Vulkan Refresher (based on vkQuake2 v1.4.3)
Client: 8.00pre

Setting mode 21: 1920x1080 (vid_fullscreen 0)
Real display mode: 2560x1440@60
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 0x0
...trying swapchain image format: 44
QVk_Init(): Could not create Vulkan swapchain: VK_ERROR_OUT_OF_HOST_MEMORY
RE_InitContext() - could not initialize Vulkan!
R_SetMode() - invalid mode
Setting mode 4: 640x480 (vid_fullscreen 0)
Shutting down Vulkan
Real display mode: 2560x1440@60
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 640x480
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
MSAAx1 is used...
...created 3 Vulkan render passes
...created Vulkan command pools
...created world depth buffer
...created UI depth buffer
...created world color buffer
...created world postpocess color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan commandbuffers

```

I would guess the problem here is the minimized window.  Like in the log from March 11th  window dimensions are **0x0**. I checked vkquake  and vkquake2  and it seems that renderer is only restarted when window is not minimized anymore.

**Comment by Yamagi** [comment]
Mkay. I got myself a box with an Intel GPU and gave it a try. After about one hour of debugging I finally understand what's going on. First there's the problem that the client might try to shutdown the renderer after `QVk_Shutdown()` was already called. This isn't a problem on Nvidia, on Intel the GPU driver crashes. It isn't too hard to hack around that. I'm not 100%, but fixing that problem might solve the remaining 'bad model' errors after restarts.

The 'VK_ERROR_OUT_OF_HOST_MEMORY' is caused by a swapchain extend of 0x0. When the window is minimized (not maximized!) the Vulkan state gets corrupted and the renderer tries to restart itself. During the restart `vkGetPhysicalDeviceSurfaceCapabilitiesKHR()` returns an `surfaceCaps.currentExtent` of 0x0. The code doesn't handle that case, it puts that extent into an `VkSwapchainCreateInfoKHR` and passes that to `vkCreateSwapchainKHR()` which fails with 'VK_ERROR_OUT_OF_HOST_MEMORY'. 

While it's possible to fix that problem, it introduces another one. As long as the window is minimized, the Vulkan is detected as corrupted in every frame. I wonder if it wouldn't be easier if we handle minimized windows in the client. Something like not calling the renderer when the window is minimized.

**Comment by turol** [comment]
According to the Vulkan spec section 33.9:
> On some platforms, it is normal that maxImageExtent may become (0, 0), for example when the window is minimized. In such a case, it is not possible to create a swapchain due to the Valid Usage requirements.

So it appears that this is "normal" and in this case we can't create a swapchain and therefore should not do anything. I think `RE_BeginFrame` should check for this and if so set a flag so that all other rendering functions will silently return for this frame.

**Comment by Yamagi** [comment]
Thank you for the hint, @turol . I've implemented this and fixes for some other init / restart / shutdown bugs I stumpled over while debugging in the vulkanrestart2 branch: https://github.com/yquake2/yquake2/compare/vulkanrestart2 It seems to work, I'm able to minimize and maximize the windows without the renderer crashing or something like that. Of course it's just a hack. The client shouldn't call into the renderer at all, as long as the window is minimized or hidden.

This bug, the 24 comments, all the problem I've found while debugging and the hopefully final hack shows that it was a bad idea trying to port Q2 to Vulkan. It's properly the same with the RTX renderer. Q2 was released in 1997 and it's internal architecture doesn't match with the requirements of modern render APIs. The client must process a minimal amount of render frames, otherwise the game doesn't work. There're renderer calls throughout the code, making it hard to split the render frame into a 'prediction frame' and a 'render dll is called frame'. There's no clean way to abort a frame. The renderer cannot request the reupload of assets. And so on. vkQuake2 and Quake II RTX can work around that by hacking the client, for YQ2 that isn't an option. We want so support multiple renderers, mods compiled in the late 1990th, etc. And we don't want to introduce new bugs by avoidable architectural changes.

That said, let's hope that this was the last bigger restart bug. If not we'll to reconsider if we'll ever be able to hack the Vulkan renderer to be 100% reliable on YQ2. And if we're are able to support it in the long term.

I'll test my branch on some other GPUs and driver. If evenrything seems to work I'll upload another test build early next week.

**Comment by j4reporting** [comment]
that's a big progress. 
I cannot reproduce crash with  vid_fullscreen 0 
but vid_fullscreen 1  + alt-tab   throws  a new error when restoring game window/screen 

`Error: QVk_BeginFrame(): unexpected error after vkAcquireNextImageKHR: VK_TIMEOUT
`

**Comment by Yamagi** [comment]
I don't see that on my box. To be sure: You have SDL 2.0.14 and the window minimizes at alt-tab?

**Comment by j4reporting** [comment]
yes it's SDL 2.0.14.  Game minimizes  at  alt+tab / left windows key / CTRL + ESC  and  is waiting for to be restored.   

verified on two different systems  HD530  / Iris 540  with different Intel driver versions.

this was also recorded in stdout

`
==== Yamagi Quake II Initialized ====

*************************************

[0.0.0.0]:0: client_connect
==== ShutdownGame ====
Server was killed.
QVk_BeginFrame(): received VK_SUBOPTIMAL_KHR after vkAcquireNextImageKHR - restarting video!
Shutting down curl.
Shutting down OpenAL.
Shutting down input.
Shutting down Vulkan
recursive shutdown
`

**Comment by 0lvin** [comment]
[VK_SUBOPTIMAL_KHR](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkResult.html) looks as successful result, and can be used in future interaction.

**Comment by Yamagi** [comment]
The question is why we're shutting down. Like the log says, `VK_SUBOPTIMAL_KHR` will abort the frame and request a renderer restart at either end of the current frame or the beginning of the next frame. Let's see what happens when we restart at `VK_TIMEOUT`. May lead to a restart loop: c5d9b43fbc5533e62ba0612f795547ba11d07906

**Comment by 0lvin** [comment]
> VK_SUBOPTIMAL_KHR A swapchain no longer matches the surface properties exactly, but can still be used to present to the surface successfully.

I suppose should be:
```diff
- if (result == VK_ERROR_OUT_OF_DATE_KHR || result == VK_SUBOPTIMAL_KHR || result == VK_ERROR_SURFACE_LOST_KHR || result == VK_TIMEOUT)
+ if (result == VK_ERROR_OUT_OF_DATE_KHR || result == VK_ERROR_SURFACE_LOST_KHR || result == VK_TIMEOUT)
....
-else if (result != VK_SUCCESS)
+else if (result != VK_SUCCESS && result != VK_SUBOPTIMAL_KHR) 
```

**Comment by j4reporting** [comment]
on the system with Iris 540 GPU  I see this in stdout.  If you configure    r_mode  <  desktop resolution, then you"ll see the system switching desktop to game resolution but the switch to game window will never happen. 

sometimes it looks like this in std.out:  (Iris 540)

`
QVk_BeginFrame(): received VK_SUBOPTIMAL_KHR after vkAcquireNextImageKHR - restarting video!
Shutting down OpenAL.

------- sound initialization -------
Loading library: openal32.dll
...opening OpenAL device: ok
...creating OpenAL context: ok
...making context current: ok

OpenAL settings:
AL_VENDOR: OpenAL Community
AL_RENDERER: OpenAL Soft
AL_VERSION: 1.1 ALSOFT 1.21.1
AL_EXTENSIONS: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_EXT_SOURCE_RADIUS AL_EXT_STEREO_ANGLES AL_LOKI_quadriphonic AL_SOFT_bformat_ex AL_SOFTX_bformat_hoa AL_SOFT_block_alignment AL_SOFTX_callback_buffer AL_SOFTX_convolution_reverb AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_direct_channels_remix AL_SOFT_effect_target AL_SOFT_events AL_SOFTX_filter_gain_ex AL_SOFT_gain_clamp_ex AL_SOFT_loop_points AL_SOFTX_map_buffer AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length AL_SOFT_source_resampler AL_SOFT_source_spatialize

Available OpenAL devices:
- OpenAL Soft on BenQ EX3203R (Intel(R) Display Audio)
- OpenAL Soft on Headphones (Realtek High Definition Audio)

Current OpenAL device:
- OpenAL Soft

Number of OpenAL sources: 31

Sound sampling rate: 0
------------------------------------

==== ShutdownGame ====
Shutting down curl.
Shutting down OpenAL.
Shutting down input.
Shutting down Vulkan
recursive shutdown
`

**Comment by j4reporting** [comment]
ok, the line  `QVk_BeginFrame(): received VK_SUBOPTIMAL_KHR after vkAcquireNextImageKHR - restarting video!` 
is already logged when I switch back to desktop.  
But with latest commit applied  I can restore game screen successfully.

**Comment by Yamagi** [comment]
So it works now? With my change or with @0lvins change?

**Comment by j4reporting** [comment]
with your change,  Did not try 0lvin's change yet.  It takes some time and in the end code restarts the vk renderer. 
Shouldn't the code maybe check for vid_fullscreen == 1 and restart the renderer right away?
I understand on your system this worked before without this change?  May I ask what CPU/GPU this is?

`QVk_BeginFrame(): received VK_TIMEOUT after vkAcquireNextImageKHR - restarting video!
Shutting down Vulkan
Enabled extensions: VK_KHR_surface VK_KHR_win32_surface 
...created Vulkan instance
...created Vulkan surface
...found 1 Vulkan-capable device(s)
Supported present modes: VK_PRESENT_MODE_IMMEDIATE_KHR VK_PRESENT_MODE_FIFO_KHR 
...using present mode: VK_PRESENT_MODE_FIFO_KHR
...trying swapchain extent: 2560x1440
...trying swapchain image format: 44
...created Vulkan swapchain
...created synchronization objects
MSAAx1 is used...
...created 3 Vulkan render passes
...created Vulkan command pools
...created world depth buffer
...created UI depth buffer
...created world color buffer
...created world postpocess color buffer
...created 2 Vulkan image view(s)
...created 2 Vulkan framebuffers
...created 2 Vulkan commandbuffers
Reallocate space for 512 models.
Map: base2
 `

**Comment by Yamagi** [comment]
Yes, it indeed worked right away and so far I was unable to trigger the `VK_TIMEOUT`. It's an Intel 620 GPU with some Coffee Lake Core i5 CPU. Latest drivers as of yesterday. I'm not at home right now, I can look up the exakt version tomorrow morning. There's one obvious difference: I've updated the build env (`pacman -Syu` twice, once for the MSYS2 runtime and once for the packages) to get the latest Vulkan headers.

> It takes some time and in the end code restarts the vk renderer.

Maybe the game is waiting for the timeout. The timeout is `UINT32_MAX`, that are 4294967295 nanoseconds == 4.2 seconds, which looks way too high: https://github.com/yquake2/yquake2/blob/vulkanrestart2/src/client/refresh/vk/vk_common.c#L2074

**Comment by Yamagi** [comment]
Anyways, I'll have another look at the timeout and add some logic against restart loops. I'll also incooperate the suggestion @0lvin made.

**Comment by j4reporting** [comment]
0lvin's change works too, but  it fails to switch desktop to game resolution on the first attempt.  It looks similar to the old  7.x  vid_fullscreen 1  but with the windows desktop as background.  I need to minimize window again, and then restore window a second time to get the expected result.    

I also have here a system with UHD620 ( some I5-8xxx  I think with win10 enterprise )  I could test on later.

**Comment by j4reporting** [comment]
Timeout:  yes that was also my impression and indeed reducing the timeout to half  already makes for  a much better experience. 
  
I guess for some reason on this older systems (Skylake)  the current implementation needs to run into the timeout first. Binaries were compiled  using  a  current MSYS2  system.

**Comment by Yamagi** [comment]
Another round of changes:

* 3100feec740fe9e3a8fd57b4114ef179600b44b2: Lower the timeout to 500 milliseconds. To my understanding it should be high enough to avoid problem with vsync, getting scheduled away, etc. If not we can bump it again to something higher.
* 5940a1e4f32362597842370842b22353601ae772: Prevent restart loops.

VK_SUBOPTIMAL_KHR still triggers a restart. Otherwise we might end up with a wrong viewport or something like that.

**Comment by j4reporting** [comment]
no issues with latest commits. Looks good.

> Yes, it indeed worked right away and so far I was unable to trigger the VK_TIMEOUT. 

Did you test on a multi-monitor setup?  I can reproduce the VK_TIMEOUT  on a UHD620 with `d226dea` in a single display setup (laptop).  No VK_TIMEOUT if I configure vid_fullscreen 1  with screen index 1 or 2  on a multi-monitor setup.

**Comment by Yamagi** [comment]
All my tests were with only one display.

**Comment by Yamagi** [comment]
Here is another testbuild with these changes included: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210430-2e8e608.zip
