### ISSUE TITLE
Set basedir to accurately reflect where files are located

### ISSUE THREAD

**Issue by jjbarr** [yquake2/yquake2#664]
On most Unix systems, if you launch yamagi-quake2 its cwd won't be meaningful by default. This isn't necessarily a problem, but many mods either assume that 1) cwd is your quake 2 folder, or 2) basedir is your quake2 folder. Since basedir defaults to ., these amount to the same thing most of the time. 

Right now, I believe there is no actual way for a mod to correctly determine the basedir in yquake2. This is relevant because this is actually something a lot of mods try to do: they want to do file I/O on their directory.  Barring system locations, the options for basedir on unix are cwd, a user-specified location, or ~/.yq2. I suggest we actually set basedir based on where files are found, so that mods have at least some way to locate things.

**Comment by Yamagi** [comment]
> they want to do file I/O on their directory

They shouldn't do that. The VFS is there for a reason. I known, I'm 24 years late to complain...

The search path magic is already rather complicated. The base search path fs_cddir -> SYSTEMDIR -> basedir -> binary dir -> cfgdir. The mod specific search path (that's everything which is not baseq2) is added in front of it. It's determined from either the ` fs_gamedirvar` cvar or the `game` cvar send by the server and the directories in the base search path. The mod can be in any of these directories, in theory it can even be splitted between them. The game dll is special, it must be in a subdirectory next to the quake2 binaries. Other places may work by luck, but that's not supported.

That `-basedir` defaults to `.` is actually a feature. It allows people with distro wide installations to do crap like: `cd /path/to/custom/gamdata ; quake2`

So, what would be a meaningful dir to change the cwd to? I'm not sure if that can be decided, because the mods game data can be in any of the search path dirs. And we don't know how the assets are called, so something like 'the dir with pak0.pk2' won't work.

**Comment by jjbarr** [comment]
That's the same question I had, actually, when thinking about this.

Unfortunately, the conclusion I came to is that while there are several solutions that might be *good enough*, there is no solution that's actually that good...

It's possible that the "fix" is that there isn't a fix and the users will have to cd to the correct location themselves, which is where we are now.

I guess I'm closing this, then...
