### ISSUE TITLE
Vulkan: CurvedPNTriangles tessellation 

### ISSUE THREAD

**Issue by 0lvin** [yquake2/yquake2#686]
What do you think about tessellation for modes?

It looks promising from presentation: http://alex.vlachos.com/graphics/CurvedPNTriangles.pdf and [tessellation example](https://github.com/SaschaWillems/Vulkan/blob/master/examples/tessellation/tessellation.cpp).

**Comment by DanielGibson** [comment]
The paper is from 2000 so it doesn't have anything to do with tesselation shaders.
If you wanna do anything like this (I personally think it's as pointless as high-res texture packs), it should be done in software (i.e. upload the "upscaled" model to the GPU instead of using shaders) and work with all renderers (at least all HW accelerated ones).

**Comment by Yamagi** [comment]
Not that I'm against the change. But wouldn't it be better to fix the remaining Vulkans bugs and ship a release with the renderer before adding more features?

**Comment by 0lvin** [comment]
Could you please tag critical bugs for release with some tag / or have some issue with list of critical issues with check boxes?

Like if user uses custom model, do we need to fix such issue before release? 

We have:
#673 - semiofficial texture issue - looks like critical for release.
#670 - models has bigger then limit of triangles - looks as minor bug
#669 - hand is not rendered with custom model - looks as minor bug
#662 - looks as fixed by #681
#651 - require rewrite shaders, i am not sure that it can be fast. So it would be nice but ....
#680 - vulkan restart issue, i have not found where it is mentioned initially(#505 ?). I have never experienced with such but looks critical.

Have I missed some issues?

**Comment by Yamagi** [comment]
* I would agree that #673 is critical. It sound like it could happen with any texture, at least in theory.
* #670 and #669 are minor, custom models were always problematic.
* #662 is indeed fixed. I'll close the issue.
* #651 is a long term project and only to have, not critical for release.
* #680 might be fixed by #680. I'll finally test and likely merge that later today.

So if we could get #673 fixed I would be happy. :)

**Comment by 0lvin** [comment]
@Yamagi Could you check #694? it should cover #673 and close #670.

**Comment by Yamagi** [comment]
Thank you! Go on with software tessellation if you want :)
