### ISSUE TITLE
The Reckoning Map: Warehouse

### ISSUE THREAD

**Issue by phine4s** [yquake2/yquake2#71]
To get to Secret 1 the fan should lift the player up. It sucks down instead (or just does not lift up).
Disabling game.dll and using original gamex86.dll works as it should..

![q2_mp1_xware](https://cloud.githubusercontent.com/assets/12458860/7651239/7424bcb6-fafe-11e4-800e-9b4939d8952b.jpg)

**Comment by DanielGibson** [comment]
I couldn't reproduce this on Linux.

Did you try the latest binaries from http://deponie.yamagi.org/quake2/windows/quake2-5.30.zip ?

If it happens for you with the latest binaries we'll test on Windows as well.

**Comment by DanielGibson** [comment]
We just reproduced it on Windows and suspect it might be a 32/64bit problem.

Anyway, we're on it :-)

**Comment by DanielGibson** [comment]
It doesn't work when build with gcc for 32bit (and thus neither with mingw, which we use  to create the windows binaries).  
It does work if you use -msse so it uses SSE instead of x87 for floating point math.  
It works in 64bit builds (when SSE is used by default) and in clang 32bit builds (I guess they use SSE by default?)

It boils down to: The leveldesigner set a too high speed for the trigger_push over the ventilator (920).  
That value is first multiplied with 10 (whyever) and then with 8 - and the result (73600.0) is stored into a short integer, which can only hold values between -32768 and and 32767.  
For some reason, gcc -m32 without SSE converts that to -32768, while in the other cases (SSE/64bit) it's converted to 8064 (I get the same result if I convert the float to a 32bit int first and then to 16bit short, so it seems like this is the normal result of an int overflow).

The crucial line is: https://github.com/yquake2/xatrix/blob/master/src/player/client.c#L2028
`pm.s.velocity[i]` is a short, while `ent->velocity[i]` is a float (and `ent->velocity[i] * 8` still is a float, but a bigger one - too big for the short in this case)

Now we just have to figure out a solution that is least likely to break more things.  
Maybe something like `int tmpVel = ent->velocity[i] * 8; pm.s.velocity[i] = tmpVel;` would do the trick by keeping the old behaviour (you said the original game.dll worked, and so do our 64bit builds) and is thus least likely to blow up in other places.  
The proper fix would be to check for an overflow and set the velocity to 32767 or something, but that would change the original behaviour and thus is kinda risky.

**Comment by phine4s** [comment]
Wow.
I'm impressed.
From the time of reaction as well as from the Depth of Explanation, honestly.
And i apologize for not being exact by not naming the OS I use nor the versions of the affected Software:
Win 7 / 64bit,
yquake 5.30
Hi-res textures in use
i52400 / p67 / amd gpu
After 10 years not having played Quake 2, I came to yamagi because kmquake had too many differences to the original and not reacting properly.
Great Work and thx for the response.

**Comment by DanielGibson** [comment]
Well, you were kinda lucky that Yamagi and me were meeting yesterday and felt like fixing a bug ;-)

Yeah, in the future please provide all that system information, especially operating system and if you built the binaries yourself as 32bit/64bit etc. In this case we were able to guess it's 32bit windows because you wrote about gamex86.dll

In general it's possible to do a map-quirk that checks for this specific entity in this specific map in the code and replaces the value. However, this bug probably happens in other places as well (https://github.com/yquake2/xatrix/issues/4 mentions a Ground Zero Level), so we're gonna fix the code "properly" instead of working around this particular trigger_push.

I'm glad you like our Quake2 client, we try to keep it as close as possible to the original experience (well, at least if one had a 3D accelerator back then), just without the bugs and with support for modern systems and screen resolutions.

(After fixing the bug we'll probably provide new windows binaries to test)

**Comment by DanielGibson** [comment]
It's fixed in git, we'll provide updated binaries later

**Comment by Yamagi** [comment]
And the binaries can be found here: http://deponie.yamagi.org/quake2/windows/quake2-5.31pre1.zip

**Comment by phine4s** [comment]
Yeeehaaa!
Good job, thx.
console reports v5.30 though ...

**Comment by DanielGibson** [comment]
That's ok, we'll change it to 5.31 on release, this is just an inofficial beta for testing

Have fun and please report any other bugs you'll find (we don't test on Windows that much because we mostly use 64bit Linux/FreeBSD)
