### ISSUE TITLE
Customized controls are not saved

### ISSUE THREAD

**Issue by ChristianPervoelz** [yquake2/yquake2#719]
Version: 2.45a, Windows 10

**Steps**
1.  Customize controls (e.g. prev item -> +, next item -> #)
2.  Leave game
3. Restart game

**Result**
Controls are reset back to defaults

This is quite inconvenient, as on some keyboard layouts some keys are not accessible by just a simple key press. For example the square brackets are alternative keys on a German keyboard.

Not sure whether this is the behavior of the original quake 2, but as there are other changes in yquake which are not part of Q2, I assume it would be great to fix this.

**Comment by j4reporting** [comment]
works for me, tested with **7**.45 ;)
check if the file  baseq2/config.cfg  is write protected

**Comment by ChristianPervoelz** [comment]
Did some experiments and found clearer steps.
1. Start YQuake2
2. Change mod to rogue (Mission Pack: Ground Zero)
3. Change control for _prev item_ from **[** to **+** and for _next item_ from **]** to **#** (please see notes below)
4. Shutdown game
5. Restart
6. Change mod to rogue (it's not stored between sessions)
7. All changes to the customized controls are back to default

**Customization**
- before setting the new binding, remove the old one by pressing backspace
- it's done with a German keyboard layout on a German Codepage on Windows, so it might be difficult to reproduce it with non-german layouts.

**Notes**
With default quake (baseq2) it works absolutely correct.

stdout shows three interesting lines after setting the bindings:
You can't bind the special key "ESCAPE"!
You can't bind the special key "~"!
You can't bind the special key "`"!

The bindings are not stored in _config.cfg_ of _rogue_, but can be used during the game, until shutdown and restarted.

**Comment by j4reporting** [comment]
yet again, works for me.
do you have an autoexec.cfg  file somewhere, that is overriding these settings? Check if there are stale config.cfg or autoexec.cfg files  in install directory.

What happens if you start the rogue, or any other mod,  with   `yquake.exe +set game rogue`  command?

**Comment by ChristianPervoelz** [comment]
There's not autoexec.cfg at all (neither in install, nor in storage location). There are also no stale config.cfg.

Anyway, loading the mod with +set game works properly, as well as first setting the custom controls and then only applying the mod.

Thanks for you quick responses :)

Not sure, whether to close this issue, or not, as I cannot bring any proof it's really fixed already.

**Comment by j4reporting** [comment]
ah, sorry, I forgot to include the link to the latest test build  from end of April. here it is  https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20210430-2e8e608.zip

I think there is still some work to do, because  the intro animations do not change when switching to another game mod using the in game menu.  I'm used to start mods with the appropriate  command.

**Comment by Yamagi** [comment]
There's one small bug in 7.45, that's fixed in git and the current Windows testbuilds: When changing from one mode to another through the `game` cvar or the menu, the config isn't saved for the first mod.

I'll look into the cinematic. I can't promise that the problem can be fixed, though. Quake II isn't really designed for changing the mod at runtime, there're some corner cases that cannot work. We've implemented it for convenience (starting the game from cmd or through batch files is annoying) and to allow the server to change to mod of the client. The later worked more or less in Vanilla Quake II, but only if the mod hadn't custom assets.

**Comment by j4reporting** [comment]
git version has also the bug with settings from base game overriding some setting in mod config.  Tested  with invprev  and invnext.

```
baseq2/config.cfg  
bind QUOTE "invdrop"
bind [ "invprev"
bind ] "invnext"
bind BACKSPACE "invdrop"

rogue/config.cfg
bind KP_MINUS "invprev"
bind KP_PLUS "invnext"
bind KP_STAR "invdrop"

```
start game, switch to rogue  and settings from baseq2/config.cfg are active.
command  to start game was `yquake2.exe -cfgdir YamagiQ2-pre  -datadir "C:/Games/quake2/"`  but it's also happening in -portable  mode.

the idlogo cinematics are played twice only immediately after the mod change.  Later the correct cinematics are played, e.g.  after closing the console. I guess it's ok like it is.

**Comment by ChristianPervoelz** [comment]
Tried that in vanilla quake and there it doesn't happen of course, as loading the mod is done with `+set game`.

Honestly: I love this port, as the experience is so close to vanilla Q2.
So I'm not sure, whether its worth fixing this issue, as it will take away the port farther from vanilla. Especially when I consider the often mentioned fragility of the code.

Just my 2cts :)

Thanks for all your effort and support!

**Comment by Yamagi** [comment]
> git version has also the bug with settings from base game overriding some setting in mod config. Tested with invprev and invnext.

The problem here is that Quake II has no concept of option namespaces. cvars and binding are global, there's no way to know where they came from. When the game is switched on the fly, all cvars and binding known to the game at that point stay as they are. The only exception are cvars and bindings which are overwritten by the mod configs.

In your example `bind [ "invprev"` is already there, `bind KP_MINUS "invprev"` doesn't overwrite it and is added as another binding.

There's not much we can do here. I experimented a little bit with resetting all cvars and binding at mod load, but that breaks a lot of things ins strange ways.

**Comment by Yamagi** [comment]
> EDIT: @Yamagi , there is a minor issue with the intro cinematics. Switching to rogue via in-game mod menu, the ID logo cinematic is played twice. It should play the rogue logo first and than die ID logo.

I figured it out: This is a side effect of alias expansion. The demo loop consists of several aliases, `d1` to `d4` for baseq2. When the mod menu is closed (after the user selected the new mod) `d1` is added to the command buffer. Since we're still in baseq2 (the game is changed the next time the control flow enters the cvar subsystem) it gets expended to `demomap idlog.cin ; set nextserver d2`. rogue overwrites the aliases and defines `d2` as `demomap idlog.cin ; set nextserver d3`. Therefor idlogo.cin is played twice. I'll need to ponder a little bit and see if I can find a way to fix this.

**Comment by Yamagi** [comment]
I've pushed a fixed for the cinematic issue. It defers the start of the demo loop until the filesystem rebuild the search path for the new game, its configs were executed, etc. The fix will only work if the the game is changed through the menu. We don't enter the demo loop when it's changed through the console or a latched cvar from the server.
