### ISSUE TITLE
Stereo Wave Support in 8.00

### ISSUE THREAD

**Issue by djdarko** [yquake2/yquake2#723]
Hi,

I just updated to Yamagi Quake II 8.00 - In the changelog there is a note that says "Support stereo wave files. (by 0lvin)"

I had been hoping for lossless music support for a while and excitedly tested the soundtrack in .wav format, but it only produced silence.

Is this change for music or just sound effect files?

Any clarification would be appreciated. Thanks.

**Comment by 0lvin** [comment]
Stereo .wav support is related only in game effects. Soundtracks is supported only in vorbis/ogg format.

**Comment by Yamagi** [comment]
I think my wording in the changelog is al litte bit confusing. As @0lvin says, stereo waves are now supported for sound samples. That's a hack, because stereo samples cannot cannot be spartialized and may sound wrong / distorted. It seems to work for the few mods that use stereo waves, though. Vorbis is still the only file format supported for the soundtrack. It'll likely stay that way, until someone shows up and refactors the soundtrack code into a generic frontend and several backends for different file types.
