### ISSUE TITLE
yquake2.exe quarantined by Malwarebytes as it's detected as ransomware while quicksaving

### ISSUE THREAD

**Issue by ks202005** [yquake2/yquake2#733]

**Comment by ks202005** [comment]
Oops, didn't mean to hit enter. Long story short, I enabled quick saving and loading using these commands:
bind F5 "echo Quick Saving...; wait; save quick"
bind F7 "echo Quick Loading...; wait; load quick"

It worked fine for a few saves, but then on my 3rd or 4th save it hung up on me. Malwarebytes immediately told me that it had quarantined yquake2.exe as it detected it as ransomware, presumably because it was trying to write to a file that already existed?

This is the URL it gives me: https://blog.malwarebytes.com/detections/malware-ransom-agent-generic/
![image](https://user-images.githubusercontent.com/65844375/128593753-0bcfdcac-2f2f-4143-9d72-1723d11df587.png)

**Comment by DanielGibson** [comment]
Another case of antivirus being garbage - I don't think there's anything we could do about it :-/
Except maybe for getting an expensive code signing certificate and signing the executables, but this is 1. snakeoil 2. blackmail ("of course you don't *need* to buy our code signing certificates, but our antivirus might blacklist you if you don't, wouldn't that be a pity") 3. not guaranteed to help anyway 4. costs more money than we're willing to spend for our hobby project.

So I suggest you restore yquake2.exe to tell Malwarebytes that you indeed trust the executable.
If you want to feel more certain about yquake2.exe's harmlessness you could upload it at https://www.virustotal.com/gui/ and have it scanned by dozens of antivirus engines.
Usually they'll all say it's harmless, though of course sometimes one or two screw up and misdetect, especially shortly after releases (turns out many don't really analyze if the executable is harmful but just flag executables they haven't seen before as suspicious).

**Comment by maraakate** [comment]
Also, just fyi, we used Malwarebytes years ago at my job and it's just as worthless now as it was back then.  If you must have AV get a real one.

**Comment by DanielGibson** [comment]
I'd suggest just sticking to Windows Defender, it's less shitty than many others and it's free.
(Though it too has flagged yq2 as malware in the past)

**Comment by BjossiAlfreds** [comment]
Can you put yquake2.exe into an exceptions list? If you want to keep MalwareBytes on your system that'd be the first thing to try in my opinion, whenever false positives occur.

**Comment by ks202005** [comment]
Adding yquake2.exe as an exception to all detections in Malwarebytes worked just fine. I wasn't particularly concerned about Yagami being an actual threat, given it had no issues until I explicitly began clobbering the same save file over and over again. I can see why that would trigger any AVs detection, even though you would think the heuristics would be a little bit more complicated than that. 
As far as AV goes, I only have Malwarebytes Premium because I got it on a steep discount and figured "why not, it was good for removing shit 12 years ago".
