### ISSUE TITLE
Possible fix out there?

### ISSUE THREAD

**Issue by ForeskinJohn** [yquake2/yquake2#737]
It seems that eraser bot with the netpack for some reason wont work on jump pads, i was wondering if this was an engine thing or a mod thing but either way id like to know if there was some sort of fix out there for this issue

**Comment by Yamagi** [comment]
It depends what the problem is. :) We haven't changed the interface between mod libraries and the server. Mods build against Vanilla Quake II will work in Yamagi Quake II. At least on Windows. Linux and MacOS have diverged to much since the late 1990th. There're two possible causes for such problems:

*  Eraser exploits bugs in the engine that were fixed in YQ2. In such case it may be possible to work around the problem, at least if someone figures out what exactly is wrong.
* It's undefined behavior in the mod library. Over the years we've found some really evil problems in the game code, especially in the movement handling. Nice things like a float getting cast to a short and the short overflows, turning a push into a pull. These thing worked by luck in the late 1990th, but may be broken on modern operating systems and / or CPUs. If the code for Eraser is available such things could be fixed, otherwise there's no chance.

**Comment by maraakate** [comment]
Was there an issue here or QDOS (or both?) about 3ZB2 bots having similar issues and someone narrowed it down to compile flags which had everything to do with float->int->float bologna.  If that's the case and the eraser bot has no source available (which it does not afaik) then there is nothing we can do.
