### ISSUE TITLE
Rare footsteps and footsteps in water

### ISSUE THREAD

**Issue by Mitradis** [yquake2/yquake2#738]
Rare footsteps (with g_footsteps=2) and footsteps in water:
https://youtu.be/5ouWGu1_MYk

**Comment by Yamagi** [comment]
That's the exactly what to expect. There're two modes:

* `g_footsteps 1` or whenever the game is running with `cheats 0`: The Vanilla Quake II behavior, footstep sounds are generated at the end of every weapon bop cycle (that's the weapon wobbling around while moving) when the player is on solid ground and faster than 225.
* `g_footsteps 2`: Added because some people were annoyed by footsteps weren't always played. Footstep sound are generated at the end of every weapon bop cycle, regardless if the player is on solid ground or who fast they are.

What you're seeing is just that Quake IIs movement is rather buggy. Or one might say "optimized". You're walking, but the player can only walk as long they're moving in a single direction. As soon as you're pressing w+d you're moving forward and to the right. That are two directions, the player starts running and you're moving faster. Faster movements leads to more weapon bops and more footsteps are generated. To make things worse the player speed is never absolute. There're several factor contributing to absolut movement speed. For example a player moving to the zero coordinate is faster than a player moving from zero. Not to forget the collision detection and movement prediction stuff done in the server or client and unknown to the game.

The foodsteps in water are a corner case. General speaking there're only two option: Either we always generate footsteps or we're doing it only when the player is on a ground entity. In a lot of cases there isn't a ground entity. Water is one example, others are some stairs or slopes, ladders, moving platforms... I could could add `g_footsteps 3` that generates footsteps regardless of the players movement speed but only of they are on a ground entity. That would lead to footsteps missing when walking stairs, slopes and the like.

**Comment by Mitradis** [comment]
how difficult it is...

**Comment by Yamagi** [comment]
Yeah, it is. One must keep in mind that Quake II was developed by a small team in juster over 12 month. And that in a time without all the nice modern tools. It's not that YQ2 is dead, but we have reached a point were nearly everything that could be done without breaking the original gameplay or mod and notwork compatiblity has been done. Anyways: I'll add a `g_footsteps 3`.

**Comment by Yamagi** [comment]
I've changed the cvar:

* `0`: No footsteps at all. There're some corner cases were exactly one footstep is generated, for example when reaching ground after a jump.
* `1`: Vanilla Quake II behavior, cheatprotected to this.
* `2`: Always footsteps, as long as there's a ground entity.
* `3`: Always footsteps.
