### ISSUE TITLE
Moving forward always makes me slide sideways

### ISSUE THREAD

**Issue by Hezkore** [yquake2/yquake2#739]
Is this just how Quake 2 works, or is this a yquake2 issue?

Moving forward makes me slide sideways.
At first I thought it was this specific floor on the first level, but it seems to happen everywhere.

https://user-images.githubusercontent.com/1727541/130710315-523740a1-3bbf-42b4-afcb-08cf64bb6937.mp4

Update:
It acts even weirder at this location by pushing me until I align with the pillar in front of me.

https://user-images.githubusercontent.com/1727541/130710592-3dc4be48-20e3-4fa8-9586-bc6448aa8fde.mp4

**Comment by Yamagi** [comment]
This could be the "zero has gravity bug". Everything is pulled to the zero coordinate. The bug is caused by wild casts between floats and integers or shorts. Quake I and likely early Quake II development version had most of the movement calculations in integers or shorts. The Quake II release version changed parts of the code to floats. This led to floats getting cast to integers and shorts, often several times in one frame. With each cast the decimals getting dropped. For example the player is at x coordinate 23.42 -> cast to integer cuts it down to 23 -> the player is pulled to 0. Some really good players (not me :)) could exploit this for some crazy trickjumps.

**Comment by apartfromtime** [comment]
The offending code appears to be in

https://github.com/yquake2/yquake2/blob/5cc9e91b02e9efe2824b2b9e5a5aa07b7cc83f54/src/common/pmove.c#L1138

**Comment by Hezkore** [comment]
I mean... it might bug me, but if this is how Q2 is supposed to be then it might as well be left as is I suppose?
Or maybe a console cvar could toggle this on/off in Singleplayer?

**Comment by apartfromtime** [comment]
It's a known bug that nobody bothered to patch out, and subsequently players exploited it. A bug as a feature.
This from Quake III Arena changelog alludes to it.

https://github.com/id-Software/Quake-III-Arena/blob/dbe4ddb10315479fc00086f08e25d968b4b43c49/code/unix/ChangeLog#L1411

As Yamagi said it's caused by the conversion from shorts to fixed point to float. I'd second its removal or a cvar to toggle it on off.

**Comment by Yamagi** [comment]
> It's a known bug that nobody bothered to patch out, and subsequently players exploited it.

It cannot be fixed. At least not in YQ2, because we aim to stay compatible with Vanilla Quake II. The problem isn't limited to the game / server site movement code @apartfromtime pointed out. It's literally everywhere. Player movement, physics calculations, etc. All that data get send over the network or local loopback to the client, where the movement and angle predictions come into play... Any changes to these things will break the network protocol, fixed server and / or clients won't be able to work correctly with unfixed servers and / or clients. Unfixed mods cannot work against fixed clients, most mods don't have their source code available. And the exiting game data was build against the buggy code, bugfixes might break it.

Even if someone wants to try it in a fork or starting with Vanilla Quake II, it would be a lot of work to go over all calculations in the code and remove the integer <-> float casts. After that someone needs to play the game, identify newly introduced problems and find ways to work around them without breaking other things. In YQ2 we spend round about the first 5 years with fixing the bugs present in Vanilla Quake II. Since then we've spend about 10 years fixing all the bugs we inadvertently introduced by the fixes and some new features, the async client alone (which was absolutely necessary, without it the game still would be limited to less than 90 FPS and exhibit extreme tearing on modern flat panels) introduced years of instability witch strange and often hard to find physic bugs and costs us countless hours of bugfixing and testing.

I'm a perfectionist. If I weren't, I wouldn't have pushed YQ2 this far. :) But I think we have reached a point where everything that could reasonably be done has been done. All that remains are some subtle problems that are hardly noticeable when playing and can only be solved with unaccaptebale effort or even not at all given that we want to stay compatible with Vanilla Quake II.

**Comment by Hezkore** [comment]
Good to know!
Closing issue.
