### ISSUE TITLE
[Bug] Showstopper crash in Oblivion

### ISSUE THREAD

**Issue by NightFright2k19** [yquake2/yquake2#759]
When playing Oblivion, you will eventually experience a crash to console in "The Harvester" map, making it impossible to continue the game.

Crash messages (one or the other):
**ERROR: Game error: ED_Alloc: no free edits
ERROR: *Index overflow**

Port: Yamagi v8.0
Mod: [Oblivion (with 2012 patch) from ModdB](https://www.moddb.com/mods/turoktirol/downloads/oblivion1)
Map: "The Harvester" (harvester1.bsp)

Reproduction:
- The "index overflow" error occurred while playing through the campaign and making progress on that map. Eventually I got kicked to console, either when trying to shoot a mob or by just running away. Curiously enough, I managed to get past the spot which triggered the second error described below.
- The "no free edicts" error occurred when trying to start the map via launcher (SQL 2.5) and blowing up the barrels on the upper deck (after climbing the ladder near the entrance to the room with imprisoned marines behind a forcefield).

**Comment by NightFright2k19** [comment]
Outstanding, my friend. Much appreciated!

**Comment by BjossiAlfreds** [comment]
If Oblivion has source code available, you could replicate my changes there. Otherwise your only option is another port I'm afraid.

**Comment by NightFright2k19** [comment]
I need to check if there is source available for Oblivion. Mods released back in the days sadly didn't have that so often. 

But just updating the executable wouldn't fix the crashes? Oblivion must have had increased limits in its custom exe back then, otherwise it would have crashed already back then.

**Comment by BjossiAlfreds** [comment]
Entity allocation is done in the game library, not the main client. I guess Oblivion made no changes to the allocation algorithm, just upped the entity limit itself, which would require quite a bit of changes in both the game library and the client.

There is always making your own ent files for these maps though, with non-essential entities removed, like armor shards and stimpacks. Though you'd have to play again from the hub or the beginning for the ent files to take effect. But I'd suggest just using another port and avoid all that extra work.

**Comment by NightFright2k19** [comment]
Well, already tried the unofficial Q2 v3.24 patch and KMQuake2, both crash as well. However, since the dll remains the same, I wonder if it works anywhere at all.

**Comment by maraakate** [comment]
KMQ2 should have extended limits for max entities.  Are you certain it's using the KMQ2 protocol and not the vanilla protocol?  Is KMQ2 actually loading the game dll?  If you're using x64 version of KMQ2 (not sure if this was released yet) and trying to use a gamex86.dll it will not work.  Try contacting Knightmare he should be able to help.  Is the source available for this mod?

**Comment by maraakate** [comment]
Sorry didn't read the whole thread earlier.  If the source is not available to the DLL you are out of luck as BjossiAlfreds stated the entity stuff is done in the game DLL.  Ent file hacking is probably your best bet or playing on a lower skill level (if the map author actually set spawnflags for various skill levels, some did not).  This has probably always been a bug but nobody has bothered to report it and has nothing to do with YQ2 or other ports.

**Comment by NightFright2k19** [comment]
I doubt it. People are asking for it since years since Oblivion still has its final map missing and without the source it can't be done.

Curiously enough, that "index overflow" issue was even mentioned on the website:
https://www.celephais.net/oblivion/main.html

That patch mentioned there never came, at least it didn't fix this. Someone made a patch in 2009, but I am not sure what was changed.

I was playing on Easy, so it couldn't have less monsters. Is there a way to remove monsters from a map with a command, maybe? Dunno if that'd help, though. There's stuff in that level that keeps spawning entities, like a grinder spitting guts. Guess you would have to turn all of that off.

But well, it still cannot hurt if Yamagi handles these cases more generously.

**Comment by maraakate** [comment]
Yamagi cannot handle these cases.  It has nothing to do with the engine it's entirely a fault with the mod author in their game DLL.  Yamagai cannot hack around it.  The entity struct size is built in to that DLL, fixing it via an ASM patch is difficult to do and the people who would be skilled enough to do it (not me) wouldn't waste their time on this.  The error message is actually coming from the game DLL.

The best you can do is generate an ent file (I don't remember if YQ2 has a command to generate it, but I believe it does, you'll have to look at the docs) then fix it to have less enemies.  You could even remove the gib generator.  However, you will have to delete your save folder and start over.  Persistent data of entities are stored in the saved files.  Even if you tried to be clever by walking back one map unit then back to the problem map it may or may not work or cause odd effects.  The save system in Quake 2 is not that clever to handle these situations.  It mostly assumes the data is correct and doesn't make too many efforts to self-heal.

**Comment by BjossiAlfreds** [comment]
It's been years but last time I used KMQ2 it didn't support the original game API, so it wouldn't load game DLLs unless built specifically for KMQ2.

Even if KMQ2 did support the game API however, that doesn't mean things will work out. Both the game DLL and client have to agree on how the entity limit was raised. If you were to run Oblivion's DLL using KMQ2's client, it is more than likely they don't match, which just leads to crashes and/or mysterious bugs and problems.

**Comment by NightFright2k19** [comment]
Man, what a mess...

But well, I can try to edit an ent file of the map (got one already through ericw tools) to have maybe 50% less enemies and see if it's playable. In the worst case, remove all.

**Comment by BjossiAlfreds** [comment]
If only id had included void *(*GetAPIExtension)(const char *name); in game_import_t and game_export_t.

**Comment by BjossiAlfreds** [comment]
I'm curious, could SVF_NOCLIENT entities be immediately re-allocated without lerping anomalies? I'm wondering if I could further ease the allocation policy this way, making G_FreeEdict give SVF_NOCLIENT ents a freetime of 0.

**Comment by NightFright2k19** [comment]
I have posted a request for the Oblivion source over at the Func_Msgboard since John "metlslime" Fitzgibbons used to be in Lethargy and he is still posting there. 

However, considering I am not the first one to ask for this and the first and only patch for the mod was released in 2009 (ten years after the original release), I am not too optimistic.

In general, Oblivion was rushed for an X-Mas 1999 release on the PC Gamer disc, resulting in the later sections of the game being particularly buggy. On the old website,

**Comment by NightFright2k19** [comment]
In a first test, I removed over 50% of the monsters in harvester1.bsp via ent file and it seems it might do the trick. Removed anything without a target or item drop, basically.

Still managed to crash to console though after trying to give back all weapons at once via a selfmade cfg file (since I loaded the map w/o previous savegame and that particular level seems to have almost no weapon pickups for some reason). This means I need to keep testing by starting 1-2 maps before to see how it is with a fuller arsenal.

**Comment by BjossiAlfreds** [comment]
give all and give <pickup name> will spawn a dummy item and force-pick it up, then free it if it still exists. If you do a lot of this in a cfg you'll create that many entities in the level since it all happens in the same server frame. In this situation it is best to execute these commands spaced out in time, so that free entities get re-used.

**Comment by NightFright2k19** [comment]
This level is really pushing the limits to the very edge, it seems. Guess that crash I had shouldn't happen under normal circumstances, then.

**Comment by NightFright2k19** [comment]
Over at Func_Msgboard, they revealed the internal index limit is 256 for everything - images, models, sounds. That's really low and I can imagine there are more maps out there which exceed that narrow limit.

So yeah, one way or another, it would be good to make the port more tolerant and robust when it comes to larger maps.

**Comment by maraakate** [comment]
Dude, there is nothing they can do!  This map relies on a DLL!

The 256 limit is PER TYPE.  So 256 images, 256 models, 256 sounds, etc.  You cannot just blindly increase these values as many port authors LIKE to do.  The reason for this is because if things get bumped up too high, especially MAX_MSGLEN, it can make the max packet size grow too large and trip up some routers/modems/switches.  It's not so much of an issue in single player, but it is a real problem in online play.

Quake 2 was actually optimized for dial up.  That is why the limits are so low.  "Booming" these limits, which was trendy to do, must be done with care.  KMQ2 is a port that has boomed limits and a new protocol written around working with it and hey this same map does not work on it, because this is a problem with the DLL and the Map TOGETHER.

You may just have to accept that there is nothing you can do and find another map set.  There's literally thousands of Q2 maps out there to try.

**Comment by maraakate** [comment]
I also want to mention that "booming" limits is NOT in the scope of YQ2.  This port is intended to be a bug-fixed port with some small enhancements to play nice on modern hardware.  Again, if you want an expanded port that can be more "tolerant and robust" with larger maps use KMQ2.  And this map set won't even work with that port anyways, because this map relies on some bullshit DLL and they couldn't even be assed to test it properly before releasing it.  I've never played this map, but I can guarantee it is not that great.  No map is that great.

**Comment by Yamagi** [comment]
Yeah, the main problems with bumping the limits are breakage of the server<->game-API (may break compatibility with old mods, mostly the same reason why we've never done an official 64-bit Windows build), breakage of the the network protocol and the possible / likely introduction of a lot new subtle and hard to find bugs. That's one lesson we've learned over the years: Don't alter thing or even fix bugs unless it's required. The strangest bug @DanielGibson and me introduced by an well meant fix was the rock squishing the tank in the 'Lower Mines' sometimes getting stuck on it's own debris. Finding and working around that took two days.

That's the reason why I'm still pondering over #760. It's probably save as long as the map doesn't run into the entity limit. The big question is what happens when that logic triggers. In theory nothing, the game doesn't error out and everything is good. In practice there's a chance that something we don't think about changes and instead of a nice and explainable error some strange bugs show up. Is this really worth the risk for a corner case which won't happen in most cases anyways? And wouldn't map which run into in the entity limit likely also trigger the model, texture or sound limit? If I'll merge it only with a clear message written into the console and the log that the recovery magic triggered and the user is in undefined no-man's-land. Like Linux does by marking the running kernel as tainted after recovering from an oops.

**Comment by DanielGibson** [comment]
IMHO a main problem with #760 is that it doesn't fix any known bug, while introducing a danger of new bugs, as @Yamagi described.
It **would** fix this bug, if Oblivion used the baseq2 game.dll - but it uses its own closed-source DLL which obviously doesn't contain the fix so it doesn't help ¯\\_(ツ)_/¯

**Comment by BjossiAlfreds** [comment]
Stress testing it is fairly easy, it only took me a few moments to pad rware2 with into_notnull's to bring it to its knees and see what happens for real. I wasn't able to cause any unwanted side-effects. It still ED_Alloc's pretty often but it is far more playable. While it doesn't technically fix a bug, I'd call it a win for the user if the game can keep the show going instead of crashing to console.

**Comment by NightFright2k19** [comment]
I guess another approach seems more viable here: Ent fixing the affected maps. I am on it already and once I am done, I can offer them here so you can have a crash-free experience even with the original mod dll. Most of the time it's just about message typos anyway. In one map I still try to figure out an ingame warning with "G_PickTarget called with NULL targetname".

**Comment by NightFright2k19** [comment]
Out of curiosity: Would activated stencil shadows have any influence on the index overflow crash, i.e. would deacticating them reduce the amount of used index entries?

**Comment by DanielGibson** [comment]
No, the shadows aren't extra entities, only the renderer knows about them, the game code doesn't

**Comment by Yamagi** [comment]
I've merged #760. It should be save enough and may help in some corner cases. I'm pretty sure that #612 is one of them. I'll port it to both addons soon. I'm closing here because that's all we can do.

**Comment by DanielGibson** [comment]
> I'm closing here because that's all we can do.

at least unless they're releasing the source after all

though I doubt the map/mission is any good (and thus worth more work on it), if they didn't even test enough to detect and fix this bug
