### ISSUE TITLE
[Bug?] Can not start deathmatch or co-op in-game

### ISSUE THREAD

**Issue by BjossiAlfreds** [yquake2/yquake2#766]
I'm experiencing something weird. Starting a MP game from the menu or setting the cvars from console doesn't work for me any more, it just starts a single-player session, with both coop and deathmatch cvars set to 0 as if I never changed them.

Setting coop or deathmatch from command-line does work however. If I start the game with: yquake2 +set game baseq2 +set deathmatch 1 and then load a map with the map command from the console, I start a DM session. And I can also set deathmatch to 0 and coop to 1 and start a co-op game. However if I set both to 0 and start a SP game by loading a map, I can no longer start MP games and have to restart the game using the above command-line string.

Stderr is blank and I don't see any errors in the console or stdout that might give clues to this. Any ideas/theories?

**Comment by Yamagi** [comment]
Is `singleplayer` set to `0`? That one was added to suppport single player games over the dedicated server: https://github.com/yquake2/yquake2/commit/2fae58d56b8ee4b2b1b7b86071710cad863587d0

**Comment by BjossiAlfreds** [comment]
That was the problem. I didn't even know this cvar was added.

Knowing this, I do have 2 suggestions:
1. The start server menu should set singleplayer to 0 automatically.
2. To retain original precedence of gamemodes, make coop and deathmatch a higher priority than singleplayer. So for example if singleplayer and coop are both 1, prefer coop. To me this makes more sense because singleplayer is the only one whose default value is 1.

It might also be a good idea to print some information to the console and/or stdout if there was a gamemode conflict and how it was resolved. Example: "Game mode conflict: Starting singleplayer, ignoring coop, ignoring deathmatch" if all 3 cvars were set to 1.

**Comment by BjossiAlfreds** [comment]
I made a personal branch with some changes that address this.

https://github.com/BjossiAlfreds/yquake2/tree/gamemode

If you like my changes I can do a PR, otherwise I will just use them for personal use. I do consider the server menu change to be a bugfix, as it should not start a SP game if you explicitly start a DM or coop game from the MP menu.

I haven't made a gamemode switcher command yet but I might do that later.

**Comment by Yamagi** [comment]
I've merged https://github.com/BjossiAlfreds/yquake2/commit/914e9dffc38c72d369b5ff15af164bb98929ec2d and https://github.com/BjossiAlfreds/yquake2/commit/4777576858a5f9693fb87bbd8b778a54e3711a79. And I've added `gamemode` to the documentation.

> Are these intentional? If not, would you like me to address them?
The're historically grown ;)

`skill` was initialized with `0` in Vanilla Quake II: https://github.com/id-Software/Quake-2/blob/master/server/sv_main.c#L950 I like to keep it that way because changing the skill during a game more or less works. When entering a level for the first time after the cvar was changed entities spawn with the new skill level. It's unsupported and might have some problems, though. 

Marking `singleplayer` as `CVAR_LATCH` sounds like a good idea. Done in 9f558dbc808d91cef1acc74e15cc5f814a28a3f6.

And I've marked all three cvars as `CVAR_SERVERINFO` in ec398e2df03a97e8979ff5afb79586465d0a5c5b.
