### ISSUE TITLE
[Bug] Cannot read textures within PAK/PK3 in root dir

### ISSUE THREAD

**Issue by NightFright2k19** [yquake2/yquake2#767]
Yamagi Q2 is apparently unable to read textures stored in the "textures" root dir (no subdir) if they are stored in pak/zip/pk3 files.

Tested with:
Yamagi Q2 v8.01pre (built from source on Nov 6 2021)

Reproduction:
- Extract "Ride The Lightning" (poodm1.zip, attached) into user dir "poodm1"
- Launch with: **yquake2.exe  +set game poodm1  +map poodm1**
- Textures will show up properly ingame
- Now, zip "textures" dir in the poodm1 folder, delete the textures folder afterwards and launch again
- Textures in root folder (pooblu.wal, poocross2.wal, pooflor2.wal, veggi1.wal, WALL3_4.wal) will not be loaded
- Same will happen when using PAK format instead of .zip/.pk3

Errors are like this:
Couldn't load textures/./wall3_4.m8
Couldn't load textures/./pooblu.m8
Couldn't load textures/./poocross2.m8
Couldn't load textures/./pooflor3.m8
Couldn't load textures/./vegg1.m8

Additional note:
Inside of poodm1.bsp, the textures in question are defined as _./wall3_4_, _./pooblu_ etc.

My assumption is that the port doesn't know what to do with the ./ dir or literally looks for a folder named ".", which is technically impossible to create.

"Ride The Lightning" map (poodm1.zip, 0.8 MB):
[poodm1.zip](https://github.com/yquake2/yquake2/files/7503714/poodm1.zip)

**Comment by Yamagi** [comment]
> My assumption is that the port doesn't know what to do with the ./ dir or literally looks for a folder named ".", which is technically impossible to create.

Ah, the **robust** and totally not hacky Q2 filesystem again. :) It's exactly what you say. The code is here: https://github.com/yquake2/yquake2/blob/master/src/common/filesystem.c#L372 It takes the filename in `name`, allocates a file handle with it and looks if it can find that file in paks (the search path makes sure that numbered paks have precedence over unnumbered paks, the precendence between unnumbered paks is filesystem dependent), zips of all kind and the raw directory tree. `name` contains the path as it's found in the map, there's no normalization or anything. Since paks and zips don't support relative pathes, the files cannot be found. It works in the directory tree, because the code just calls `fopen()` which normalized pathes.

We could, at least in theory, normalizes paths at the beginning of the function. The question is if that would break some corner cases.

**Comment by Yamagi** [comment]
After some pondering normalizing self references with `.` and empty path elements with `//` should be save. Relative paths with `..` should exists in Quake II but you'll never know. So we should leave them alone.

**Comment by BjossiAlfreds** [comment]
The original pak0.pak for baseq2 contains this path: "models/monsters/tank/../ctank/". So you definitely have to skip on normalizing "..".

**Comment by Yamagi** [comment]
I've added path normalization for:

* Self references (`/./`)
* Empty directories (`//`)
* Leading Slashes

This should be save. This is limited to `FS_FOpenFile()`. There're some other function which might benefit from this change. I haven't added the fix to them because I want to avoid unnecessary changes to the fragile VFS.

**Comment by NightFright2k19** [comment]
Confirmed working with latest build. Nicely done!
