### ISSUE TITLE
Jumping issue Multiplayer and maybe singleplayer too

### ISSUE THREAD

**Issue by MadDog386** [yquake2/yquake2#785]
I have an issue where if i have the variables set as such:
cl_async 0
vid_maxfps 120
cl_maxfps 120

When im strafe jumping through the map it seems to delay my jumps after the first hop  making it impossible to strafe jump or even time jumps across platforms which i can fall off of when my jump is delaying to register.

i noticed if i set the variables as such:
cl_async 1
vid_maxfps 120
cl_maxfps 120
busywait 0

It happens much less often but still happens sometimes. I also tried cl_async 0 but it happens a bit more than if its on 1.

Im hoping this can be fixed because i really like this client for multiplayer. good quake2.exe replacement for modern systems.

EDIT: i am on windows 10
Seems to happen at any fps above 100 or so

**Comment by Yamagi** [comment]
> Seems to happen at any fps above 100 or so
I didn't happen with Vanilla Quake II?

**Comment by MadDog386** [comment]
> > Seems to happen at any fps above 100 or so
> 
> I didn't happen with Vanilla Quake II?

I tried the original quake 2 client earlier and i don't have the skipped/delayed jump issue at cl_maxfps 120, only seems to be on yamagi client.  

Should i record a video of the issue i am having so you can more clearly understand what I mean by jump "delay"?

**Comment by Yamagi** [comment]
A video would be very helpful

**Comment by MadDog386** [comment]
> A video would be very helpful

https://www.youtube.com/watch?v=AmeWAqr0daw

Here is a video, i added some times in the description of the video where it lables what settings i used and how you can see it effects the bug

**Comment by MadDog386** [comment]
> That's indeed very helpful and makes clear whats goes wrong. One more thing: Is that under Linux or Windows? I'm asking because the low level timing code (mostly `Sys_Nanosleep()` )is different.

I am using Windows 10, i do not have a linux system setup right now to test the linux version, sorry.

**Comment by Yamagi** [comment]
So far I was unable to trigger this on my machine. However I havn't played Quake II in multiplayer for years and my skills are more than rusty. Two ideas to narrow this down:

* No matter what `cl_maxfps` and `vid_maxfps` are set to, the game will always enforce 5 percent less client frames than render frames. That's because the client must not run faster than the renderer, otherwise everything explodes. Can you try to increase `vid_maxfps` to 130 and see if it helps? I don't think so, because the problem also occurs with `cl_async 0` which doesn't distinguish between client and renderer frames.

* There's a hacked up build here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-issue785-1.zip It removes the "brake" from the mainloop. No matter what `busywait` is set to, the game will always spin as fast as it could and burn it's CPU core at 100 percent load. If this does help, the problem is likely the game sleeping too long and missing the start of the next frame. That would break physics. If it doesn't help, the problem is not in the platform specific code. Which means that things will get complicated.

**Comment by MadDog386** [comment]
> So far I was unable to trigger this on my machine. However I havn't played Quake II in multiplayer for years and my skills are more than rusty. Two ideas to narrow this down:
> 
>     * No matter what `cl_maxfps` and `vid_maxfps` are set to, the game will always enforce 5 percent less client frames than render frames. That's because the client must not run faster than the renderer, otherwise everything explodes. Can you try to increase `vid_maxfps` to 130 and see if it helps? I don't think so, because the problem also occurs with `cl_async 0` which doesn't distinguish between client and renderer frames.
> 
>     * There's a hacked up build here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-issue785-1.zip It removes the "brake" from the mainloop. No matter what `busywait` is set to, the game will always spin as fast as it could and burn it's CPU core at 100 percent load. If this does help, the problem is likely the game sleeping too long and missing the start of the next frame. That would break physics. If it doesn't help, the problem is not in the platform specific code. Which means that things will get complicated.

Hi i noticed certain fps values would cause it in stock quake 2 as well, i tested it on two different machines. But i seemed to have found a weird fix, i made a video showing it and what seems to be going wrong.

The video is self explantory maybe it can help.

https://www.youtube.com/watch?v=HbSjqKgMYJk

**Comment by Yamagi** [comment]
After a lot of testing with several YQ2 version back to 1.4, Vanilla Quake II 3.20 and SDL 1.2 neither @DanielGibson not me see a difference to id Softwares original executable. In general everything higher than 90 packet frames (`cl_maxfps` when `cl_async 1`, `vid_maxfps` otherwise) is undefined and thus buggy. The code cannot scope with frame rates that high, things like trick jumps exploit this.

Both double jumps and strafe jumps are highly frame rate depend. As an example 125 fps is nearly unusable, 120 fps is much better. We didn't find a framerate were it's perfect. Nevertheless, framerates which works good under Vanilla Quake II are also good under Yamagi Quake II and the other way round.
