### ISSUE TITLE
Some mechanisms at the Factory level don't seem to work correctly

### ISSUE THREAD

**Issue by Lrflx** [yquake2/yquake2#786]
For example this grinder isn't moving at all most of the time. Though result looks kinda funny I guess. 
Checked with 8.01
![q2_0001](https://user-images.githubusercontent.com/63182627/151525281-df77b0fa-7072-4e40-bb1f-4d9a8f10dcaf.jpg)

**Comment by Yamagi** [comment]
A, the factory again... It has always been rather fragile. The problems were mostly related to gibs blocking some entities and I though we found a combination were both gibs and the factory were working. or at least working enough. I'll have another look.

**Comment by BjossiAlfreds** [comment]
In the original game gibs are SOLID_NOT but in YQ2 they are SOLID_BBOX. ThrowGib() and target_spawner gibs don't have a clipmask so they shouldn't obstruct moving brushes, but the one created by ThrowHead() might - It has a bbox of size 0 (which is treated as a collidable by the CDS) and the monster's original MASK_MONSTERSOLID clipmask. I don't know if that has anything to do with it but it's a noteworthy code change.

**Comment by BjossiAlfreds** [comment]
I also notice another oddity, doors that aren't crushers behave like they are, like the first door in base3. The problem is the !activator check in door_go_up() that makes the function return prematurely. That could also play a role here.

**Comment by Yamagi** [comment]
If I remember right id Software changed from `SOLID_BBOX` to `SOLID_NOT` in one of the point releases, because `SOLID_BBOX` had some unwanted side effects. That broke several things, for example gibs were no longer carried by conveyor belts. We changed it back to  `SOLID_BBOX` and fixed the side effects. `MASK_MONSTERSOLID` on the head might be indeed the corner case we've missed and that's causing the problems. I'll change the code and see if it helps. Otherwise we'll need to dig deeper.

> I also notice another oddity, doors that aren't crushers behave like they are, like the first door in base3. The problem is the !activator check in door_go_up() that makes the function return prematurely.

Hmmm... That sounds a like a bug introduced with the sanity checks. I'll remove the check.

**Comment by maraakate** [comment]
You also need to remove the (which is called from door_go_up()) G_UseTargets() !activator sanity check.  I noticed at some point in my notes with the coop mod it breaks the plats in xware.bsp.

**Comment by BjossiAlfreds** [comment]
When removing it from G_UseTargets, it's a good idea to add it into the next if-statement: if (activator && (ent->message) && ...). Otherwise the game could crash with a NULL activator when the trigger event has a message. I don't know if the game can get into that state, but it's better to be safe.

**Comment by Yamagi** [comment]
This was caused by a complete different bug: `func_rotate` didn't connect the `rotating_blocked()` function. That bug was introduced while fixing the problems found by PVS studio.

I've also implemented the other suggestions made in this discussion. Thank you all.
