### ISSUE TITLE
[Feature Request] Nightmare Suggestions

### ISSUE THREAD

**Issue by OpenRift412** [yquake2/yquake2#809]
This is a bit of a nitpick, but I thought I might as well ask. Wouldn't it make a bit more sense for "Nightmare" to be listed as "Hard+", therefore matching how the difficulty is listed in the game's help computer menu? I know it's pedantic, but it's just a consistency thing.

Also, perhaps an interesting thing to add would be that in order for nightmare/hard+ to show up in the New Game menu, you have beat the game (or enable it via a console command), akin to how Doom 3 does it.

**Comment by apartfromtime** [comment]
Another option would be changing the game help computer to fit "Nightmare" into the skill group.

I think all of the GUI needs enhancing while still retaining the q2 art direction. But that is up to Yamagi to decide. YQ2 has reached the point where all of the major bugs have been fixed and that all that is left is these inconsistencies and bugs introduced through workarounds\fixes.

**Comment by maraakate** [comment]
I think requiring you to beat the game or console cheat to enable hard+ is a bit beyond the scope of YQ2.  But, renaming it to Hard+ would probably make the most sense.  Or "Hard+ (Nightmare)" in the skill menu.  Editing art assets is probably something that I doubt would happen.

**Comment by Yamagi** [comment]
It's called "Hard+" in the help computer, because the text field is too small for "Nightmare". Internally it's called nightmare. It was the same in Vanilla Quake II, the only thing I've added is the menu entry. Before that the nightmare skill was only available through the console. Changing the menu to "hard+ / nightmare" looks ugly. What about changing the help computer to something like "nightm."?

 > Also, perhaps an interesting thing to add would be that in order for nightmare/hard+ to show up in the New Game menu, you have beat the game (or enable it via a console command), akin to how Doom 3 does it.

While this isn't impossible, it's more complicated than it looks. The information if the game was beaten would be available in the game, the menu is drawn by the client. The information needs to be passed from the game to server, over the network to the client. It could be done by a cvar, but the client would need to take in account, that not every game implements it... It's not worth the efford.

> I think all of the GUI needs enhancing while still retaining the q2 art direction.

A *good* AI upscale of all the assets would be nice. I know there're several upscaled texture packs, but so far all of them looked ugly. Maybe due to the use of an unfitting model / profile.

**Comment by apartfromtime** [comment]
I had a look at the vanilla source, and I would agree with [OpenRift412](https://github.com/OpenRift412) and [maraakate](https://github.com/maraakate) that the skill was always referenced as "hard+" and makes the most sense in the menu and would be consistent help computer, "nightmare" makes sense in the context of q1, which was the assumption I was operating under that this was carried over from q1, but someone has added it in.

Maybe a key combination could make the "hard+" option appear in the menu?

**Comment by OpenRift412** [comment]
> Maybe a key combination could make the "hard+" option appear in the menu?

Key combination? Ooooh, I like that idea. Maybe have it play a sound when unlocked, like the quad damage noise.

**Comment by NeonKnightOA** [comment]
That or passing the game in Hard mode.

**Comment by Yamagi** [comment]
I've renamed it to hard+. Looks ugly but whatever. For everything else send a pull request.
