### ISSUE TITLE
Elevators and doors stutter

### ISSUE THREAD

**Issue by dezo2** [yquake2/yquake2#819]
When using 144Hz/FPS with vsync on and default settings (cl_async 1), there are some nasty stutters on elevators, opening doors etc. It is somewhat smoother with cl_async 0, but then the physics can be broken according to yq2 docs. Is there some other cvar I can try to fix this? Tried the same map sections in q2pro and there was no stutter at all. Here is a save before such elevator in Ammo Depot map: [save4.zip](https://github.com/yquake2/yquake2/files/8555681/save4.zip)

**Comment by dezo2** [comment]
Nevermind, it works smooth enough so far with cl_async 0.

**Comment by DanielGibson** [comment]
this should also (and especially) work with cl_async 1

**Comment by dezo2** [comment]
That would be great.
The game movement is OK overall, only the elevators / doors and similar linear animations exhibit these skips, Framerate is constant 144FPS all the time with flat frametime chart, GPU usage around 5%. Fiddling with cvars cl_maxfps, vid_maxfps, r_vsync didn't fix it until cl_async is set to 0 or cl_maxfps is set to 144 from default 60 to match display refresh. Which I guess is the same as set cl_async to 0.

**Comment by Yamagi** [comment]
This could be caused by the special case for stairs and evelators: https://github.com/yquake2/yquake2/blob/master/src/client/cl_prediction.c#L298=

Does setting `cl_predict 0` help? That isn't a fix, just to figure out were to look.

**Comment by Yamagi** [comment]
Position in the attached savegame is bunk1.bsp / -678 -102 46.

**Comment by dezo2** [comment]
cl_predict 0 makes it even more visible and also adds skips when strafing.
So far the best settings for async for me is cl_maxfps 144 and leave the rest at default.

**Comment by DanielGibson** [comment]
maybe cl_maxfps 60 (or maybe 63 or 64) and vid_maxfps 120 could work well?

**Comment by Yamagi** [comment]
First: q2pro is a very good Quake II engine. From a source code standpoint likely the best. Since they effectively dropped singleplayer support and concentrate on multiplayer, they can do a lot of architectural changes and bugfixes which aren't possible for YQ2. We focus on singleplayer and mod compatibility. We try to stay mostly bug-compatible with Vanilla Quake II, even if it means that we cannot fix some problems.

The root cause for the stuttering elevator is a long standing bug in the movement prediction. If the player moves in vertical direction, some velocities work good and other velocities lead to mispredictions. This mispredictions cause slightmispositions and subsequently repositions. This repositions can be perceived as subtle stuttering. We cannot fix this, because existing game data requires the broken prediction behavior, without some game mechanics will likely stop working.

You're seeing a side effect. With the async client the renderer interpolates one server frame into several renderer frames. If the divider between the two framerates is suboptimal, the stuttering is amplified. On my 60hz display with `vid_maxfps 144` a `cl_maxfps 62` gives a much better result than the default 60.

We'll see if we can come up with some magic to mitigate this problem. It might take some days, through.

**Comment by dezo2** [comment]
I understand, thank you for looking into this.
I will try to fiddle with the cvars some more, but I can live with that no problem. I would probably not even notice it on my old 60Hz display. Its just these old games looks sooo much better at high refresh rates.

**Comment by DanielGibson** [comment]
The changes in #830 might help with this, especially if you set `cl_maxfps` to `-1` (only works with the changes from that PR).
To make that elevator extra smooth, additionally set `vid_maxfps` to `120`

**Comment by Yamagi** [comment]
A new Windows testbuild with the timing changes included can be found here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20220510-1833f16.zip

**Comment by dezo2** [comment]
Thanks for the build, Tested it with cl_maxfps -1, vid_maxfps 144 and 120 fps and at 120 it is indeed better. At 144 it stutters like before - even when I set cl_maxfps to 72 manually. Stutters vanish completelly only when cl_maxfps value is the same as current fps value. Anyway my display has variable refresh in range 24-144, so I will just set framerate limit to the value that works best and be done with it.
