### ISSUE TITLE
Heretic 2 support

### ISSUE THREAD

**Issue by 0lvin** [yquake2/yquake2#870]
Does it  make sense to port code from https://github.com/jmarshall23/Heretic2? (https://www.doomworld.com/forum/topic/120254-heretic-2-source-code-recreation-part-2/) 

I am not sure that such is legal and covered by GPL.

What do you think?

Idea is 
* We can use code in main repository for support models from some other GPL projects.
* Add some non GPL repository with game library code from Heretic2 re-cteate repository with mention that it is not fully legal.

**Comment by 0lvin** [comment]
SDK code can be downloaded from [Ht2Toolkit_v1.06.exe](https://www.quaddicted.com/files/idgames2/planetquake/hereticii/files/Ht2Toolkit_v1.06.exe)

**Comment by Yamagi** [comment]
This should be done in an own repo. For two reasons:

* One can never be 100% sure that the licensing is okay and no proprietary code is involved, either on purpose or by coincidence. Oven reverse engineering isn't guaranteed to be clean if it want done right as clean room implementation with at least two developers (one for documentation and one for implementation) involved.
* Quake II is not Heretic II. :) Supporting heretic II in YQ2 would always be a burden for both projects. YQ2 needs to maintain code which it doesn't need, is therefore poorly tested, etc. The H2 project needs to get all engine side changes in YQ2, which a long and annoying process. Since YQ2 is mostly done and sticking to bugfixes and smaller features these days merging YQ2s upstream changes into a H2 downstream project should be easy.

**Comment by 0lvin** [comment]
Thank you! 

Its looks as really big code amount, and question is more theoretic than real effort ;-) Maybe in future will be some gain.

**Comment by DanielGibson** [comment]
Keep also in mind that this would require modifying all renderers (unless you'd restrict Heretic2 support to only GL(ES)3 or whatever).

IMO a YQ2 fork with Heretic2 support would be pretty cool, but as you said it's a lot of work and I agree with Yamagi that merging it back into this engine might not be a good idea, both because of code bloat and because of licensing questions.

**Comment by 0lvin** [comment]
I finally have version of heretic2 on Linux.
 It's on really initial steps, it could be complied ;-), it runs without crashes and can open tutorial level. That's all what is good. 
Drawbacks: code is not rebased over yquake2 code, no sounds, broken jumps, no menu or books implementations.  Code can't open ssdocks level(first level of game). Not all files has licence header and code is little bit mess.

https://github.com/0lvin/heretic2

If someone has tons of free time to waste, you are welcome;-)

**Comment by KAMiKAZOW** [comment]
> I am not sure that such is legal and covered by GPL.

Yes, it is covered by the GPL because jmarshall modified the GPL release. As per the GPL, all modifications are under GPL as well. The quality of H2 support makes it extremely unlikely that it's based on leaked code, no code leak was ever reported, and Activision did not DMCA it either, so I see basis for any caution going further than merely following the GPL.

**Comment by 0lvin** [comment]
Little update: code is rebased over yquake2, in same time it has issues with moving, player model animation is not played when player is moving, looks like still has issues with jumping and noclip. And other smaller issues.

**Comment by 0lvin** [comment]
Looks as I finally have code with same functionality state as https://github.com/jmarshall23/Heretic2 had. 

In same time code is rebased over yquake2 master, show blockers are:
* jump is not supported,
* only GL1 has not bad rendering support,
* soft don't crash, but incorrect angle of models render and no fireballs on attack
* player could not change weapons
* client/server code has ugly hacks
