### ISSUE TITLE
[Improvement] Mod list should be enclosed in brackets

### ISSUE THREAD

**Issue by TedThompson** [yquake2/yquake2#881]
While DM levels are guilty of not following this "Style guide" rule, other places where Left and Right are employed to scroll thru options (most notably in the video menu) have [ and ] around the entry.

I submit that the addition of a Mods menu (a welcome QOL enhancement) would be further improved by adding a [ before, and a ] after the mod name. in the menu.

As would a method of adding a "human readable" name for mods that aren't CTF, Reckoning, or Ground Zero in that gray banner at the bottom of the screen.

**Comment by BjossiAlfreds** [comment]
I definitely wouldn't give Quake 2's spin controls many usability points. There is nothing really there to tell the user they can move left/right. In busy option menus the user would be more inclined to assume it's a left/right spin, but in an empty screen like the mods menu, people are more likely to expect a vertical list, especially since they just came from one (the easy/medium/... menu).

**Comment by TedThompson** [comment]
Precisely, but the brackets are a textual clue there's more to be seen. I'd have tried the left and right if they had been there, but like you say, with all that empty real estate on the screen my brain thought the game didn't know there was more.

**Comment by Yamagi** [comment]
This was solved by merging #882.
