### ISSUE TITLE
yquake2 more info

### ISSUE THREAD

**Issue by mckaygerhard** [yquake2/yquake2#89]
i see more projets in yquake2 group github, and read the README complety.. try to play again this game for me (i dont like the playstation version) and does not run.. noted some things:

1) i cannot setup different game base dir (or i dont know how in linux)?¿
2) respect i see, do i need some others compiled files for play rogue or xtraix?¿
3) the baseq2 are case-sensitive or must be all uppercase?¿

could u provide me those info and i can made a extense file with FAQ and a pull request for the respective place

currently i plan to package the compelte quake2 game for my Debian based and also promote the the flaky poor debian oficial main repo (as i noted its not very improvement the debian oficial package)

also i want to play the mod of Zaero and i cant see there's some changes made it here in the respective project.

eagerly awaiting response... thanks in advance.

**Comment by Yamagi** [comment]
Hello,
that's more or less easy to answer:

* The "yquake2" repo has all the GPL licensed stuff excluding the "Three Wave Capture The Flag" addon. That's the client "quake", the dedicated server "q2ded" and the main game "baseq2/game.so".
* The addons are provided as separate repositories, mainly because they're provided under the Quake II SDK license.
  * xatrix -> The Reckoning (the first addon)
  * rogue -> Ground Zero (the second addon)
  * ctf -> Three Wave Capture The Flag (GPL licensed)
  * zaero -> The Zearo mod. The port is unfinished but more or less working.

You'll need to build the main client and each addon. The README files supplied with the code have instruction how the code must be build and how the game.so and the game data is put together. On Linux / Unix all directories must be given in lower case. The game data itself should(!) be case insensitive. Read: It works as it's provided by id Software.

The the system wide game data directory can be configured with the WITH_SYSTEMWIDE and WITH_SYSTEMDIR compile time variables. Have a look at the Makefile, it has some comments for each compile time option.

**Comment by mckaygerhard** [comment]
thanks for clarify, so the addons are non-GPL but redistributable if are non-commercial right? i right now reading the parts 2 and 3 of the SDL license and i found that (i think due my english are very bad)

i ask something, u'r project are only a mantained code of original work, if i made manpages and better README more explicit, pull request can be possible or are outside of the scope of the target? (waiting for feedback)

reading the code now i understand why are so many mods for quake 1 and quake3 and so few for quake2, quake2 needs a loaders (as i understand reviewed the code)

the base dir are cahnged thorught variables event a parameter option like others engine (and now i know original quake codes set basedir as it)

i try to package those addons for my debian derivate VenenuX

**Comment by mckaygerhard** [comment]
another question, SYSTEMWIDE and SYSTEMDIR what are the differences, i see the code at init filesystem and seem systemwide permits added more than one directory "to search" or changes the base dir?

**Comment by maraakate** [comment]
Quake 2 mods are DLLs so without their original source code available theres no way to port them to linux or new quake ports that veer from the original q2 structure.

**Comment by mckaygerhard** [comment]
yeah i experiment that yesterday triying to load and play the zaero witouth the proper "share loader" of the game.. (DLL, theres no DLL that its only appliet to an inestable os)

in mac i found the loader for OSX and now i can play it! for Free BSD and Maebo i try to compile the zaero source of yamagi and seems to work.

i'll close this issue due now i have the enought info.
