### ISSUE TITLE
Player skins not ordered alphabetically

### ISSUE THREAD

**Issue by ghost** [yquake2/yquake2#891]
In vanilla Q2, the player skins in the menu are ordered alphabetically by name. For a while now, the order in Yamagi Q2 has been random and not predicated on any discernible criteria (model name or even file size of the skins). 

I've encountered this on Linux and FreeBSD (i.e. with case-sensitive filesystems), cannot confirm whether it is also the case on Mac or Windows. 
  
Since there is no other obvious (to me) cause in the code, I suspect the problem may be that the list is non-alphabetically ordered when retrieved from the filesystem. While not critical, for aesthetic reasons, it would be nice if this could be fixed.

**Comment by apartfromtime** [comment]
The models are always sorted male, female then alphabetically, the skins however are never sorted. Are you certain it is random? Windows returns them alphabetically. You would think any systems level programmer would return them at the very least sequentially case sensitive or not.

I could add another sort to the skin display names since I made some changes to that code recently if Yamagi or anyone else would like to see that implemented, but I haven't any way to test this on Linux, since I run Windows.

**Comment by widmak** [comment]
Yes, it is the skins that are not being sorted alphabetically (sorry – the original title of the issue was misleading!). 

The order is fixed and not random in the sense that it changes each time YQ2 is run, but it is definitely not alphabetical. For example, the first five skins under 'male' are (consistently): razor, nightops, major, claymore, grunt.

Adding a sort as you suggest ought to prevent this.

**Comment by Yamagi** [comment]
> Windows returns them alphabetically. You would think any systems level programmer would return them at the very least sequentially case sensitive or not.

Most unixoid systems return files in the order they are found on the filesystem. The specific ordering depends on the filesystem.
