### ISSUE TITLE
Bug: cinematic palette not cleared when "developer" set

### ISSUE THREAD

**Issue by apartfromtime** [yquake2/yquake2#925]
Exiting a cinematic early, with the "developer" command variable set, skips clearing the palette back to the default "game" palette. The client state is later zeroed with memset, while the "cinematicpalette_active" still active.

https://github.com/yquake2/yquake2/blob/690e46512ee7a2dacccb9bc4168721de72a96619/src/client/cl_screen.c#L585

Not an issue in opengl. Software results in the previous cinematic palette continuing to be active.

Adding the lines solves the issue.
```
if (developer->value)
{
	if (cl.cinematictime > 0)
	{
		SCR_StopCinematic();
	}

	return;
}
```

**Comment by Yamagi** [comment]
Interesting problem... :) I've pushed a hack that works good enough. It still renders at least one frame with the wrong palette, though. I complete fix would be rather invasive because it would require reworking this overly complicated loading plaque and screen clearing magic. That has a high provability breaking corner cases exploited by mod, custom campaigns, etc.
