### ISSUE TITLE
ReadLevel Errorwhen loading a custom map save

### ISSUE THREAD

**Issue by Screamerofstars** [yquake2/yquake2#937]
Recently i decided to take a loot at the Quake 2 Single Player packs at moddb

https://www.moddb.com/games/quake-2/addons/quake2-superpack-1

https://www.moddb.com/games/quake-2/addons/quake-2-super-pack-2

and while playing Awakening, i found a ReadLevel Error when trying to load any save outside the default ones, quicksave also works.

![q2_0002](https://user-images.githubusercontent.com/51536434/202923550-0229edbc-571e-401a-9719-d6a5a7dc0265.jpg)

og 3.20 q2 exe and Kmq2 have no issues with this map

**Comment by BjossiAlfreds** [comment]
YQ2's game.so/game.dll library doesn't check for function pointers, so you are using an external game library which YQ2 has no jurisdiction over. This error happens because there is no guarantee the library gets loaded into the same address space as previous runs.

Perhaps there is a way for YQ2 to always try to load the game library into a fixed addresss space first, but even then there is no guarantee there is enough room for it there and so the saved function pointer will not be aligned. The only reliable fix is to remove the check, if source code is available, or if that fails, give the library a base memory address by editing its metadata (this can be done with Windows dll's, not sure about Linux shared objects (so's)).

But unfortunately all these options will require you to start over, or you can keep restarting the game and hoping the game library is loaded into the same address space as the one where you last saved...

**Comment by Yamagi** [comment]
Looks like the source code to Awakening was never released. The developer was Eric Von Rothkirch: https://www.mobygames.com/developer/sheet/view/developerId,479658/ If you are really interested in preserving Awakeing, you can try to figure out a way to contact him and ask if he still has the sources and is willing to release the source code to the public.

An alternative source would be Richard Hess who ported the mod to BeOS, Irix and Linux: https://web.archive.org/web/20050214001153/http://www.planetquake.com/awaken/download.shtml A quick Google search shows that he ported a lot of software back in the day. There are a lot of people named Richard Hess out there, it might be hard to find the right one.

With the source available porting YQ2s fixed savegame system - it will work with any engine, since it is in the game.dll - would be rather easy.

**Comment by DanielGibson** [comment]
I googled Richard Hess a bit, and he used to work at Netscape and later SGI, this is the latest snapshot available of his homepage at SGI: https://web.archive.org/web/20010802004131/http://reality.sgi.com/rhess_engr/
Seems like he was also involved with Mozilla (even after leaving Netscape).

Unfortunately I couldn't find out where he went afterwards (and the reality.sgi.com pages were taken down later in 2001 and I don't have a newer homepage of his), the only mentions of him were from the late 90s when he parted several Q2 mods to BeOS, Irix and other weird platforms, and he also ported Q3A to Irix.

Anyway, I think Eric von Rothkirch is easier to find, most (all?) of the google results should be him, so I'd suggest trying to contact him and hope he still has the source

**Comment by DanielGibson** [comment]
Oh wait, on Richard Hess I just noticed a link on the aforementioned homepage to https://web.archive.org/web/20040618090757/http://eswat.deviantart.com:80/ (the profile still exists: https://www.deviantart.com/eswat/about#about but hasn't been active since 2014)

And googling `"Richard Hess" eswat` gives us https://github.com/eswat2 and https://eswat2.github.io/ which has an e-mail address and several other links to pages he's on

**Comment by DanielGibson** [comment]
Furthermore, I found http://awakening2.backshooters.com/ - is "Awekening 2" just an updated version of the original Awakening mod? If so, source is available

**Comment by Screamerofstars** [comment]
Quicksave still works, it is a short 2 map mod, but its main feature are the maps and multiplayer.

i will look at other maps at the Single player pack 1 once in a while, Single pack 2 is the mission packs like The Armageddon device and so on.

Also, if you guys are interested, the quake 2 Oblivion gamei386.so can be accessed by Binary Ninja, this is what i saw off the debug file https://files.catbox.moe/853ubb.txt

Pseudo C version  https://files.catbox.moe/k5a9xf.txt

i think its possible to reverse engineer the source code off the .so file

**Comment by Screamerofstars** [comment]
> Furthermore, I found http://awakening2.backshooters.com/ - is "Awekening 2" just an updated version of the original Awakening mod? If so, source is available

Yes, it is a reverse engineering of the original mod

> This Quake2 mod was originally designed and created by Eric "redchurch" von Rothkirch (http://www.redchurch.com) and Patrick Martin back in 1999. The version 1 source code was not available, so I had to recode the mod from scratch (with kind permission) before I could develop it further with the new features intended for version 2.
