### ISSUE TITLE
-portable gives error on server change

### ISSUE THREAD

**Issue by KOKOSv8** [yquake2/yquake2#969]
1.Changing maps with gamemap on local works good no error. 
2.Connecting to online server and then changing to local "map q2dm1" quits game and gives error "Couldn't create dir".
3.Connecting to online server and switching to other online server quits game and gives error "Couldn't create dir".
![Screenshot_1](https://user-images.githubusercontent.com/123253141/214140930-ad26c733-f0ef-4aba-8f29-821f01527c84.png)

**Comment by maraakate** [comment]
I know this is a bug, but in defense of the devs it's not as well-tested and you really shouldn't be using -portable.  Especially on Windows Vista and later because the NTFS folder permissions make things difficult which is why user data is now written out elsewhere.

Have you tested running it as admin?  If it works as admin then it's probably folder permission issues.

**Comment by KOKOSv8** [comment]
Running as admin didnt solve the problem, but if this is too hard to fix then we can forget about it as its not really important. I personally just like to have all q2 files in one folder.

**Comment by lafoxxx92** [comment]
Which Game is the server running? Not baseq2?
Disconnect first, then change map – works?

**Comment by KOKOSv8** [comment]
Game is opentdm, if i do disconnect first then there is another error.
![Screenshot_1](https://user-images.githubusercontent.com/123253141/214598199-9691312e-662e-4100-ad43-0978386e8972.png)

**Comment by Yamagi** [comment]
The Quake II virtual filesystem is gift that keeps giving... Nevertheless I'm not convinced that this our bug. Config files are written to the first directory in the search path, the config dir is created the moment the search path is build. That happens when the game starts and every time the `game` cvar changes. The only thing `-portable` changes is the first directory: Normally it's 'My Documents\YamagiQ2', when `-portable` is set its the binary dir.

It's highly suspicious that the game starts fine, the first call to `Sys_Mkdir()` is fine. At a later time - after data was send over the network -  the search path is rebuild and the call to `Sys_Mkdir()` fails for some reason. This wouldn't be the first time that antivirus software interferes with YQ2: Our binaries aren't signed, they load unsigned DLLs at runtime, they transmit data over the network and when `-portable` is set they try to write into their binary dir -> antivirus software may block write requests.

In fact writing into the binary dir is shaky when antivirus software is involved, this was one reason for writing into the users home directory by default. Before we continue, please make sure that no antivirus software including Windows Defender is interfering with Quake II.

If the problem persists without antivirus software I need to see the log file with debugging enabled: Start the game with `quake2.exe +set developer 1 +set fs_debug 1` -> open the console and type `path`, it will print out the search path and copy it into the log -> reproduce the problem -> attach stdout.txt here.

**Comment by KOKOSv8** [comment]
So i have added yamagiq2 to exception in windows defender and also switch off windows defender to make sure, error still there.
[stdout.txt](https://github.com/yquake2/yquake2/files/10506696/stdout.txt)

**Comment by Yamagi** [comment]
Mkay, this was our bug and is was complicated. After about 90 minutes of debugging: When the `game` cvar was reset from a mod to baseq2 (the cvar is empty after the reset) the internal `fs_gamedir` variable representing the config dir was set to a pak file or an empty string. When `Sys_Mkdir()` was called on the path in hat variable the dir couldn't be created and the game crashed. It was broken in all cases, the default case without `-portable` worked by luck because the home directory is always at the start of the path list.

**Comment by Yamagi** [comment]
The build is here: https://deponie.yamagi.org/quake2/windows/testbuilds/quake2-20230204-74bb325.zip
