### ISSUE TITLE
Borehole

### ISSUE THREAD

**Issue by Sind6ex** [yquake2/yquake2#976]
Hi!

I don't know if you noticed a possible bug in "Borehole"-map but I'm sure it wasn't intended. When you come out of the tube there are two "Berserkers" heading towards you. If you step to the right just outside the tube you found yourself in a kind of corner, if you get there you're stuck unless you use the rocket-jump. I thought maybe map-fix can be done.

**Comment by BjossiAlfreds** [comment]
When you say stuck, do you mean stuck in an area or unable to move at all? The former can be quasi-fixed by putting something one can jump on like an explosive barrel with infinite health or a teleportation pad, but the other is a bug in the collision detection system which none of us dare to touch honestly.

**Comment by Sind6ex** [comment]
> When you say stuck, do you mean stuck in an area or unable to move at all? The former can be quasi-fixed by putting something one can jump on like an explosive barrel with infinite health or a teleportation pad, but the other is a bug in the collision detection system which none of us dare to touch honestly.

Hi!

I can't jump, I can't crouch, I can't move in any direction but I can rotate, shoot and as I said rocket-jump out of it.

**Comment by Sind6ex** [comment]
Hi!

I can't jump, I can't crouch, I can't move in any direction but I can rotate, shoot and as I said rocket-jump out of it.

**Comment by BjossiAlfreds** [comment]
That can happen in a number of other maps and locations. Unfortunately map fixes can only manipulate entities, not the BSP geometry of the map itself. This bug is more code territory, specifically in collision detection, id's CDS code is complex and easy to break so nobody dares to touch it because more likely than not we'll just introduce new problems.

**Comment by Sind6ex** [comment]
> That can happen in a number of other maps and locations. Unfortunately map fixes can only manipulate entities, not the BSP geometry of the map itself. This bug is more code territory, specifically in collision detection. id's CDS code is very complex and also very easy to break so nobody here dares to touch it because more likely than not we'll just introduce new problems.

I understand. Thank you for the explanation, I've been playing quake2 now and then since it came out -97.

Slav Ukraini!
